// @vitest-environment jsdom
import {act,cleanup,renderHook,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {ApiRequestError,fetchSavingsPlanRequestStatus,stageSavingsPlan} from '../api'
import {bindPlanScope} from './comfortablePlanRecovery'
import {useComfortablePlanMutation} from './useComfortablePlanMutation'
import {savingsFixture,savingsPlanDraft} from '../test/savingsFixtures'
vi.mock('../api',async original=>({...await original<typeof import('../api')>(),fetchSavingsPlanRequestStatus:vi.fn(),stageSavingsPlan:vi.fn()}))
const scope={user_id:901,household_id:77,enrollment_id:1}
const input={target_cents:25000,expected_plan_version_id:null,reason:'',financial_baseline_version_id:null,baseline_digest:null,spending_changes:[{budget_category_id:null,description:'Fictional comfortable lunch',recurrence:'unknown' as const,planned_reduction_cents:2500}]}
const result={record:savingsPlanDraft(),challenge:savingsFixture(),replayed:false}
afterEach(cleanup)
beforeEach(()=>{vi.clearAllMocks();bindPlanScope(null);sessionStorage.clear()})
it('preserves exact payload/key across navigation and stores only identity metadata',async()=>{vi.mocked(stageSavingsPlan).mockRejectedValueOnce(new ApiRequestError('Uncertain',{status:503})).mockResolvedValueOnce(result);const done=vi.fn();const first=renderHook(()=>useComfortablePlanMutation(scope,done,vi.fn()));await act(async()=>{await first.result.current.perform('plan_stage',input)});const request=vi.mocked(stageSavingsPlan).mock.calls[0];expect(sessionStorage.getItem('comfortable-plan-request-identities-v1')).not.toContain('comfortable lunch');expect(sessionStorage.getItem('comfortable-plan-request-identities-v1')).not.toContain('target_cents');first.unmount();const next=renderHook(()=>useComfortablePlanMutation(scope,done,vi.fn()));await act(async()=>{await next.result.current.retry?.()});expect(vi.mocked(stageSavingsPlan).mock.calls[1].slice(0,2)).toEqual(request.slice(0,2));expect(done).toHaveBeenCalledOnce()})
it('reconciles committed status and does not convert in-flight into a fresh request',async()=>{vi.mocked(stageSavingsPlan).mockRejectedValue(new ApiRequestError('Uncertain',{status:503}));vi.mocked(fetchSavingsPlanRequestStatus).mockResolvedValueOnce({state:'in_flight',actor_scope:scope}).mockResolvedValueOnce({...result,state:'committed',replayed:true,actor_scope:scope});const done=vi.fn();const hook=renderHook(()=>useComfortablePlanMutation(scope,done,vi.fn()));await act(async()=>{await hook.result.current.perform('plan_stage',input)});await act(async()=>{await hook.result.current.check?.()});expect(hook.result.current.reviewFresh).toBeNull();expect(hook.result.current.busy).toBe(true);await act(async()=>{await hook.result.current.check?.()});expect(done).toHaveBeenCalledOnce();expect(hook.result.current.busy).toBe(false)})
it('on cold actor return retains only identity, requires checked unknown status before same-action re-review',async()=>{vi.mocked(stageSavingsPlan).mockRejectedValue(new ApiRequestError('Uncertain',{status:503}));vi.mocked(fetchSavingsPlanRequestStatus).mockResolvedValue({state:'unknown',can_retry:true,actor_scope:scope});const hook=renderHook(({current})=>useComfortablePlanMutation(current,vi.fn(),vi.fn()),{initialProps:{current:scope}});await act(async()=>{await hook.result.current.perform('plan_stage',input)});hook.rerender({current:{...scope,enrollment_id:2}});await waitFor(()=>expect(hook.result.current.pending).toBeNull());hook.rerender({current:scope});await waitFor(()=>expect(hook.result.current.pending).not.toBeNull());expect(hook.result.current.retry).toBeNull();expect(hook.result.current.reviewFresh).toBeNull();await act(async()=>{await hook.result.current.check?.()});expect(hook.result.current.reviewFresh).not.toBeNull();act(()=>hook.result.current.reviewFresh?.());expect(hook.result.current.freshAction?.action).toBe('plan_stage');expect(hook.result.current.busy).toBe(true);vi.mocked(stageSavingsPlan).mockResolvedValue(result);const originalKey=vi.mocked(stageSavingsPlan).mock.calls[0][1];await act(async()=>{await hook.result.current.perform('plan_approve',{accepted:true,expected_draft_lock_version:0,expected_plan_version_id:null},11)});expect(stageSavingsPlan).toHaveBeenCalledTimes(1);await act(async()=>{await hook.result.current.perform('plan_stage',{...input,target_cents:30000})});expect(vi.mocked(stageSavingsPlan).mock.calls[1][1]).toBe(originalKey);expect(hook.result.current.busy).toBe(false)})
it('stale approval conflict blocks further edits until fresh challenge context arrives',async()=>{vi.mocked(stageSavingsPlan).mockRejectedValue(new ApiRequestError('Baseline changed',{status:409}));const hook=renderHook(({fresh})=>useComfortablePlanMutation(scope,vi.fn(),vi.fn(),fresh),{initialProps:{fresh:0}});await act(async()=>{await hook.result.current.perform('plan_stage',input)});expect(hook.result.current.needsRefresh).toBe(true);hook.rerender({fresh:1});await waitFor(()=>expect(hook.result.current.needsRefresh).toBe(false))})

it('retains the key when a fresh same-action review conflicts, then checks the original committed result',async()=>{vi.mocked(stageSavingsPlan).mockRejectedValueOnce(new ApiRequestError('Uncertain',{status:503})).mockRejectedValueOnce(new ApiRequestError('Original request won',{status:409}));vi.mocked(fetchSavingsPlanRequestStatus).mockResolvedValueOnce({state:'unknown',can_retry:true,actor_scope:scope}).mockResolvedValueOnce({...result,state:'committed',replayed:true,actor_scope:scope});const done=vi.fn();const hook=renderHook(({current})=>useComfortablePlanMutation(current,done,vi.fn()),{initialProps:{current:scope}});await act(async()=>{await hook.result.current.perform('plan_stage',input)});hook.rerender({current:{...scope,enrollment_id:2}});await waitFor(()=>expect(hook.result.current.pending).toBeNull());hook.rerender({current:scope});await waitFor(()=>expect(hook.result.current.pending).not.toBeNull());await act(async()=>{await hook.result.current.check?.()});act(()=>hook.result.current.reviewFresh?.());await act(async()=>{await hook.result.current.perform('plan_stage',{...input,target_cents:30000})});expect(hook.result.current.pending?.input).toBeUndefined();expect(hook.result.current.busy).toBe(true);await act(async()=>{await hook.result.current.check?.()});expect(done).toHaveBeenCalledOnce();expect(hook.result.current.busy).toBe(false)})
