export type BaselineScope = { user_id: number; household_id: number }
export type BaselineCategoryChoice = { budget_category_id: number | null; eligible: boolean; recurrence: 'unknown' | 'recurring' | 'one_off' | 'seasonal' | 'annual'; reason: string }
export type BaselineActualDecision = { transaction_id: number; event_type: 'purchase' | 'fee' | 'interest' | 'transfer' | 'debt_payment' | 'cash_withdrawal'; disposition: 'include' | 'exclude' | 'match'; tracked_account_id?: number | null; cash?: boolean; overlap_disposition: 'new' | 'distinct' | 'match'; source_review_version_id?: number | null; matched_transaction_id?: number | null; reason: string }
export type BaselineCashAllocation = { source_review_version_id: number; transaction_id: number; amount_cents: number; reason: string }
export type BaselineRequest = { window_start_on: string; window_end_on: string; revision_ids: number[]; tracked_account_ids: number[]; household_scope_attested: boolean; missing_accounts: string[]; cash_coverage: 'complete' | 'partial' | 'not_used' | 'unknown'; category_eligibility: BaselineCategoryChoice[]; actual_decisions: BaselineActualDecision[]; cash_allocations: BaselineCashAllocation[] }
export type BaselineSource = { document_import_id: number; revision_id: number; filename: string; source_available: boolean; coverage_status: string | null; coverage_current: boolean; approved_rows: number; total_rows: number; accounts: Array<{ tracked_account_id: number; label: string; period_start_on: string | null; period_end_on: string | null }> }
export type BaselineContext = { actor_scope: BaselineScope; local_today: string; records: BaselineSource[]; next_cursor: number | null; categories: Array<{ id: number; name: string }> }
export type BaselineRow = { key: string; source_review_version_id?: number; actual_id?: number; revision_id?: number; tracked_account_id?: number | null; classification: string; signed_amount_cents: number | null; purchase_amount_cents: number | null; posted_on: string | null; merchant: string | null; expense: boolean; source_type: string; cash?: boolean; splits: Array<{ budget_category_id: number | null; amount_cents: number }> }
export type BaselinePatternCategory = Omit<BaselineCategoryChoice, 'eligible' | 'reason'> & { reason: string | null; name: string; active: boolean; eligible: boolean | null; frequency: number; gross_cents: number; refunds_cents: number; net_cents: number; prior_window_refunds_cents: number }
export type BaselineMovement = { count: number; inflow_cents: number; outflow_cents: number }
export type BaselinePreview = { actor_scope?: BaselineScope; local_today?: string; digest: string; calculation_version: string; request: BaselineRequest; window_start_on: string; window_end_on: string; window_days: number; window_complete_calendar_month_count: number; supported_complete_calendar_month_count: number; observed_spending_known: boolean; complete_eligible: boolean; deficiencies: string[]; assumptions: string[]; represented_row_count: number; sample_limit: number; aggregates_use_full_window: true; sample_rows: BaselineRow[]; category_eligibility: Array<Omit<BaselineCategoryChoice, 'eligible' | 'reason'> & { reason: string | null; name: string; active: boolean; eligible: boolean | null }>; account_coverage: Array<{ tracked_account_id: number; account_basis: 'asset' | 'liability'; approved_intervals: string[][]; missing_ranges: Array<{ start_on: string; end_on: string }>; complete: boolean }>; possible_overlaps: Array<{ actual_id: number; possible_canonical_keys: string[]; proof: string }>; cash: { coverage: string; withdrawal_cents: number; allocated_purchase_cents: number; unallocated_withdrawal_cents: number; manual_cash_purchase_cents: number; cash_balance_known: false; savings_inferred: false }; patterns: { gross_spending_cents: number; allocated_refunds_cents: number; prior_window_refunds_cents: number; net_spending_cents: number; same_window_net_spending_cents: number; eligible_gross_spending_cents: number; eligible_net_spending_cents: number; prior_window_eligible_refunds_cents: number; comparable_eligible_spending_cents: number; expense_count: number; source_row_count: number; unallocated_refund_cents: number; transfers: BaselineMovement; debt_payments: BaselineMovement; cash_withdrawals: BaselineMovement; income_cents: number; merchants: Array<{ merchant: string; frequency: number; gross_cents: number; refunds_cents: number; net_cents: number; prior_window_refunds_cents: number; observed_dates: string[] }>; categories: BaselinePatternCategory[]; months: Array<{ month: string; gross_cents: number; refunds_cents: number; net_cents: number; prior_window_refunds_cents: number; frequency: number }> } }
export type BaselineVersion = { id: number; version_number: number; digest: string; window_start_on: string; window_end_on: string; coverage_status: 'complete' | 'partial' | 'manual'; reason: string; supersedes_id: number | null; calculation_version: string; created_at: string; preview: BaselinePreview }
export type BaselineCurrent = { actor_scope: BaselineScope; local_today: string; head_id: number | null; lock_version: number; approved_version: BaselineVersion | null; needs_revision?: boolean; current_dataset_digest?: string | null; current_deficiencies?: string[] }
export type BaselineApproval = { request: BaselineRequest; expected_preview_digest: string; base_version_id: number | null; base_lock_version: number; coverage_status: 'complete' | 'partial' | 'manual'; reason: string }
export type BaselineMutation = { actor_scope: BaselineScope; local_today: string; record: BaselineVersion; replayed: boolean }
export type BaselineStatus = ({ state: 'committed'; record: BaselineVersion; replayed: true } | { state: 'unknown'; can_retry: true } | { state: 'in_flight' }) & { actor_scope: BaselineScope; local_today: string }
export function sameBaselineScope(left: BaselineScope | null | undefined, right: BaselineScope | null | undefined): boolean { return Boolean(left && right && left.user_id === right.user_id && left.household_id === right.household_id) }
export function validateBaselineWindow(start: string, end: string, today: string) {
  const exact = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(Date.parse(`${value}T00:00:00Z`)) && new Date(`${value}T00:00:00Z`).toISOString().slice(0,10) === value
  if (!exact(start) || !exact(end) || !exact(today) || start > end || end > today || (Date.parse(`${end}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86_400_000 >= 366) throw new Error('Choose a past period of 1–366 days using valid dates.')
}
export function baselineMoney(cents: number): string { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100) }
export function baselineLimit(code: string): string {
  const labels: Record<string,string> = { source_coverage_not_complete: 'A statement has incomplete or outdated participant-approved coverage.', source_account_outside_declared_scope: 'A source account is outside the accounts you selected.', stale_source_account_identity: 'An account identity changed and needs statement review.', split_funding_unresolved: 'A complete purchase needs reviewed funding links.', ambiguous_actual_overlap: 'A recorded expense may overlap another source. Compare the original copies before matching.', household_account_scope_not_attested: 'Household account scope has not been explicitly checked.', missing_accounts_declared: 'You identified missing household account history.', cash_coverage_unknown_or_partial: 'Cash coverage is unknown or partial.', no_approved_observations: 'There are no approved spending observations; spending is unknown.', no_declared_statement_accounts: 'No statement accounts were declared.', account_window_incomplete: 'A selected account has gaps in this period.', known_source_account_omitted: 'A known account with history in this period was omitted.', actual_classification_unreviewed: 'An existing transaction still needs its spending or movement classification reviewed.', actual_account_unassigned: 'An existing transaction needs a recognized account or cash assignment.', actual_account_outside_declared_scope: 'A recorded transaction belongs to an account outside the selected scope.', active_actual_excluded: 'An active recorded transaction was deliberately excluded; coverage remains limited.', actual_cash_conflicts_with_declared_scope: 'A cash purchase conflicts with your no-cash declaration.', actual_split_total_unresolved: 'A recorded transaction has unresolved category splits.', typed_actual_without_selected_source: 'A spending entry refers to a statement not included in this baseline.', category_eligibility_unreviewed: 'A spending category still needs your consideration and recurrence choice.', refund_allocation_unresolved: 'A refund needs its original purchase allocation reviewed.', conflicting_account_period_headers: 'Statements for the same account period disagree.', account_balance_discontinuity: 'Adjacent statement balances do not agree.', current_baseline_inputs_unavailable: 'Some previously approved baseline inputs are no longer available.' }
  return labels[code.split(':')[0]] ?? 'Additional source coverage or classification review is needed.'
}
export type BaselineActualRecord = { id: number; posted_on: string; merchant: string | null; amount_cents: number; source_type: string; digest: string; splits: Array<{ budget_category_id: number | null; category_name: string | null; amount_cents: number }> }
export type BaselineObservationKind = 'actual' | 'purchase' | 'withdrawal'
export type BaselineObservationPage<T> = { actor_scope: BaselineScope; local_today: string; kind: BaselineObservationKind; records: T[]; next_cursor: number | null }
export type BaselineReviewedActual = { record: BaselineActualRecord; decision: BaselineActualDecision; match?: { source?: import('./participantSourceReview').ReviewedRow; actual?: BaselineActualRecord } }
export type BaselineReviewedCash = { withdrawal: import('./participantSourceReview').ReviewedRow; purchase: BaselineActualRecord; allocation: BaselineCashAllocation }
