import { describe, expect, it } from 'vitest'
import { checkedDebtSummary, checkedDebtTerms, debtApr, debtMoney, debtNullableDecimal, debtScopeMatches } from './optionalDebt'
import { debtFixtureScope, fictionalTerms, syntheticDebtApi } from '../test/optionalDebtFixtures'
describe('exact optional debt terms and response fences', () => {
  it('keeps unknown separate from reviewed zero in cents and APR basis points', () => { expect(debtNullableDecimal('')).toBeNull(); expect(debtNullableDecimal('0')).toBe(0); expect(debtNullableDecimal('19.99', true)).toBe(1999); expect(debtMoney(null)).toBe('Unknown'); expect(debtMoney(0)).toBe('$0.00'); expect(debtApr(0)).toBe('0.00%'); expect(debtApr(null)).toBe('Unknown') })
  it('rejects rounding, signs, scientific notation, unsafe integers and unsupported APR precision', () => { for (const value of ['1.005', '-1', '1e3', '1,000', 'Infinity', '90071992547409.92']) expect(() => debtNullableDecimal(value)).toThrow(); expect(() => debtNullableDecimal('1000.01', true)).toThrow(); expect(debtNullableDecimal('1000', true)).toBe(100000) })
  it('checks calendar, paid-off claims and partial-rate overallocations', () => { for (const changes of [{ as_of_on: '2026-02-30' }, { as_of_on: '0000-01-01' }, { status: 'paid_off' as const, balance_cents: null }, { apr_bps: 1.5 }, { rate_segments: [{ label: 'Excess', balance_cents: 30001, apr_bps: null, promotional_expires_on: null, post_promo_apr_bps: null }] }]) expect(() => checkedDebtTerms(fictionalTerms(changes))).toThrow() })
  it('allows nil enrollment only for in-flight metadata and rejects any wrong identity', () => { const envelope = { actor_scope: debtFixtureScope, cohort_id: 701, enrollment_id: null }; expect(debtScopeMatches(envelope, debtFixtureScope)).toBe(false); expect(debtScopeMatches(envelope, debtFixtureScope, true)).toBe(true); for (const key of ['user_id', 'household_id', 'cohort_id', 'enrollment_id'] as const) { const scope = { ...debtFixtureScope, [key]: 999 }; expect(debtScopeMatches({ actor_scope: debtFixtureScope, cohort_id: 701, enrollment_id: 801 }, scope)).toBe(false) } })
  it('refuses wrong enrollment context, false portfolio completeness and fabricated payment recommendations', async () => { const summary = await syntheticDebtApi().summary(701); expect(checkedDebtSummary(summary, debtFixtureScope, 701)).toEqual(summary); for (const value of [{ ...summary, cohort_id: 999 }, { ...summary, actor_scope: { ...summary.actor_scope, household_id: 999 } }, { ...summary, portfolio_complete: true }, { ...summary, extra_payment_cents: 500 }]) expect(() => checkedDebtSummary(value as typeof summary, debtFixtureScope, 701)).toThrow() })
})
