// @vitest-environment jsdom
import {beforeEach,expect,it} from 'vitest'
import {evidenceCandidate} from '../test/evidenceFixtures'
import {clearEvidenceIdentity,readEvidenceIdentity,saveEvidenceIdentity,evidenceRecoveryStorage} from './evidenceRecovery'
import {evidenceProof,validateEvidenceSelections,type EvidenceCandidate} from './savingsEvidence'
beforeEach(()=>sessionStorage.clear())
it('requires exact positive allocations within entry and canonical capacities, rejecting reused movement legs',()=>{const candidate=evidenceCandidate();expect(validateEvidenceSelections([{candidate,amount_cents:2550}],5000)).toBe(2550);for(const cents of [0,1.5,5001])expect(()=>validateEvidenceSelections([{candidate,amount_cents:cents}],5000)).toThrow();expect(()=>validateEvidenceSelections([{candidate,amount_cents:2500},{candidate:{...candidate,source_review_version_id:102},amount_cents:1000}],5000)).toThrow('twice');expect(evidenceProof(candidate,2550)).toEqual({source_review_version_id:101,expected_source_digest:'a'.repeat(64),expected_account_identity_digest:'b'.repeat(64),economic_group_version_id:null,expected_group_digest:null,amount_cents:2550})})
it('persists only scoped identity and never a financial body; other actor or entry cannot recover it',()=>{const scope={user_id:901,household_id:77,enrollment_id:7,entry_version_id:11};const request={scope,action:'attach' as const,key:'original-key',input:{reason:'PRIVATE',proofs:[{amount_cents:2500}]}};saveEvidenceIdentity(request);const stored=sessionStorage.getItem(evidenceRecoveryStorage)!;expect(stored).not.toContain('PRIVATE');expect(stored).not.toContain('amount_cents');expect(readEvidenceIdentity({...scope,user_id:902})).toBeNull();expect(readEvidenceIdentity({...scope,entry_version_id:12})).toBeNull();expect(readEvidenceIdentity(scope)?.key).toBe('original-key');clearEvidenceIdentity({...request,key:'wrong'});expect(readEvidenceIdentity(scope)).not.toBeNull();clearEvidenceIdentity(request);expect(readEvidenceIdentity(scope)).toBeNull()})
it('requires both human transfer legs for participant review while allocation counts once',()=>{const candidate:EvidenceCandidate={...evidenceCandidate(),movement_kind:'reviewed_asset_transfer' as const,economic_group_version_id:3,expected_group_digest:'c'.repeat(64),canonical_event_ids:[1,2]};expect(()=>validateEvidenceSelections([{candidate,amount_cents:2500}],5000)).toThrow('paired transfer details');candidate.movement_legs=[{merchant:'Transfer out',posted_on:'2026-10-02',account_label:'Checking',filename:'Checking.pdf',source_available:false,signed_amount_cents:-5000},{merchant:'Transfer in',posted_on:'2026-10-02',account_label:'Reserve',filename:'Reserve.pdf',source_available:true,signed_amount_cents:5000}];expect(validateEvidenceSelections([{candidate,amount_cents:2500}],5000)).toBe(2500)})
