import {requestStorageError} from './durableRequestIdentity'
import {useEffect,useRef,useState} from 'react'
import {ApiRequestError,approveSavingsPlan,fetchSavingsPlanRequestStatus,stageSavingsPlan} from '../api'
import {sameBaselineScope} from './financialBaseline'
import type {SavingsMutation,SavingsPlanApproval,SavingsPlanInput} from './savingsChallenge'
import {bindPlanScope,clearPlanRequest,isPlanScope,readPlanRequest,savePlanRequest,subscribePlanRequest,type PlanRequest,type PlanScope} from './comfortablePlanRecovery'
export function useComfortablePlanMutation(scope:PlanScope|undefined,onDone:(result:SavingsMutation<unknown>)=>void,onDenied:()=>void,freshness=0){
 const[,update]=useState(0);const[needsRefresh,setNeedsRefresh]=useState(false);const[error,setError]=useState<string|null>(null);const live=useRef(true);const controllers=useRef(new Set<AbortController>())
 useEffect(()=>{live.current=true;const owned=controllers.current;return()=>{live.current=false;for(const controller of owned)controller.abort();owned.clear()}},[])
 useEffect(()=>subscribePlanRequest(()=>update(value=>value+1)),[])
 useEffect(()=>{if(scope)bindPlanScope(scope)},[scope])
 useEffect(()=>{queueMicrotask(()=>{setNeedsRefresh(false);setError(null)})},[freshness])
 const pending=readPlanRequest(scope)
 useEffect(()=>{if(!pending)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[pending])
 async function perform(request:PlanRequest){if(!scope||!isPlanScope(scope)||!request.input||readPlanRequest(scope)?.working)return;const old=readPlanRequest(scope);if(old&&old.key!==request.key)return;if(!savePlanRequest({...request,working:false,unknown:false,error:undefined})){if(live.current)setError(requestStorageError);return}const controller=new AbortController();controllers.current.add(controller);savePlanRequest({...request,working:true,unknown:false});setError(null)
 try{const result=request.action==='plan_stage'?await stageSavingsPlan(request.input as SavingsPlanInput,request.key,controller.signal):await approveSavingsPlan(request.draftId!,request.input as SavingsPlanApproval,request.key,controller.signal);if(!isPlanScope(scope))return;if(result.challenge.enrollment?.id!==scope.enrollment_id)throw new Error('Private enrollment changed. Check the request in its original workspace.');clearPlanRequest(request.key);if(live.current)onDone(result)}
 catch(failure){if(!isPlanScope(scope))return;const message=failure instanceof Error?failure.message:'Plan review unavailable.';if(failure instanceof ApiRequestError&&failure.status===409&&request.recoveryReview)savePlanRequest({...request,input:undefined,working:false,awaitingFreshReview:false,unknown:false,error:'The fresh review conflicted with this retained request. Check the earlier result before continuing.'});else if(failure instanceof ApiRequestError&&[400,401,403,404,409,422].includes(failure.status))clearPlanRequest(request.key);else savePlanRequest({...request,working:false,error:message});if(live.current){setError(message);if(failure instanceof ApiRequestError&&failure.status===409)setNeedsRefresh(true);if(failure instanceof ApiRequestError&&[401,403,404].includes(failure.status))onDenied()}}
 finally{controllers.current.delete(controller)} }
 async function check(){if(!scope||!pending||pending.working||!isPlanScope(scope))return;savePlanRequest({...pending,working:true,unknown:false});try{const result=await fetchSavingsPlanRequestStatus(pending.action,pending.key);if(!isPlanScope(scope))return;if(!sameBaselineScope(result.actor_scope,scope))throw new ApiRequestError('Private plan scope changed.',{status:403});if(result.state==='committed'){if(result.challenge.enrollment?.id!==scope.enrollment_id)throw new Error('Private enrollment changed.');clearPlanRequest(pending.key);if(live.current){setError(null);onDone(result)}}else savePlanRequest({...pending,working:false,unknown:result.state==='unknown',error:result.state==='in_flight'?'Your earlier plan request is still processing. Check again.':pending.input?'No committed result found. Retry the exact saved request.':'No committed result found, and this page no longer holds the original inputs. Explicitly release the request before preparing a fresh review.'})}catch(failure){if(!isPlanScope(scope))return;if(failure instanceof ApiRequestError&&[401,403,404].includes(failure.status)){clearPlanRequest(pending.key);if(live.current)onDenied()}else savePlanRequest({...pending,working:false,error:failure instanceof Error?failure.message:'Plan status unavailable.'})}}
 return{pending,needsRefresh,busy:Boolean(pending),error:pending?.error??error,perform:(action:PlanRequest['action'],input:SavingsPlanInput|SavingsPlanApproval,draftId?:number)=>{if(!scope)return Promise.resolve();const old=readPlanRequest(scope);if(old){if(!old.awaitingFreshReview||old.action!==action||old.draftId!==draftId)return Promise.resolve();return perform({...old,input,working:false,awaitingFreshReview:false,recoveryReview:true})}return perform({scope,action,input,draftId,key:crypto.randomUUID(),working:false})},retry:pending?.input&&!pending.working?()=>perform(pending):null,check:pending&&!pending.working?check:null,freshAction:pending?.awaitingFreshReview?{action:pending.action,draftId:pending.draftId}:null,reviewFresh:pending?.unknown&&!pending.input&&!pending.working?()=>{savePlanRequest({...pending,awaitingFreshReview:true,unknown:false,error:'Re-review only this same plan action. The original request key is retained; unrelated changes remain blocked.'});setError(null)}:null}
}
