import {useEffect,useRef,useState} from 'react'
import {ApiRequestError} from '../api'
import {fetchSavingsEvidenceStatus,mutateSavingsEvidence} from '../evidenceApi'
import {clearEvidenceIdentity,readEvidenceIdentity,saveEvidenceIdentity,type EvidenceIdentity} from './evidenceRecovery'
import {evidenceRecoveryScopeMatches,type EvidenceAction,type EvidenceInput,type EvidenceMutation,type EvidenceScope} from './savingsEvidence'
type Pending=EvidenceIdentity&{input?:EvidenceInput;working:boolean;unknown?:boolean;fresh?:boolean;recovery?:boolean;error?:string}
export function useEvidenceMutation(scope:EvidenceScope|undefined,onDone:(result:EvidenceMutation)=>void,onDenied:()=>void,onConflict:()=>void){
 const[pending,setPending]=useState<Pending|null>(null);const[error,setError]=useState<string|null>(null);const active=useRef<string|null>(null);const generation=useRef(0);const current=useRef<Pending|null>(null);const controllers=useRef(new Set<AbortController>());const scopeKey=scope?`${scope.user_id}:${scope.household_id}:${scope.enrollment_id}:${scope.entry_version_id}`:null
 const save=(request:Pending|null)=>{current.current=request;setPending(request);if(request)saveEvidenceIdentity(request)}
 useEffect(()=>{active.current=scopeKey;generation.current++;const old=scope?readEvidenceIdentity(scope):null;current.current=old?{...old,working:false,error:'An earlier evidence request needs its result checked.'}:null;queueMicrotask(()=>{setPending(current.current);setError(null)});const owned=controllers.current;return()=>{active.current=null;for(const controller of owned)controller.abort();owned.clear();current.current=null}},[scopeKey,scope])
 useEffect(()=>{if(!pending)return;const guard=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[pending])
 async function run(request:Pending,check=false){if(!scope||active.current!==scopeKey||current.current?.working)return;if(!check&&!saveEvidenceIdentity(request)){current.current=null;setPending(null);setError('Request identity could not be retained in this browser. No proof change was submitted. Allow session storage before trying again.');return;}const epoch=generation.current;const controller=new AbortController();controllers.current.add(controller);save({...request,working:true,unknown:false});setError(null)
  try{const result=check?await fetchSavingsEvidenceStatus(request.action,scope.entry_version_id,request.key,controller.signal):await mutateSavingsEvidence(request.action,request.input!,request.key,controller.signal);if(active.current!==scopeKey||epoch!==generation.current)return;if(!evidenceRecoveryScopeMatches(result,scope))throw new ApiRequestError('Private evidence scope changed. Close and reopen this view.',{status:403});if(!('record'in result)){save({...request,working:false,unknown:result.state==='unknown',error:result.state==='in_flight'?'The earlier request is still processing. Check again.':request.input?'No committed result found. You may retry the exact request.':'No committed result found. Re-review only this same action with the retained request key.'});return}clearEvidenceIdentity(request);save(null);onDone(result as EvidenceMutation)
  }catch(failure){if(active.current!==scopeKey||epoch!==generation.current)return;const message=failure instanceof Error?failure.message:'Evidence request unavailable.';if(failure instanceof ApiRequestError&&failure.status===409)onConflict();if(failure instanceof ApiRequestError&&[401,403,404].includes(failure.status)){save({...request,input:undefined,working:false,error:message});onDenied()}else if(failure instanceof ApiRequestError&&failure.status>=400&&failure.status<500&&!(request.recovery&&failure.status===409)&&!check){clearEvidenceIdentity(request);save(null);setError(message)}else save({...request,input:request.recovery&&failure instanceof ApiRequestError&&failure.status===409?undefined:request.input,working:false,fresh:false,error:message});
  }finally{controllers.current.delete(controller)}
 }
 return{pending,error,submit:(action:EvidenceAction,input:EvidenceInput)=>{if(!scope)return Promise.resolve();const old=current.current;if(old){if(!old.fresh||old.action!==action)return Promise.resolve();return run({...old,input,working:false,fresh:false,recovery:true})}return run({scope,action,input,key:crypto.randomUUID(),working:false})},check:pending&&!pending.working?()=>run(pending,true):null,retry:pending?.input&&!pending.working?()=>run(pending):null,reviewFresh:pending?.unknown&&!pending.input&&!pending.working?()=>save({...pending,fresh:true,unknown:false,error:'Re-review this same action. Its original request key is retained.'}):null}
}
