import { expect, test } from '@playwright/test'
test('BOG UI Coach Studio metadata and explicit current sharing fit each viewport', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/coach-challenge.html')
  await page.getByLabel('Challenge group').selectOption('1')
  await expect(page.getByText('Fictional pilot participant')).toBeVisible()
  await expect(page.getByText(/Check-in unavailable/)).toBeVisible()
  await expect(page.getByText(/\$100.00 reported/)).toHaveCount(0)
  await page.getByRole('button', { name: 'Open permitted help & sharing' }).click()
  await page.getByRole('button', { name: 'Check current sharing permissions' }).click()
  await page.getByRole('button', { name: 'Open consented savings summary' }).click()
  await expect(page.getByText(/\$100.00 reported/)).toBeVisible()
  await page.getByRole('button', { name: 'Synthetic revoke sharing' }).click()
  await page.getByRole('button', { name: 'Check current sharing permissions' }).click()
  await expect(page.getByRole('alert')).toContainText('Synthetic sharing revoked')
  await expect(page.getByText(/\$100.00 reported/)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('synthetic-coach-private-view.png'), fullPage: true })
})
test('BOG UI fixed coarse report review and private export choices are explicit', async ({ page }) => {
  await page.goto('/e2e/fixtures/coach-challenge.html')
  await page.getByLabel('Challenge group').selectOption('1')
  await page.getByText('Checkpoint reports', { exact: true }).click()
  await page.getByRole('button', { name: 'Review scheduled reports' }).click()
  await expect(page.getByRole('button', { name: 'Seal reviewed Day 30 report' })).toBeDisabled()
  await page.getByRole('checkbox', { name: /Seal the scheduled checkpoint/ }).check()
  await page.getByRole('button', { name: 'Seal reviewed Day 30 report' }).click()
  await expect(page.getByText('Progress bands suppressed by the reporting policy.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Download this coarse report' })).toBeVisible()
  await page.getByText('Download your private challenge record', { exact: true }).click()
  await expect(page.getByRole('checkbox', { name: /Include my optional feeling history/ })).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Download reviewed records' })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
