import { expect, test } from '@playwright/test'
test('BOG UI optional terms stage, separately approve, preserve unknowns and contain keyboard on every viewport', async ({ page }, info) => {
  await page.goto('/optional-debt-qa.html'); const opener = page.getByRole('button', { name: 'Open optional card review' }); await opener.focus(); await opener.press('Enter')
  const dialog = page.getByRole('dialog'); await expect(dialog).toBeVisible(); await expect(page.getByText(/No extra-payment amount or payoff date/)).toBeVisible()
  await page.getByRole('button', { name: 'Add optional card terms' }).click(); await page.getByRole('combobox', { name: 'How will you review these terms?' }).selectOption('manual'); await page.getByRole('textbox', { name: 'Card label', exact: true }).fill('Fictional phone card')
  await page.getByRole('textbox', { name: 'Balance in US dollars', exact: true }).fill('0'); await page.getByRole('textbox', { name: 'APR in percent', exact: true }).fill('19.99'); await page.getByRole('combobox', { name: 'Card status' }).selectOption('paid_off')
  await page.getByRole('button', { name: 'Review pending proposal' }).click(); const proposal = page.getByRole('region', { name: 'Pending proposal review' }); await expect(proposal.getByText('$0.00')).toBeVisible(); await expect(proposal.getByText('Unknown', { exact: true }).first()).toBeVisible(); await expect(page.getByRole('button', { name: 'Save pending proposal' })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'I reviewed this exact pending proposal and mapping choice.' }).check(); await page.getByRole('button', { name: 'Save pending proposal' }).click(); await expect(page.getByText('Pending proposal saved. Review it separately before approving.')).toBeVisible()
  await page.getByRole('button', { name: 'Review approval for draft 300' }).click(); await expect(page.getByRole('button', { name: 'Approve reviewed card terms' })).toBeDisabled(); await page.getByRole('checkbox', { name: 'I accept these exact reviewed card terms and mapping.' }).check(); await page.getByRole('button', { name: 'Approve reviewed card terms' }).click(); await expect(page.getByText('Card terms approved. Your savings are unchanged.')).toBeVisible()
  const bounds = await dialog.boundingBox(), viewport = page.viewportSize()!; expect(bounds!.x).toBeGreaterThanOrEqual(0); expect(bounds!.width).toBeLessThanOrEqual(viewport.width); expect(bounds!.height).toBeLessThanOrEqual(viewport.height); expect(await page.locator('.optional-debt-scroll').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('synthetic-optional-debt.png'), fullPage: true }); await page.getByRole('button', { name: 'Close card review' }).focus(); for (let i = 0; i < 10; i++) { await page.keyboard.press('Tab'); expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[role=dialog]')))).toBe(true) }
  await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible(); await expect(opener).toBeFocused()
})
test('BOG UI optional debt exact-key recovery survives cold reload and explicit source choice never invents rates', async ({ page }) => {
  await page.goto('/optional-debt-qa.html?scenario=uncertain'); await page.getByRole('button', { name: 'Open optional card review' }).click(); await page.getByRole('button', { name: 'Add optional card terms' }).click(); await page.getByRole('combobox', { name: 'How will you review these terms?' }).selectOption('source'); await page.getByRole('combobox', { name: 'Exact approved liability account' }).selectOption('901'); await expect(page.getByRole('textbox', { name: 'APR in percent', exact: true })).toHaveValue(''); await expect(page.getByRole('textbox', { name: 'Required minimum in US dollars' })).toHaveValue('')
  await page.getByRole('button', { name: 'Review pending proposal' }).click(); await page.getByRole('checkbox', { name: 'I reviewed this exact pending proposal and mapping choice.' }).check(); await page.getByRole('button', { name: 'Save pending proposal' }).click(); await expect(page.getByText(/Synthetic lost response/)).toBeVisible(); await expect(page.getByRole('button', { name: 'Retry exact card request' })).toHaveCount(0)
  const identity = await page.evaluate(() => JSON.parse(sessionStorage.getItem('optional-debt-request-identity-v1')!)); expect(JSON.stringify(identity)).not.toContain('87000'); expect(JSON.stringify(identity)).not.toContain('terms'); expect(identity.scope.cohort_id).toBe(701)
  await page.getByRole('button', { name: 'Close card review' }).click(); await page.reload(); await page.getByRole('button', { name: 'Open optional card review' }).click(); await page.getByRole('button', { name: 'Check earlier card result' }).click(); await page.getByRole('checkbox', { name: 'I will re-review this same action using its original request key.' }).check(); await page.getByRole('button', { name: 'Prepare original request review' }).click(); await page.getByRole('combobox', { name: 'How will you review these terms?' }).selectOption('manual'); await page.getByRole('textbox', { name: 'Card label', exact: true }).fill('Fictional rereview')
  await page.getByRole('button', { name: 'Review pending proposal' }).click(); await page.getByRole('checkbox', { name: 'I reviewed this exact pending proposal and mapping choice.' }).check(); await page.getByRole('button', { name: 'Save pending proposal' }).click(); await expect(page.getByText(/Synthetic lost response/)).toBeVisible(); const retained = await page.evaluate(() => JSON.parse(sessionStorage.getItem('optional-debt-request-identity-v1')!)); expect(retained.key).toBe(identity.key)
  await page.getByRole('button', { name: 'Check earlier card result' }).click(); await page.getByRole('button', { name: 'Retry exact card request' }).click(); await expect(page.getByText('Pending proposal saved. Review it separately before approving.')).toBeVisible()
})
