import type { BaselineContext, BaselineCurrent, BaselinePreview, BaselineRequest, BaselineVersion } from '../lib/financialBaseline'
export const baselineScope = { user_id: 901, household_id: 77 }
export const baselineContext: BaselineContext = { actor_scope:baselineScope,local_today:'2026-10-05',records:[{document_import_id:1203,revision_id:88,filename:'Fictional-checking.pdf',source_available:true,coverage_status:'complete',coverage_current:true,approved_rows:137,total_rows:137,accounts:[{tracked_account_id:2,label:'Fictional checking',period_start_on:'2026-09-01',period_end_on:'2026-09-30'}]}],next_cursor:null,categories:[{id:10,name:'Groceries'},{id:20,name:'Dining'}] }
export function baselineRequest():BaselineRequest{return {window_start_on:'2026-09-01',window_end_on:'2026-09-30',revision_ids:[],tracked_account_ids:[],household_scope_attested:false,missing_accounts:[],cash_coverage:'unknown',category_eligibility:[],actual_decisions:[],cash_allocations:[]}}
export function baselinePreview(request:BaselineRequest=baselineRequest(),known=false,complete=false):BaselinePreview{
  const category=request.category_eligibility.find((choice)=>choice.budget_category_id===10)
  const rule={budget_category_id:10,name:'Groceries',active:true,eligible:category?.eligible??null,recurrence:category?.recurrence??'unknown',reason:category?.reason??null} as const
  const movement={count:0,inflow_cents:0,outflow_cents:0}
  return {actor_scope:baselineScope,local_today:'2026-10-05',digest:JSON.stringify(request),calculation_version:'approved_spending_baseline_v1',request,window_start_on:request.window_start_on,window_end_on:request.window_end_on,window_days:30,window_complete_calendar_month_count:1,supported_complete_calendar_month_count:complete?1:0,observed_spending_known:known,complete_eligible:complete,deficiencies:complete?[]:known?['category_eligibility_unreviewed:10','account_window_incomplete:2']:['no_approved_observations','no_declared_statement_accounts','cash_coverage_unknown_or_partial','household_account_scope_not_attested'],assumptions:['Frequency does not establish future recurrence or saved cash.'],represented_row_count:known?137:0,sample_limit:50,aggregates_use_full_window:true,sample_rows:known?Array.from({length:50},(_,index)=>({key:`source:${4000+index}`,source_review_version_id:4000+index,revision_id:88,tracked_account_id:2,classification:'purchase',signed_amount_cents:-1000,purchase_amount_cents:1000,posted_on:'2026-09-15',merchant:`Fictional purchase ${index+1}`,expense:true,source_type:'reviewed_source',splits:[{budget_category_id:10,amount_cents:1000}]})):[],category_eligibility:known?[rule]:[],account_coverage:request.tracked_account_ids.length?[{tracked_account_id:2,account_basis:'asset',approved_intervals:[['2026-09-01','2026-09-30']],missing_ranges:complete?[]:[{start_on:'2026-09-29',end_on:'2026-09-30'}],complete}]:[],possible_overlaps:[],cash:{coverage:request.cash_coverage,withdrawal_cents:0,allocated_purchase_cents:0,unallocated_withdrawal_cents:0,manual_cash_purchase_cents:0,cash_balance_known:false,savings_inferred:false},patterns:{gross_spending_cents:known?137000:0,allocated_refunds_cents:known?2000:0,prior_window_refunds_cents:known?1000:0,net_spending_cents:known?135000:0,same_window_net_spending_cents:known?136000:0,eligible_gross_spending_cents:category?.eligible?137000:0,eligible_net_spending_cents:category?.eligible?135000:0,prior_window_eligible_refunds_cents:category?.eligible?1000:0,comparable_eligible_spending_cents:category?.eligible?136000:0,expense_count:known?137:0,source_row_count:known?137:0,unallocated_refund_cents:0,transfers:movement,debt_payments:movement,cash_withdrawals:movement,income_cents:0,merchants:known?Array.from({length:37},(_,index)=>({merchant:`Fictional merchant ${index+1}`,frequency:index===0?101:1,gross_cents:index===0?101000:1000,refunds_cents:index===0?2000:0,net_cents:index===0?99000:1000,prior_window_refunds_cents:index===0?1000:0,observed_dates:['2026-09-15']})):[],categories:known?[{...rule,frequency:137,gross_cents:137000,refunds_cents:2000,net_cents:135000,prior_window_refunds_cents:1000}]:[],months:known?[{month:'2026-09',gross_cents:137000,refunds_cents:2000,net_cents:135000,prior_window_refunds_cents:1000,frequency:137}]:[]}}
}
export function baselineVersion(preview=baselinePreview(baselineRequest(),true)):BaselineVersion{return {id:501,version_number:1,digest:preview.digest,window_start_on:preview.window_start_on,window_end_on:preview.window_end_on,coverage_status:'partial',reason:'Reviewed earlier limited context.',supersedes_id:null,calculation_version:preview.calculation_version,created_at:'2026-10-01T01:00:00Z',preview}}
export function baselineCurrent(version:BaselineVersion|null=null):BaselineCurrent{return {actor_scope:baselineScope,local_today:'2026-10-05',head_id:version?500:null,lock_version:version?1:0,approved_version:version,needs_revision:false}}
