import type { DebtCandidate, DebtCard, DebtDraft, DebtEnvelope, DebtInput, DebtPage, DebtScope, DebtSummary, DebtTerms, DebtVersion, OptionalDebtApi } from '../lib/optionalDebt'
export const debtFixtureScope: DebtScope = { user_id: 501, household_id: 601, cohort_id: 701, enrollment_id: 801 }
export const debtEnvelope: DebtEnvelope = { actor_scope: { user_id: 501, household_id: 601 }, cohort_id: 701, enrollment_id: 801 }
export const fictionalTerms = (changes: Partial<DebtTerms> = {}): DebtTerms => ({ label: 'Fictional reviewed card', as_of_on: '2026-11-01', balance_cents: 30000, minimum_payment_cents: null, apr_bps: null, due_on: null, promotional_apr_bps: null, promotional_expires_on: null, post_promo_apr_bps: null, rate_segments: [], status: 'active', ...changes })
const source = { source_tracked_account_id: null, source_account_identity_version_id: null, source_revision_approval_id: null, source_fingerprint: null, source_snapshot: {} }
export const fictionalVersion = (id = 10, cardId = 1, terms = fictionalTerms()): DebtVersion => ({ ...source, id, savings_debt_card_id: cardId, savings_enrollment_id: 801, previous_version_id: null, version_number: 1, terms, reason: 'Fictional review only', digest: 'a'.repeat(64), approved_at: '2026-11-01T00:00:00Z' })
export const fictionalDraft = (id = 300, cardId = 4, terms = fictionalTerms()): DebtDraft => ({ ...source, id, savings_debt_card_id: cardId, savings_enrollment_id: 801, terms, base_version_id: null, base_head_lock_version: 0, lock_version: 0, status: 'pending', approved_version_id: null, reason: 'Fictional pending review only' })
export const fictionalCandidate: DebtCandidate = { source_tracked_account_id: 900, source_account_identity_version_id: 901, source_revision_approval_id: 902, fingerprint: 'b'.repeat(64), label: 'Fictional approved liability', statement_as_of_on: '2026-10-31', snapshot: { statement_closing_balance_cents: 87000 }, proposed_terms: { balance_cents: 87000, as_of_on: '2026-10-31', minimum_payment_cents: null, apr_bps: null }, qualifications: ['APR and required minimum were not established by this source.'] }
export function syntheticDebtApi(options: { empty?: boolean; pageSize?: number; pending?: boolean } = {}): OptionalDebtApi {
  const versions = options.empty ? [] : [fictionalVersion(10, 1, fictionalTerms({ label: 'Fictional smaller card', balance_cents: 10000, apr_bps: 1500 })), fictionalVersion(20, 2, fictionalTerms({ label: 'Fictional paid-off card', balance_cents: 0, minimum_payment_cents: 0, apr_bps: 2999, status: 'paid_off' })), fictionalVersion(30, 3, fictionalTerms({ label: 'Fictional unknown balance', balance_cents: null, apr_bps: 2500 }))]
  const cards: DebtCard[] = versions.map(version => ({ id: version.savings_debt_card_id, savings_enrollment_id: 801, lock_version: 1, current_version_id: version.id, source_tracked_account_id: null, current_version: version }))
  const drafts: DebtDraft[] = []
  if (options.pending) { cards.push({ id: 4, savings_enrollment_id: 801, lock_version: 0, current_version_id: null, source_tracked_account_id: null, current_version: null }); drafts.push(fictionalDraft()) }
  const committed = new Map<string, DebtDraft | DebtVersion>()
  const page = <T>(records: T[], cursor?: number | null): DebtPage<T> => { const selected = records.filter(row => (row as { id?: number; source_account_identity_version_id?: number }).id! > (cursor ?? 0) || !(row as { id?: number }).id && (row as DebtCandidate).source_account_identity_version_id > (cursor ?? 0)), size = options.pageSize ?? 50, shown = selected.slice(0, size); return { ...debtEnvelope, records: shown, next_cursor: selected.length > size ? ((shown.at(-1) as { id?: number }).id ?? (shown.at(-1) as DebtCandidate).source_account_identity_version_id) : null } }
  return {
    summary: async (): Promise<DebtSummary> => ({ ...debtEnvelope, local_today: '2026-11-01', portfolio_complete: false, known_balance_subtotal_cents: versions.length ? cards.reduce((sum, card) => sum + (card.current_version?.terms.balance_cents ?? 0), 0) : null, unknown_balance_count: cards.filter(card => card.current_version?.terms.balance_cents === null).length, stale_card_count: 0, cards: cards.filter(card => card.current_version).map(card => ({ card_id: card.id, version_id: card.current_version!.id, label: card.current_version!.terms.label, terms: card.current_version!.terms, source_stale: false, qualifications: [], promotional_expired: null, snowball_eligible: !!card.current_version!.terms.balance_cents, avalanche_eligible: !!card.current_version!.terms.balance_cents && card.current_version!.terms.apr_bps !== null })), snowball_order: cards.filter(card => card.current_version?.terms.balance_cents && card.current_version.terms.status === 'active').sort((a, b) => a.current_version!.terms.balance_cents! - b.current_version!.terms.balance_cents!).map(card => card.id), avalanche_order: cards.filter(card => card.current_version?.terms.balance_cents && card.current_version.terms.apr_bps !== null && card.current_version.terms.status === 'active' && !card.current_version.terms.rate_segments.length && card.current_version.terms.promotional_apr_bps === null && card.current_version.terms.promotional_expires_on === null && card.current_version.terms.post_promo_apr_bps === null).sort((a, b) => b.current_version!.terms.apr_bps! - a.current_version!.terms.apr_bps!).map(card => card.id), extra_payment_cents: null, payoff_date: null, savings_credit_cents: null, qualifications: [] }),
    records: async <T extends DebtCard | DebtDraft | DebtVersion>(_scope: DebtScope, kind: 'cards' | 'drafts' | 'versions', cursor?: number | null) => page<DebtCard | DebtDraft | DebtVersion>(({ cards, drafts, versions })[kind], cursor) as unknown as DebtPage<T>,
    candidates: async (_scope, cursor) => page([fictionalCandidate], cursor),
    mutate: async (_scope, action, input: DebtInput, key) => {
      const existing = committed.get(key); if (existing) return { ...debtEnvelope, record: existing, replayed: true }
      if (action === 'stage' && 'terms' in input) {
        let card = cards.find(row => row.id === input.card_id)
        if (!card) { card = { id: Math.max(0, ...cards.map(row => row.id)) + 1, savings_enrollment_id: 801, lock_version: 0, current_version_id: null, source_tracked_account_id: null, current_version: null }; cards.push(card) }
        const draft = { ...fictionalDraft(Math.max(299, ...drafts.map(row => row.id)) + 1, card.id, input.terms), reason: input.reason, base_version_id: input.expected_version_id, base_head_lock_version: input.expected_head_lock_version, ...(input.source_mapping ? { source_tracked_account_id: input.source_mapping.source_tracked_account_id, source_account_identity_version_id: input.source_mapping.source_account_identity_version_id, source_revision_approval_id: input.source_mapping.source_revision_approval_id, source_fingerprint: input.source_mapping.fingerprint } : {}) }
        drafts.push(draft); committed.set(key, draft); return { ...debtEnvelope, record: draft, replayed: false }
      }
      if (!('draft_id' in input)) throw new Error('Fictional request does not match approval.')
      const draft = drafts.find(row => row.id === input.draft_id)!, card = cards.find(row => row.id === draft.savings_debt_card_id)!, version = { ...fictionalVersion(Math.max(99, ...versions.map(row => row.id)) + 1, card.id, draft.terms), ...source, source_tracked_account_id: draft.source_tracked_account_id, source_account_identity_version_id: draft.source_account_identity_version_id, source_revision_approval_id: draft.source_revision_approval_id, source_fingerprint: draft.source_fingerprint, previous_version_id: card.current_version_id, version_number: (card.current_version?.version_number ?? 0) + 1, reason: draft.reason }
      versions.push(version); card.current_version_id = version.id; card.current_version = version; card.lock_version++; draft.status = 'approved'; draft.approved_version_id = version.id; committed.set(key, version)
      return { ...debtEnvelope, record: version, replayed: false }
    },
    status: async (_scope, _action, key) => { const record = committed.get(key); return record ? { ...debtEnvelope, state: 'committed', record, replayed: true } : { ...debtEnvelope, state: 'unknown', can_retry: true } },
  }
}
