import type { PrivacyApi, PrivacyCandidate, PrivacyState, RemindersState, SourceLease } from '../lib/challengePrivacy'
export const privacyScope = { user_id: 901, household_id: 902 }
export const privacyFixture: PrivacyState = { enrollment_id: 100, actor_scope: privacyScope, policy_version: 'challenge_privacy_v1', grants: [], support_requests: [], support_access: [], recipients: [{ id: 903, name: 'Fictional Mel', role: 'coach' }, { id: 904, name: 'Fictional Leon', role: 'admin' }], erasable_reflections: [{ id: 700, current_version_id: 701, lock_version: 2, created_at: '2026-11-01T02:00:00Z', erased_at: null }], reflections_next_cursor: null, downloaded_copies_retrievable: false }
export const remindersFixture: RemindersState = { enrollment_id: 100, actor_scope: privacyScope, time_zone: 'Pacific/Guam', email_delivery_enabled: false, dismissal_is_check_in: false, preferences: [{ id: null, lock_version: 0, channel: 'in_app', enabled: true, local_time: '18:00', quiet_start: '21:00', quiet_end: '08:00', policy_version: 'generic_daily_reminder_v1' }, { id: null, lock_version: 0, channel: 'email', enabled: false, local_time: '18:00', quiet_start: '21:00', quiet_end: '08:00', policy_version: 'generic_daily_reminder_v1' }], reminder: { id: 800, lock_version: 0, local_on: '2026-11-01', title: 'A moment for your day', body: 'Your optional daily check-in is ready.' } }
export const sourceFixture: SourceLease = { document_import_id: 500, source_available: true, latest_authorized_expiry: '2027-02-28T13:59:59Z', affected_uses: [{ id: 601, enrollment_id: 100, expires_at: '2027-02-28T13:59:59Z', revoked: false }, { id: 602, enrollment_id: 200, expires_at: '2027-03-14T13:59:59Z', revoked: false }], expected_affected_uses_digest: 'a'.repeat(64), disclosure_version: 'personal_end_plus_30_days_v1', expected_expires_at: '2027-02-28T13:59:59Z', expected_use_id: 601, expected_lock_version: 1, approved_financial_records_retained: true, downloaded_copies_retrievable: false, provider_backup_retention_verified: false }
export function syntheticPrivacyApi(): PrivacyApi {
  return {
    controls: async () => ({ actor_scope: privacyScope, records: [{ id: 100, cohort_id: 90, program_name: 'Fictional 90-day challenge', starts_on: '2026-11-01', ends_on: '2027-01-29', time_zone: 'Pacific/Guam', status: 'active' }], next_cursor: null }),
    privacy: async () => structuredClone(privacyFixture),
    candidates: async (_id, type) => ({ actor_scope: privacyScope, records: [{ record_type: type, record_id: 500, preview: type === 'document_source' ? { filename: 'Fictional sample statement.pdf' } : type === 'chat_message' ? { content_excerpt: 'Fictional private coaching conversation.', excerpt_only: true } : { signed_cents: 5000, effective_on: '2026-11-01' } as PrivacyCandidate['preview'], shares_entire_record: true }], next_cursor: null }),
    source: async () => structuredClone(sourceFixture), reminders: async () => structuredClone(remindersFixture),
    mutate: async () => ({ event: { id: 1000 }, replayed: false }), status: async () => ({ state: 'committed', actor_scope: privacyScope }),
  }
}
