// @vitest-environment jsdom
import { useState } from 'react'
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import { fetchBaselineObservations } from '../api'
import { baselineScope } from '../test/baselineFixtures'
import type { BaselineActualRecord,BaselineReviewedActual,BaselineReviewedCash } from '../lib/financialBaseline'
import type { ReviewedRow } from '../lib/participantSourceReview'
import { BaselineObservationReview } from './BaselineObservationReview'
vi.mock('../api',async(original)=>({...await original<typeof import('../api')>(),fetchBaselineObservations:vi.fn()}))
const actual:BaselineActualRecord={id:701,posted_on:'2026-09-15',merchant:'Fictional cash lunch',amount_cents:1000,source_type:'manual_ui',digest:'actual-current',splits:[{budget_category_id:20,category_name:'Dining',amount_cents:1000}]}
const withdrawal:ReviewedRow={id:801,digest:'withdrawal-current',version_number:1,reason:'Checked source',projection:{action:'none'},actual:null,current:true,recognized_account:{identity_version_id:100,tracked_account_id:2,label:'Fictional checking',account_basis:'asset',account_id:null,current:true},facts:{source_account_identity_version_id:100,disposition:'include',event_type:'cash_withdrawal',signed_amount_cents:-5000,purchase_amount_cents:null,posted_on:'2026-09-14',merchant:'Fictional ATM',budget_category_id:null,overlap_disposition:'canonical'},source:{document_import_id:1203,filename:'Fictional-checking.pdf',locator:{page:2,row:8},source_available:true}}
const onRevoked=vi.fn()
function Harness(){const[decisions,setDecisions]=useState<BaselineReviewedActual[]>([]);const[allocations,setAllocations]=useState<BaselineReviewedCash[]>([]);return <><BaselineObservationReview start="2026-09-01" end="2026-09-30" scope={baselineScope} accounts={[{tracked_account_id:2,label:'Fictional checking'}]} decisions={decisions} allocations={allocations} onDecisions={setDecisions} onAllocations={setAllocations} onRevoked={onRevoked} disabled={false}/><output data-testid="prepared">{JSON.stringify({decisions,allocations})}</output></>}
afterEach(cleanup)
beforeEach(()=>{onRevoked.mockReset();vi.mocked(fetchBaselineObservations).mockReset().mockImplementation(async(kind)=>({actor_scope:baselineScope,local_today:'2026-10-05',kind,records:kind==='actual'?[actual]:kind==='withdrawal'?[withdrawal]:[],next_cursor:null}))})
describe('baseline individual recorded decisions',()=>{
 it('leaves a recorded transaction unclassified until explicit account and classification consent',async()=>{render(<Harness/>);fireEvent.click(await screen.findByText(/Fictional cash lunch · 2026-09-15 · recorded amount/));expect((screen.getByLabelText('Classification for Fictional cash lunch') as HTMLSelectElement).value).toBe('');expect((screen.getByRole('button',{name:'Use this transaction decision in preview'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Classification for Fictional cash lunch'),{target:{value:'purchase'}});fireEvent.change(screen.getByLabelText('Account or cash for Fictional cash lunch'),{target:{value:'cash'}});fireEvent.change(screen.getByLabelText('Transaction review note for Fictional cash lunch'),{target:{value:'Reviewed the cash receipt.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I checked this recorded amount/}));fireEvent.click(screen.getByRole('button',{name:'Use this transaction decision in preview'}));expect(screen.getByTestId('prepared').textContent).toContain('"cash":true');expect(screen.getByTestId('prepared').textContent).toContain('"transaction_id":701');expect(screen.getByTestId('prepared').textContent).toContain('"event_type":"purchase"')})
 it('allocates exact cents from an approved withdrawal to an explicitly included cash purchase',async()=>{render(<Harness/>);fireEvent.click(await screen.findByText(/Fictional cash lunch · 2026-09-15 · recorded amount/));fireEvent.change(screen.getByLabelText('Classification for Fictional cash lunch'),{target:{value:'purchase'}});fireEvent.change(screen.getByLabelText('Account or cash for Fictional cash lunch'),{target:{value:'cash'}});fireEvent.change(screen.getByLabelText('Transaction review note for Fictional cash lunch'),{target:{value:'Cash receipt checked.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I checked this recorded amount/}));fireEvent.click(screen.getByRole('button',{name:'Use this transaction decision in preview'}));fireEvent.click(screen.getByText('Allocate reviewed cash withdrawals to cash purchases'));fireEvent.click(await screen.findByRole('radio',{name:/Fictional ATM.*Fictional-checking.pdf.*page 2/}));fireEvent.change(screen.getByLabelText('Reviewed cash purchase'),{target:{value:'701'}});fireEvent.change(screen.getByLabelText('Cash allocated to this purchase'),{target:{value:'10.005'}});fireEvent.change(screen.getByLabelText('Cash allocation review note'),{target:{value:'Compared withdrawal and cash receipt.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I checked this exact withdrawal/}));fireEvent.click(screen.getByRole('button',{name:'Use this cash allocation in preview'}));expect(screen.getByRole('alert').textContent).toContain('two decimal places');fireEvent.change(screen.getByLabelText('Cash allocated to this purchase'),{target:{value:'10.00'}});fireEvent.click(screen.getByRole('checkbox',{name:/I checked this exact withdrawal/}));fireEvent.click(screen.getByRole('button',{name:'Use this cash allocation in preview'}));expect(screen.getByTestId('prepared').textContent).toContain('"source_review_version_id":801');expect(screen.getByTestId('prepared').textContent).toContain('"amount_cents":1000')})
 it('requires an explicit canonical match and retains its original statement facts in the prepared decision',async()=>{
  const purchase:ReviewedRow={...withdrawal,id:802,facts:{...withdrawal.facts,event_type:'purchase',merchant:'Fictional card lunch',posted_on:actual.posted_on,signed_amount_cents:-1000,purchase_amount_cents:1000}}
  vi.mocked(fetchBaselineObservations).mockImplementation(async(kind)=>({actor_scope:baselineScope,local_today:'2026-10-05',kind,records:kind==='actual'?[actual]:kind==='purchase'?[purchase]:[],next_cursor:null}))
  render(<Harness/>);fireEvent.click(await screen.findByText(/Fictional cash lunch · 2026-09-15 · recorded amount/));fireEvent.change(screen.getByLabelText('Classification for Fictional cash lunch'),{target:{value:'purchase'}});fireEvent.change(screen.getByLabelText('How to use Fictional cash lunch'),{target:{value:'match'}});fireEvent.change(screen.getByLabelText('Transaction review note for Fictional cash lunch'),{target:{value:'Compared the original and this duplicate.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I checked this recorded amount/}));fireEvent.click(screen.getByRole('button',{name:'Use this transaction decision in preview'}));expect(screen.getByRole('alert').textContent).toContain('exact match');expect(screen.getByTestId('prepared').textContent).not.toContain('"source_review_version_id":802')
  fireEvent.click(await screen.findByRole('radio',{name:/Fictional card lunch.*Fictional-checking.pdf.*page 2/}));fireEvent.click(screen.getByRole('checkbox',{name:/I checked this recorded amount/}));fireEvent.click(screen.getByRole('button',{name:'Use this transaction decision in preview'}));expect(screen.getByTestId('prepared').textContent).toContain('"source_review_version_id":802');expect(screen.getByTestId('prepared').textContent).toContain('"filename":"Fictional-checking.pdf"');expect(screen.getByTestId('prepared').textContent).toContain('"overlap_disposition":"match"')
 })
 it('reports revoked observation access to clear the entire private baseline view',async()=>{vi.mocked(fetchBaselineObservations).mockResolvedValue({actor_scope:{user_id:902,household_id:78},local_today:'2026-10-05',kind:'actual',records:[actual],next_cursor:null});render(<Harness/>);await waitFor(()=>expect(onRevoked).toHaveBeenCalled());expect(screen.queryByText(/Fictional cash lunch · 2026-09-15 · recorded amount/)).toBeNull()})
})
