// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import * as api from '../api'
import { baselineContext,baselineCurrent,baselinePreview,baselineScope,baselineVersion } from '../test/baselineFixtures'
import { BaselineReview } from './BaselineReview'
import { bindBaselineActor,clearBaselineRecovery,readBaselineRecovery,setBaselineExpectedUser } from '../lib/baselineRecovery'
import { validateBaselineWindow } from '../lib/financialBaseline'
vi.mock('../api',async(original)=>({...await original<typeof import('../api')>(),fetchFinancialBaseline:vi.fn(),fetchBaselineContext:vi.fn(),previewFinancialBaseline:vi.fn(),approveFinancialBaseline:vi.fn(),fetchBaselineHistory:vi.fn(),fetchBaselineRequestStatus:vi.fn(),fetchBaselineObservations:vi.fn()}))
const view=()=> <BaselineReview scope={baselineScope} onClose={vi.fn()} onReviewStatements={vi.fn()}/>
afterEach(cleanup)
beforeEach(()=>{setBaselineExpectedUser(901);bindBaselineActor(baselineScope);const pending=readBaselineRecovery(baselineScope);if(pending)clearBaselineRecovery(pending.key);vi.mocked(api.fetchFinancialBaseline).mockReset().mockResolvedValue(baselineCurrent());vi.mocked(api.fetchBaselineContext).mockReset().mockResolvedValue(structuredClone(baselineContext));vi.mocked(api.previewFinancialBaseline).mockReset().mockImplementation(async(request)=>baselinePreview(request));vi.mocked(api.approveFinancialBaseline).mockReset().mockImplementation(async(_action,input)=>({actor_scope:baselineScope,local_today:'2026-10-05',record:baselineVersion(baselinePreview(input.request)),replayed:false}));vi.mocked(api.fetchBaselineRequestStatus).mockReset().mockResolvedValue({actor_scope:baselineScope,local_today:'2026-10-05',state:'committed',record:baselineVersion(),replayed:true});vi.mocked(api.fetchBaselineHistory).mockReset().mockResolvedValue({actor_scope:baselineScope,local_today:'2026-10-05',records:[],next_cursor:null});vi.mocked(api.fetchBaselineObservations).mockReset().mockResolvedValue({actor_scope:baselineScope,local_today:'2026-10-05',kind:'actual',records:[],next_cursor:null})})
async function period(){await screen.findByText('No approved baseline yet');fireEvent.change(screen.getByLabelText('Period begins'),{target:{value:'2026-09-01'}});fireEvent.change(screen.getByLabelText('Period ends'),{target:{value:'2026-09-30'}})}
async function preview(){fireEvent.click(screen.getByRole('button',{name:'Preview baseline and limitations'}));return screen.findByRole('region',{name:'Proposed baseline preview'})}
function consent(){fireEvent.change(screen.getByLabelText('Baseline approval explanation'),{target:{value:'Reviewed the exact period and its limits.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this period/}))}
describe('participant spending baseline',()=>{
 it('validates exact dates and a past inclusive period against the server Guam day',()=>{validateBaselineWindow('2026-01-01','2026-10-05','2026-10-05');for(const [start,end] of [['2026-02-30','2026-03-01'],['2026-10-05','2026-10-06'],['2025-10-01','2026-10-05'],['2026-09-30','2026-09-01']])expect(()=>validateBaselineWindow(start,end,'2026-10-05')).toThrow()})
 it('approves an honest limited manual baseline only after separate consent',async()=>{render(view());await period();fireEvent.click(screen.getByRole('button',{name:'Use limited manual context without statements'}));const proposal=await preview();expect(within(proposal).getByText(/Spending observations are unknown/)).toBeTruthy();expect((screen.getByRole('option',{name:'Complete — all coverage checks passed'}) as HTMLOptionElement).disabled).toBe(true);expect((screen.getByRole('button',{name:'Approve baseline'}) as HTMLButtonElement).disabled).toBe(true);consent();fireEvent.click(screen.getByRole('button',{name:'Approve baseline'}));await waitFor(()=>expect(api.approveFinancialBaseline).toHaveBeenCalledTimes(1));expect(api.approveFinancialBaseline).toHaveBeenCalledWith('approve',expect.objectContaining({coverage_status:'manual',base_version_id:null,base_lock_version:0,request:expect.objectContaining({revision_ids:[],tracked_account_ids:[],category_eligibility:[],cash_coverage:'unknown',household_scope_attested:false})}),expect.any(String))})
 it('leaves categories unknown by default and submits only explicit source/account/category choices',async()=>{render(view());await period();fireEvent.click(screen.getByText('Choose reviewed statement sources (0 selected)'));fireEvent.click(screen.getByRole('checkbox',{name:/Fictional-checking.pdf/}));fireEvent.click(screen.getByRole('checkbox',{name:'Fictional checking'}));fireEvent.click(screen.getByRole('checkbox',{name:/I checked which household accounts/}));fireEvent.change(screen.getByLabelText('Cash coverage'),{target:{value:'not_used'}});fireEvent.click(screen.getByText('2. Review category consideration and recurrence'));expect((screen.getByLabelText('Consider Groceries for spending review') as HTMLSelectElement).value).toBe('');fireEvent.change(screen.getByLabelText('Consider Groceries for spending review'),{target:{value:'yes'}});fireEvent.change(screen.getByLabelText('Recurrence for Groceries'),{target:{value:'seasonal'}});fireEvent.change(screen.getByLabelText('Explanation for Groceries'),{target:{value:'School supplies season varies.'}});await preview();expect(api.previewFinancialBaseline).toHaveBeenCalledWith(expect.objectContaining({revision_ids:[88],tracked_account_ids:[2],household_scope_attested:true,cash_coverage:'not_used',category_eligibility:[{budget_category_id:10,eligible:true,recurrence:'seasonal',reason:'School supplies season varies.'}]}),expect.any(AbortSignal))})
 it('keeps the approved snapshot visible and disables a stale proposal after edits or refresh',async()=>{vi.mocked(api.fetchFinancialBaseline).mockResolvedValue(baselineCurrent(baselineVersion()));render(view());await screen.findByText('Approved baseline · version 1');await preview();consent();expect((screen.getByRole('button',{name:'Approve baseline revision'}) as HTMLButtonElement).disabled).toBe(false);fireEvent.change(screen.getByLabelText('Period ends'),{target:{value:'2026-09-29'}});expect(screen.getByText(/preview is out of date/)).toBeTruthy();expect((screen.getByRole('button',{name:'Approve baseline revision'}) as HTMLButtonElement).disabled).toBe(true);expect(screen.getByText('Approved baseline · version 1')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Refresh current baseline and choices'}));await waitFor(()=>expect(api.fetchFinancialBaseline).toHaveBeenCalledTimes(2));expect((screen.getByLabelText('Period ends') as HTMLInputElement).value).toBe('2026-09-29');expect(screen.queryByRole('region',{name:'Proposed baseline preview'})).toBeNull()})
 it('treats a stale approval conflict as requiring a fresh preview while preserving choices',async()=>{vi.mocked(api.approveFinancialBaseline).mockRejectedValueOnce(new api.ApiRequestError('Source changed; preview again.',{status:409}));render(view());await period();await preview();consent();fireEvent.click(screen.getByRole('button',{name:'Approve baseline'}));await screen.findByText('Source changed; preview again.');expect(screen.getByText(/preview is out of date/)).toBeTruthy();expect((screen.getByRole('button',{name:'Approve baseline'}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByLabelText('Baseline approval explanation') as HTMLInputElement).value).toBe('Reviewed the exact period and its limits.')})
 it('retains an uncertain request across dialog navigation and retries its exact key/body',async()=>{vi.mocked(api.approveFinancialBaseline).mockRejectedValueOnce(new Error('Lost response')).mockResolvedValueOnce({actor_scope:baselineScope,local_today:'2026-10-05',record:baselineVersion(),replayed:true});const ui=render(view());await period();await preview();consent();fireEvent.click(screen.getByRole('button',{name:'Approve baseline'}));await screen.findByRole('button',{name:'Retry the same baseline request'});ui.unmount();render(view());fireEvent.click(await screen.findByRole('button',{name:'Retry the same baseline request'}));await waitFor(()=>expect(api.approveFinancialBaseline).toHaveBeenCalledTimes(2));expect(vi.mocked(api.approveFinancialBaseline).mock.calls[1]).toEqual(vi.mocked(api.approveFinancialBaseline).mock.calls[0]);const stored=sessionStorage.getItem('baseline-request-identities-v1')??'';expect(stored).not.toContain('category_eligibility');expect(stored).not.toContain('Reviewed the exact period')})
 it('hides private financial content when access is revoked during refresh',async()=>{vi.mocked(api.fetchFinancialBaseline).mockResolvedValueOnce(baselineCurrent(baselineVersion())).mockRejectedValueOnce(new api.ApiRequestError('Access revoked',{status:403}));render(view());await screen.findByText('Approved baseline · version 1');fireEvent.click(screen.getByRole('button',{name:'Refresh current baseline and choices'}));await screen.findByText(/Private baseline access is no longer available/);expect(screen.queryByText('Approved baseline · version 1')).toBeNull();expect(screen.queryByLabelText('Period begins')).toBeNull()})
 it('rejects a mismatched actor response without exposing its approved snapshot',async()=>{vi.mocked(api.fetchFinancialBaseline).mockResolvedValue({...baselineCurrent(baselineVersion()),actor_scope:{user_id:902,household_id:78}});render(view());await screen.findByText(/private workspace changed/);expect(screen.queryByText('Approved baseline · version 1')).toBeNull();expect(screen.queryByLabelText('Period begins')).toBeNull()})
})

describe('baseline approval recovery status',()=>{
 it('keeps edits blocked for unknown and processing results, then reconciles a committed approval without another POST',async()=>{vi.mocked(api.approveFinancialBaseline).mockRejectedValueOnce(new Error('Lost response'));vi.mocked(api.fetchBaselineRequestStatus).mockResolvedValueOnce({actor_scope:baselineScope,local_today:'2026-10-05',state:'in_flight'}).mockResolvedValueOnce({actor_scope:baselineScope,local_today:'2026-10-05',state:'unknown',can_retry:true}).mockResolvedValueOnce({actor_scope:baselineScope,local_today:'2026-10-05',state:'committed',record:baselineVersion(),replayed:true});render(view());await period();await preview();consent();fireEvent.click(screen.getByRole('button',{name:'Approve baseline'}));fireEvent.click(await screen.findByRole('button',{name:'Check earlier baseline result'}));await screen.findByText(/still processing/);expect(screen.getByLabelText('Period begins').matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Check earlier baseline result'}));await screen.findByText(/No committed result found/);expect(screen.getByLabelText('Period begins').matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Check earlier baseline result'}));await waitFor(()=>expect(api.fetchFinancialBaseline).toHaveBeenCalledTimes(2));expect(api.approveFinancialBaseline).toHaveBeenCalledTimes(1)})
 it('does not restore private approval inputs after the actual actor switches',async()=>{vi.mocked(api.approveFinancialBaseline).mockRejectedValueOnce(new Error('Lost response'));const ui=render(view());await period();await preview();consent();fireEvent.click(screen.getByRole('button',{name:'Approve baseline'}));await screen.findByRole('button',{name:'Retry the same baseline request'});ui.unmount();setBaselineExpectedUser(902);bindBaselineActor({user_id:902,household_id:78});setBaselineExpectedUser(901);bindBaselineActor(baselineScope);expect(readBaselineRecovery(baselineScope)?.input).toBeUndefined();render(view());await screen.findByRole('button',{name:'Check earlier baseline result'});expect(screen.queryByRole('button',{name:'Retry the same baseline request'})).toBeNull()})
})
