import { useState } from 'react'
import { baselineLimit, baselineMoney, type BaselinePreview, type BaselineSource } from '../lib/financialBaseline'
export function BaselinePatterns({ preview, sources }: { preview: BaselinePreview; sources: BaselineSource[] }) {
  const [merchantPage, setMerchantPage] = useState(0)
  const accounts = sources.flatMap((source) => source.accounts)
  const patterns = preview.patterns
  const money = (cents: number) => preview.observed_spending_known ? baselineMoney(cents) : 'Unknown'
  const merchants = patterns.merchants.slice(merchantPage * 20, merchantPage * 20 + 20)
  return <section className="baseline-patterns" aria-label="Spending observations and limits">
    <h3>{preview.window_start_on} – {preview.window_end_on}</h3><p>{preview.represented_row_count} observations across this entire period. {preview.supported_complete_calendar_month_count} complete calendar months supported by reviewed evidence.</p>
    <dl className="baseline-totals"><div><dt>Gross observed spending</dt><dd>{money(patterns.gross_spending_cents)}</dd></div><div><dt>Allocated refunds</dt><dd>{money(patterns.allocated_refunds_cents)}</dd></div><div><dt>Net observed spending</dt><dd>{money(patterns.net_spending_cents)}</dd></div><div><dt>Current-period purchase comparison</dt><dd>{money(patterns.same_window_net_spending_cents)}</dd></div><div><dt>Participant-selected category comparison</dt><dd>{money(patterns.comparable_eligible_spending_cents)}</dd></div></dl>
    <p>Current-period comparisons exclude refunds reversing earlier-period purchases. Earlier-period refunds: {baselineMoney(patterns.prior_window_refunds_cents)}. Unallocated refunds: {baselineMoney(patterns.unallocated_refund_cents)}. None of these amounts is confirmed savings or a suggested spending cut.</p>
    {!preview.observed_spending_known && <p className="baseline-limit">Spending observations are unknown. An empty subtotal does not mean your household spent $0.</p>}
    <div className="baseline-limit"><h4>Coverage and limitations</h4>{preview.complete_eligible ? <p>This preview meets the server’s complete-coverage checks. Your separate approval is still required.</p> : <ul>{[...new Set(preview.deficiencies.map(baselineLimit))].map((limit) => <li key={limit}>{limit}</li>)}</ul>}</div>
    <details><summary>Account periods and missing ranges</summary>{preview.account_coverage.length ? preview.account_coverage.map((account) => <article key={account.tracked_account_id}><h4>{accounts.find((item) => item.tracked_account_id === account.tracked_account_id)?.label ?? 'Reviewed account'} · {account.account_basis === 'asset' ? 'Bank / wallet' : 'Credit / liability'}</h4><p>{account.complete ? 'Reviewed intervals cover this period.' : 'This account has coverage gaps.'}</p><ul>{account.approved_intervals.map((interval) => <li key={interval.join(':')}>Reviewed {interval[0]} – {interval[1]}</li>)}{account.missing_ranges.map((range) => <li key={range.start_on}>Missing {range.start_on} – {range.end_on}</li>)}</ul></article>) : <p>No statement-account coverage was declared.</p>}</details>
    <details><summary>Categories and monthly observations</summary>{patterns.categories.map((category) => <article key={category.budget_category_id ?? 'uncategorized'}><h4>{category.name}</h4><p>{category.frequency} observed purchases · {money(category.gross_cents)} gross · {money(category.refunds_cents)} allocated refunds · {money(category.net_cents)} net</p><p>Consider for spending review: {category.eligible === null ? 'Unreviewed' : category.eligible ? 'Yes' : 'No'} · Recurrence: {category.recurrence.replaceAll('_',' ')} · {category.reason ?? 'No participant explanation yet'}</p></article>)}{patterns.months.map((month) => <p key={month.month}>{month.month} · {month.frequency} purchases · {money(month.gross_cents)} gross · {money(month.refunds_cents)} refunds · {money(month.net_cents)} net</p>)}</details>
    <details><summary>Merchant observations ({patterns.merchants.length})</summary><p>Grouping normalizes names. It does not establish necessity, optional spending, business purpose or future recurrence.</p>{merchants.map((merchant, index) => <article key={`${merchant.merchant}:${index}`}><h4>{merchant.merchant || 'Description unavailable'}</h4><p>{merchant.frequency} observed purchases · {money(merchant.gross_cents)} gross · {money(merchant.refunds_cents)} refunds · {money(merchant.net_cents)} net · earlier-period reversals {baselineMoney(merchant.prior_window_refunds_cents)}</p><p>{merchant.observed_dates.join(', ')}</p></article>)}<div className="baseline-actions"><button type="button" disabled={merchantPage === 0} onClick={() => setMerchantPage((value) => value - 1)}>Previous merchants</button><span>Page {merchantPage + 1} of {Math.max(1,Math.ceil(patterns.merchants.length / 20))}</span><button type="button" disabled={(merchantPage + 1) * 20 >= patterns.merchants.length} onClick={() => setMerchantPage((value) => value + 1)}>Next merchants</button></div></details>
    <details><summary>Transfers, debt payments and cash</summary>{(['transfers','debt_payments','cash_withdrawals'] as const).map((key) => <p key={key}>{key.replaceAll('_',' ')}: {patterns[key].count} movements · {baselineMoney(patterns[key].outflow_cents)} out · {baselineMoney(patterns[key].inflow_cents)} in</p>)}<p>Cash withdrawals: {baselineMoney(preview.cash.withdrawal_cents)} · allocated to reviewed cash purchases: {baselineMoney(preview.cash.allocated_purchase_cents)} · unallocated: {baselineMoney(preview.cash.unallocated_withdrawal_cents)}.</p><p>Manual cash purchases: {baselineMoney(preview.cash.manual_cash_purchase_cents)}. Cash coverage: {preview.cash.coverage.replaceAll('_',' ')}. A cash balance is unknown. Unallocated withdrawals are not saved money.</p></details>
    <details><summary>Observation sample ({preview.sample_rows.length} of {preview.represented_row_count})</summary><p>Only the first {preview.sample_limit} rows are shown here. All totals and patterns use the entire period; this sample does not certify the other rows.</p>{preview.sample_rows.map((row) => <article key={row.key}><h4>{row.merchant ?? 'Description unavailable'}</h4><p>{row.posted_on ?? 'Unknown date'} · {row.classification.replaceAll('_',' ')} · signed movement {row.signed_amount_cents === null ? 'Unknown' : baselineMoney(row.signed_amount_cents)} · complete purchase {row.purchase_amount_cents === null ? 'Not established' : baselineMoney(row.purchase_amount_cents)} · {accounts.find((item) => item.tracked_account_id === row.tracked_account_id)?.label ?? (row.cash ? 'Cash' : 'Account unassigned')}</p></article>)}</details>
    <details><summary>What this baseline assumes</summary><ul>{preview.assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul></details>
  </section>
}
