// @vitest-environment jsdom
import { act,cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import { ApiRequestError, fetchDailyContext, fetchDailyPage, mutateDaily, fetchDailyRequestStatus } from '../api'
import { dailyContext,dailyDraft,dailyVersion } from '../test/dailyFixtures'
import { baselineScope } from '../test/baselineFixtures'
import { setDailyExpectedUser } from '../lib/dailyRecovery'
import { ChallengeToday } from './ChallengeToday'
vi.mock('../api',async(original)=>({...await original<typeof import('../api')>(),fetchDailyContext:vi.fn(),fetchDailyPage:vi.fn(),mutateDaily:vi.fn(),fetchDailyRequestStatus:vi.fn()}))
function open(){return render(<ChallengeToday scope={baselineScope} onClose={vi.fn()} onStatements={vi.fn()} onBaseline={vi.fn()}/>)}
afterEach(cleanup)
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();setDailyExpectedUser(null);setDailyExpectedUser(901);vi.mocked(fetchDailyContext).mockResolvedValue(structuredClone(dailyContext));vi.mocked(fetchDailyPage).mockImplementation(async()=>({actor_scope:baselineScope,records:[],next_cursor:null}));vi.mocked(mutateDaily).mockResolvedValue({actor_scope:baselineScope,record:dailyDraft,replayed:false})})
describe('participant daily reporting',()=>{
 it('keeps missing spending unknown and requires explicit no-spend review',async()=>{open();await screen.findByText('Spending unknown');expect(screen.queryByText('$0.00 reported spending')).toBeNull();fireEvent.change(screen.getByLabelText('Spending state'),{target:{value:'no_spend'}});expect((screen.getByRole('button',{name:'Save daily report'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/Save this exact personal spending state/}));fireEvent.click(screen.getByRole('button',{name:'Save daily report'}));await waitFor(()=>expect(mutateDaily).toHaveBeenCalledWith('check_in_save',{local_on:'2026-09-28',spending_state:'no_spend',accepted:true,expected_version_id:null,expected_head_lock_version:0,reason:''},expect.any(String)))})
 it('previews exact purchase/category choices without approving or inferring savings',async()=>{open();fireEvent.click(await screen.findByRole('button',{name:'Add a purchase'}));fireEvent.change(screen.getByLabelText('Where did you buy it?'),{target:{value:'Fictional lunch'}});fireEvent.change(screen.getByLabelText('Purchase amount (USD)'),{target:{value:'12.505'}});fireEvent.change(screen.getByLabelText('Category 1'),{target:{value:'20'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this date, merchant, exact amount/}));fireEvent.click(screen.getByRole('button',{name:'Save purchase preview'}));expect(screen.getByRole('alert').textContent).toContain('at most two decimal');expect(mutateDaily).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Purchase amount (USD)'),{target:{value:'12.50'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this date, merchant, exact amount/}));fireEvent.click(screen.getByRole('button',{name:'Save purchase preview'}));await waitFor(()=>expect(mutateDaily).toHaveBeenCalledWith('purchase_stage',expect.objectContaining({amount_cents:1250,splits:[{budget_category_id:20,amount_cents:1250}],expected_version_id:null,link_kind:'manual_new'}),expect.any(String)));expect(vi.mocked(mutateDaily).mock.calls.some(call=>call[0]==='purchase_approve')).toBe(false)})
 it('retains known money and disables no-spend when purchases exist',async()=>{vi.mocked(fetchDailyContext).mockResolvedValue({...dailyContext,day:{...dailyContext.day!,approved_purchase_count:2,reported_spend_cents:2500,spending_state:'spending'}});open();await screen.findByText('$25.00 reported spending');expect((screen.getByRole('option',{name:'I did not spend money'}) as HTMLOptionElement).disabled).toBe(true)})
 it('does not approve saved drafts until exact separate consent',async()=>{vi.mocked(fetchDailyPage).mockImplementation(async(collection)=>({actor_scope:baselineScope,records:collection==='purchase_drafts'?[dailyDraft]:[],next_cursor:null}));open();await screen.findByText('Saved purchase preview — not approved');expect((screen.getByRole('button',{name:'Approve purchase'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this saved date/}));fireEvent.click(screen.getByRole('button',{name:'Approve purchase'}));await waitFor(()=>expect(mutateDaily).toHaveBeenCalledWith('purchase_approve',{draft_id:300,accepted:true,expected_draft_lock_version:0,expected_version_id:null,expected_head_lock_version:0},expect.any(String)))})
 it('preserves an approved purchase while staging an explicit void',async()=>{vi.mocked(fetchDailyPage).mockImplementation(async(collection)=>({actor_scope:baselineScope,records:collection==='purchases'?[{id:200,current_version_id:400,lock_version:2,current_version:dailyVersion}]:[],next_cursor:null}));open();fireEvent.click(await screen.findByRole('button',{name:'Correct Fictional lunch'}));fireEvent.click(screen.getByRole('checkbox',{name:/Void this participant-entered/}));fireEvent.change(screen.getByLabelText('Correction explanation'),{target:{value:'Duplicate manual entry checked.'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this date, merchant, exact amount/}));fireEvent.click(screen.getByRole('button',{name:'Save purchase preview'}));await waitFor(()=>expect(mutateDaily).toHaveBeenCalledWith('purchase_stage',expect.objectContaining({purchase_id:200,amount_cents:0,splits:[],disposition:'void',expected_version_id:400,expected_head_lock_version:2,merchant:'Fictional lunch',purchased_on:'2026-09-28'}),expect.any(String)));expect(screen.queryByRole('button',{name:'Approve purchase void'})).toBeNull()})
 it('keeps identical request inputs and key after uncertain result and navigation',async()=>{vi.mocked(mutateDaily).mockRejectedValueOnce(new ApiRequestError('Interrupted response.',{status:503}));const mounted=open();await screen.findByText('Spending unknown');fireEvent.click(screen.getByRole('checkbox',{name:/Save this exact personal spending state/}));fireEvent.click(screen.getByRole('button',{name:'Save daily report'}));await screen.findByRole('button',{name:'Retry the same daily request'});const first=vi.mocked(mutateDaily).mock.calls[0];const metadata=sessionStorage.getItem('daily-request-identities-v1');expect(metadata).not.toContain('spending_state');expect(metadata).not.toContain('local_on');mounted.unmount();open();fireEvent.click(await screen.findByRole('button',{name:'Retry the same daily request'}));await waitFor(()=>expect(mutateDaily).toHaveBeenCalledTimes(2));expect(vi.mocked(mutateDaily).mock.calls[1]).toEqual(first)})
 it('treats unknown/in-flight journal results as unresolved instead of failure',async()=>{vi.mocked(mutateDaily).mockRejectedValue(new ApiRequestError('Interrupted response.',{status:503}));vi.mocked(fetchDailyRequestStatus).mockResolvedValue({actor_scope:baselineScope,state:'in_flight'});open();await screen.findByText('Spending unknown');fireEvent.click(screen.getByRole('checkbox',{name:/Save this exact personal spending state/}));fireEvent.click(screen.getByRole('button',{name:'Save daily report'}));fireEvent.click(await screen.findByRole('button',{name:'Check earlier daily result'}));await screen.findByText('This request is still processing. Check again.');expect((screen.getByRole('button',{name:'Add a purchase'}) as HTMLButtonElement).disabled).toBe(true)})
 it('clears private facts after a revoked refresh',async()=>{open();await screen.findByText('Spending unknown');vi.mocked(fetchDailyContext).mockRejectedValue(new ApiRequestError('Revoked.',{status:403}));fireEvent(window,new Event('focus'));await screen.findByText('Private daily access is no longer available. Close Today to continue.');expect(screen.queryByLabelText('Spending state')).toBeNull()})
 it('handles upcoming context without inventing a zero report or milestone',async()=>{vi.mocked(fetchDailyContext).mockResolvedValue({...dailyContext,day:null,calendar:{...dailyContext.calendar,local_today:'2026-06-30',phase:'upcoming',day:null}});open();await screen.findByText(/Your daily reporting opens 2026-07-01/);expect(screen.queryByText('$0.00 reported spending')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Checkpoints'}));expect((screen.getByRole('button',{name:'Review Day 30 · 2026-07-30'}) as HTMLButtonElement).disabled).toBe(true)})
})

describe('selected daily program identity',()=>{
 const cohortId=55
 const context={...dailyContext,cohort_id:cohortId}
 function selected(){return render(<ChallengeToday scope={baselineScope} cohortId={cohortId} onClose={vi.fn()} onStatements={vi.fn()} onBaseline={vi.fn()}/>)}
 beforeEach(()=>{vi.mocked(fetchDailyContext).mockResolvedValue(context);vi.mocked(fetchDailyPage).mockResolvedValue({actor_scope:baselineScope,enrollment_id:100,cohort_id:cohortId,records:[],next_cursor:null})})
 it.each([undefined,56])('rejects a first context with missing or wrong cohort %s',async(value)=>{
  vi.mocked(fetchDailyContext).mockResolvedValue({...context,cohort_id:value});selected();
  await screen.findByText('Private daily access is no longer available. Close Today to continue.');
  expect(screen.queryByLabelText('Spending state')).toBeNull();expect(fetchDailyPage).not.toHaveBeenCalled()
 })
 it('pins the enrollment across same-cohort focus refreshes',async()=>{
  selected();await screen.findByText('Spending unknown');
  vi.mocked(fetchDailyContext).mockResolvedValue({...context,enrollment_id:101});fireEvent(window,new Event('focus'));
  await screen.findByText('Private daily access is no longer available. Close Today to continue.');expect(screen.queryByLabelText('Spending state')).toBeNull()
 })
 it('rejects same-household pages from another enrollment before rendering records',async()=>{
  vi.mocked(fetchDailyPage).mockResolvedValue({actor_scope:baselineScope,enrollment_id:101,cohort_id:cohortId,records:[dailyDraft],next_cursor:null});selected();
  await screen.findByText('Private daily access is no longer available. Close Today to continue.');expect(screen.queryByText('Fictional lunch')).toBeNull()
 })
 it('discards a deferred old-program context after changing the selected cohort',async()=>{
  let resolve!:(value:typeof context)=>void
  vi.mocked(fetchDailyContext).mockReturnValueOnce(new Promise(done=>{resolve=done}));
  const view=selected();
  vi.mocked(fetchDailyContext).mockResolvedValue({...context,enrollment_id:102,cohort_id:56});vi.mocked(fetchDailyPage).mockResolvedValue({actor_scope:baselineScope,enrollment_id:102,cohort_id:56,records:[],next_cursor:null});
  view.rerender(<ChallengeToday scope={baselineScope} cohortId={56} onClose={vi.fn()} onStatements={vi.fn()} onBaseline={vi.fn()}/>);
  await screen.findByText('Spending unknown');await act(async()=>resolve(context));await waitFor(()=>expect(fetchDailyContext).toHaveBeenCalledTimes(2));
  expect(screen.queryByText('Private daily access is no longer available. Close Today to continue.')).toBeNull()
 })
})
