// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { ApiRequestError, fetchFinancialBaseline } from '../api'
import { baselineCurrent, baselineRequest, baselinePreview, baselineScope, baselineVersion } from '../test/baselineFixtures'
import { ComfortablePlanChoices, ComfortablePlanSummary } from './ComfortablePlanChoices'
import { SavingsPlanApprovalReview } from './SavingsPlanApprovalReview'
import { savingsPlanDraft } from '../test/savingsFixtures'
vi.mock('../api',async original=>({...await original<typeof import('../api')>(),fetchFinancialBaseline:vi.fn()}))
const change=vi.fn(), denied=vi.fn()
const view=(freshness=0)=><ComfortablePlanChoices scope={baselineScope} disabled={false} freshness={freshness} onChange={change} onDenied={denied}/>
function approved(){const request=baselineRequest();request.category_eligibility=[{budget_category_id:10,eligible:true,recurrence:'unknown',reason:'Participant choice'}];const version=baselineVersion(baselinePreview(request,true));version.digest='a'.repeat(64);version.preview.category_eligibility.push({budget_category_id:20,name:'Dining',active:true,eligible:false,recurrence:'one_off',reason:'Essential this month'});return baselineCurrent(version)}
async function edit(){fireEvent.click(screen.getByText('Optional comfortable spending choices'));fireEvent.click(screen.getByRole('button',{name:'Edit optional spending choices'}))}
afterEach(cleanup)
beforeEach(()=>{vi.clearAllMocks();vi.mocked(fetchFinancialBaseline).mockResolvedValue(approved())})
it('keeps choices optional and manual, validates exact cents and requires review without fetching sources',async()=>{render(view());expect(fetchFinancialBaseline).not.toHaveBeenCalled();await edit();fireEvent.click(screen.getByRole('button',{name:'Add comfortable change'}));fireEvent.change(screen.getByLabelText('Comfortable change 1'),{target:{value:'Pack lunch twice a week'}});fireEvent.change(screen.getByLabelText(/Estimated reduction for change 1/),{target:{value:'1.005'}});await waitFor(()=>expect(change.mock.calls.at(-1)?.[0].error).toContain('at most two decimal'));fireEvent.change(screen.getByLabelText(/Estimated reduction for change 1/),{target:{value:'25.50'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed these exact/}));await waitFor(()=>expect(change.mock.calls.at(-1)?.[0]).toEqual({input:{financial_baseline_version_id:null,baseline_digest:null,spending_changes:[{budget_category_id:null,description:'Pack lunch twice a week',recurrence:'unknown',planned_reduction_cents:2550}]},edited:true,reviewed:true,error:undefined}));expect(fetchFinancialBaseline).not.toHaveBeenCalled()})
it('explicitly connects partial baseline and exposes only participant eligible categories',async()=>{render(view());await edit();fireEvent.click(screen.getByText('Use an approved spending baseline (optional)'));fireEvent.click(screen.getByRole('button',{name:'Check approved baseline'}));await screen.findByText(/partial coverage/);expect(change.mock.calls.at(-1)?.[0].input.financial_baseline_version_id).toBeNull();fireEvent.click(screen.getByRole('checkbox',{name:/Include this exact approved baseline/}));fireEvent.click(screen.getByRole('button',{name:'Add comfortable change'}));expect(screen.getByRole('option',{name:'Groceries'})).toBeTruthy();expect(screen.queryByRole('option',{name:'Dining'})).toBeNull();fireEvent.change(screen.getByLabelText('Comfortable change 1'),{target:{value:'Choose less expensive groceries'}});fireEvent.change(screen.getByLabelText('Category for change 1'),{target:{value:'10'}});fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed these exact/}));await waitFor(()=>expect(change.mock.calls.at(-1)?.[0].input).toEqual({financial_baseline_version_id:501,baseline_digest:'a'.repeat(64),spending_changes:[{budget_category_id:10,description:'Choose less expensive groceries',recurrence:'unknown',planned_reduction_cents:null}]}));expect(JSON.stringify(change.mock.calls.at(-1))).not.toContain('category_name')})
it('disables stale baseline connection, resets consent on refresh and fences revoked facts',async()=>{vi.mocked(fetchFinancialBaseline).mockResolvedValue({...approved(),needs_revision:true});const mounted=render(view());await edit();fireEvent.click(screen.getByText('Use an approved spending baseline (optional)'));fireEvent.click(screen.getByRole('button',{name:'Check approved baseline'}));await screen.findByText(/needs revision and cannot/);expect((screen.getByRole('checkbox',{name:/Include this exact approved baseline/}) as HTMLInputElement).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed these exact/}));mounted.rerender(view(1));await waitFor(()=>expect((screen.getByRole('checkbox',{name:/I reviewed these exact/}) as HTMLInputElement).checked).toBe(false));vi.mocked(fetchFinancialBaseline).mockRejectedValue(new ApiRequestError('Revoked',{status:403}));fireEvent.click(screen.getByRole('button',{name:'Check approved baseline'}));await waitFor(()=>expect(denied).toHaveBeenCalledOnce());expect(screen.queryByText(/partial coverage/)).toBeNull()})
it('caps five explicit choices and does not label old missing fields as empty',async()=>{render(view());await edit();for(let i=0;i<5;i++)fireEvent.click(screen.getByRole('button',{name:'Add comfortable change'}));expect((screen.getByRole('button',{name:'Add comfortable change'}) as HTMLButtonElement).disabled).toBe(true);cleanup();render(<ComfortablePlanSummary plan={{}}/>);expect(screen.getByText(/details are unavailable/)).toBeTruthy();expect(screen.queryByText(/No spending changes were included/)).toBeNull()})
it('shows a saved plan separately and requires explicit review of optional context before approval',()=>{const approve=vi.fn();render(<SavingsPlanApprovalReview draft={{...savingsPlanDraft(),financial_baseline_version_id:null,baseline_digest:null,spending_changes:[{budget_category_id:null,description:'Pack a comfortable lunch',recurrence:'seasonal',planned_reduction_cents:2500}]}} disabled={false} onApprove={approve}/>);expect((screen.getByRole('button',{name:'Approve target plan #11'}) as HTMLButtonElement).disabled).toBe(true);expect(screen.getByText(/25.00 estimated reduction over the full 90-day/)).toBeTruthy();fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this saved target/}));fireEvent.click(screen.getByRole('button',{name:'Approve target plan #11'}));expect(approve).toHaveBeenCalledOnce()})
