import { useEffect, useRef, useState } from 'react'
import { ApiRequestError, fetchDailyPage } from '../api'
import { dailyResponseMatches } from '../lib/dailyChallenge'
import type { DailyReflection, DailyReflectionVersion, DailyScope } from '../lib/dailyChallenge'
import type { DailyMutate } from '../lib/useDailyMutation'
import { DailyReflectionErasure } from './DailyReflectionErasure'
import { DailyRecordPage } from './DailyRecordPage'
export function DailyReflectionEditor({purchaseId,scope,refresh,mutate,busy,onDenied}:{purchaseId:number;scope:DailyScope;refresh:number;mutate:DailyMutate;busy:boolean;onDenied:()=>void}) {
  const initialized=useRef(false)
  const[head,setHead]=useState<DailyReflection|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
  const[then,setThen]=useState('');const[now,setNow]=useState('');const[accepted,setAccepted]=useState(false);const[history,setHistory]=useState(false)
  useEffect(()=>{const controller=new AbortController();let live=true;fetchDailyPage<DailyReflection>('reflections',null,purchaseId,controller.signal).then(result=>{if(!dailyResponseMatches(result,scope))throw new ApiRequestError('Private workspace changed.',{status:403});if(live){const record=result.records[0]??null;setHead(record);if(!initialized.current||record?.current_version?.erased_at){setThen(record?.current_version?.feeling_then??'');setNow(record?.current_version?.feeling_now??'');initialized.current=true;}setAccepted(false);setLoading(false);setError(null)}}).catch(failure=>{if(live){setLoading(false);setError(failure instanceof Error?failure.message:'Optional feelings are unavailable.');if(failure instanceof ApiRequestError&&[401,403,404].includes(failure.status))onDenied()}});return()=>{live=false;controller.abort()}},[purchaseId,scope,refresh,onDenied])
  return <section aria-label="Optional purchase feelings"><h4>Optional feelings, separate from money</h4><p>Skip this whenever you want. Saving or erasing feelings never changes the purchase date, spending report or savings total.</p>{loading&&<p role="status">Loading your optional reflection…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&<><fieldset disabled={busy}><legend>Your reflection</legend><label>How did you feel then?<textarea maxLength={500} value={then} onChange={event=>{setThen(event.target.value);setAccepted(false)}}/></label><label>How do you feel now?<textarea maxLength={500} value={now} onChange={event=>{setNow(event.target.value);setAccepted(false)}}/></label><label className="daily-check"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>Save these optional feelings separately from financial facts.</span></label><button type="button" disabled={!accepted} onClick={()=>void mutate('reflection_save',{purchase_id:purchaseId,expected_version_id:head?.current_version_id??null,expected_head_lock_version:head?.lock_version??0,feeling_then:then.trim()||null,feeling_now:now.trim()||null})}>Save optional feelings</button>{head?.current_version?.erased_at&&<p>Previous feelings were erased. This history retains tombstone metadata.</p>}{head&&<DailyReflectionErasure key={`${head.id}:${head.current_version_id}`} reflection={head} mutate={mutate} busy={busy}/>}</fieldset>{head&&<details onToggle={event=>{if(event.currentTarget.open)setHistory(true)}}><summary>Previous reflection versions</summary>{history&&<DailyRecordPage<DailyReflectionVersion> collection="reflection_versions" parentId={head.id} scope={scope} refresh={refresh} title="Reflection history" onDenied={onDenied} render={row=><article key={row.id}><h4>Version {row.version_number}</h4><p>{row.approved_at}</p>{row.erased_at?<p>Feelings erased · {row.erased_at}</p>:<><p>Then: {row.feeling_then??'Not entered'}</p><p>Now: {row.feeling_now??'Not entered'}</p></>}</article>}/>}</details>}</> }</section>
}
