// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { fetchDailyPage } from '../api'
import { baselineScope } from '../test/baselineFixtures'
import { DailyReflectionEditor } from './DailyReflectionEditor'
import type { DailyMutate } from '../lib/useDailyMutation'
vi.mock('../api',async(original)=>({...await original<typeof import('../api')>(),fetchDailyPage:vi.fn()}))
const scope={...baselineScope,enrollment_id:100};const mutate=vi.fn<DailyMutate>();const onDenied=vi.fn()
const head={id:600,current_version_id:601,lock_version:3,savings_daily_purchase_id:200,current_version:{id:601,version_number:1,previous_version_id:null,approved_at:'2026-09-28T12:00:00Z',reason:null,savings_daily_reflection_id:600,savings_daily_purchase_id:200,feeling_then:'A fictional stressful day',feeling_now:'Calmer',erased_at:null}}
const view=(refresh=0)=><DailyReflectionEditor purchaseId={200} scope={scope} refresh={refresh} mutate={mutate} busy={false} onDenied={onDenied}/>
afterEach(cleanup)
beforeEach(()=>{vi.clearAllMocks();vi.mocked(fetchDailyPage).mockResolvedValue({actor_scope:baselineScope,records:[head],next_cursor:null});mutate.mockResolvedValue({id:602})})
it('loads an exact purchase reflection and saves feelings independently without financial fields',async()=>{render(view());await screen.findByDisplayValue('A fictional stressful day');expect(fetchDailyPage).toHaveBeenCalledWith('reflections',null,200,expect.any(AbortSignal));fireEvent.change(screen.getByLabelText('How do you feel now?'),{target:{value:'A different feeling'}});fireEvent.click(screen.getByRole('checkbox',{name:/Save these optional feelings separately/}));fireEvent.click(screen.getByRole('button',{name:'Save optional feelings'}));await waitFor(()=>expect(mutate).toHaveBeenCalledWith('reflection_save',{purchase_id:200,expected_version_id:601,expected_head_lock_version:3,feeling_then:'A fictional stressful day',feeling_now:'A different feeling'}));expect(JSON.stringify(mutate.mock.calls[0])).not.toContain('amount_cents')})
it('preserves unsaved reflection input on context refresh but requires reviewed erasure of all versions',async()=>{const mounted=render(view());await screen.findByDisplayValue('Calmer');fireEvent.change(screen.getByLabelText('How do you feel now?'),{target:{value:'Unsaved personal words'}});mounted.rerender(view(1));await waitFor(()=>expect(fetchDailyPage).toHaveBeenCalledTimes(2));expect((screen.getByLabelText('How do you feel now?') as HTMLTextAreaElement).value).toBe('Unsaved personal words');expect((screen.getByRole('button',{name:'Erase all versions of these feelings'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/Erase my feelings from every version/}));fireEvent.click(screen.getByRole('button',{name:'Erase all versions of these feelings'}));expect(mutate).toHaveBeenCalledWith('reflection_erase',{erase_accepted:true,expected_version_id:601,expected_head_lock_version:3},600)})
it('does not expose text in tombstone history',async()=>{vi.mocked(fetchDailyPage).mockResolvedValue({actor_scope:baselineScope,records:[{...head,current_version:{...head.current_version,feeling_then:null,feeling_now:null,erased_at:'2026-10-05T01:00:00Z'}}],next_cursor:null});render(view());await screen.findByText('Previous feelings were erased. This history retains tombstone metadata.');expect(screen.queryByDisplayValue('A fictional stressful day')).toBeNull()})
