// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import * as api from '../api'
import { ApiRequestError } from '../api'
import { SavingsChallengeHome } from './SavingsChallengeHome'
import { savingsFixture, savingsEntryDraft, savingsEntryVersion } from '../test/savingsFixtures'
import { homeSavingsStorage, saveHomeSavingsIdentity, type HomeSavingsIdentity } from '../lib/homeSavingsRecovery'
vi.mock('../contexts/brandContextValue',()=>({useBrand:()=>({assistantName:'Mia'})}))
vi.mock('../api',async original=>({...await original<typeof import('../api')>(),fetchSavingsChallenge:vi.fn(),fetchSavingsPage:vi.fn(),fetchHomeSavingsRequestStatus:vi.fn(),stageSavingsEntry:vi.fn(),approveSavingsEntry:vi.fn(),enrollSavingsChallenge:vi.fn(),attestSavingsZero:vi.fn(),stageSavingsPlan:vi.fn()}))
const actor={user_id:7,household_id:8}, scope={...actor,cohort_id:42}
const fixture=(enrolled=true)=>({...savingsFixture(enrolled),cohort_id:42})
function identity(action:HomeSavingsIdentity['action'],more:Partial<HomeSavingsIdentity>={}){return{scope,action,key:'original-safe-key',enrollmentId:action==='enrollment'?null:1,...more}}
function view(cohortId=42,token=0){return <SavingsChallengeHome cohortId={cohortId} participantScope={actor} evidenceRefreshToken={token} onAskMia={()=>undefined} onReviewStatements={()=>undefined}/>}
async function open(){render(view());await screen.findByText('Not yet approved');await waitFor(()=>expect(screen.getByLabelText('Amount in US dollars') .matches(':disabled')).toBe(false))}
async function fresh(){const count=vi.mocked(api.fetchSavingsChallenge).mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText(/does not prove the earlier request failed/);fireEvent.click(screen.getByLabelText(/I will re-review the same action/));fireEvent.click(screen.getByRole('button',{name:'Prepare fresh savings review'}));await waitFor(()=>expect(api.fetchSavingsChallenge).toHaveBeenCalledTimes(count+1))}
beforeEach(()=>{vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>setTimeout(()=>callback(0),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);sessionStorage.clear();vi.clearAllMocks();HTMLElement.prototype.scrollIntoView=vi.fn();vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(fixture());vi.mocked(api.fetchSavingsPage).mockResolvedValue({records:[],next_cursor:null,actor_scope:actor,enrollment_id:1,cohort_id:42});vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'unknown',can_retry:true,actor_scope:actor,cohort_id:42})})
afterEach(()=>{cleanup();sessionStorage.clear();vi.restoreAllMocks();vi.unstubAllGlobals()})
it('retains only action and scoped identity, recovers committed entry after real component remount without another POST',async()=>{
 vi.mocked(api.stageSavingsEntry).mockRejectedValue(new Error('Lost after commit'));await open();fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'25.50'}});fireEvent.click(screen.getByRole('button',{name:'Review savings record'}));await screen.findByRole('button',{name:'Retry exact savings request'});const saved=sessionStorage.getItem(homeSavingsStorage)!;expect(saved).not.toMatch(/signed_cents|effective_on|funding_source|25.50|reason|perform/);const key=Object.values(JSON.parse(saved))[0]as {key:string};cleanup();vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'committed',record:savingsEntryDraft(),replayed:true,challenge:fixture(),actor_scope:actor,cohort_id:42});render(view());await screen.findByRole('button',{name:'Check earlier savings result'});expect(screen.queryByRole('button',{name:'Retry exact savings request'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText(/earlier request was confirmed once/);expect(api.stageSavingsEntry).toHaveBeenCalledTimes(1);expect(api.fetchHomeSavingsRequestStatus).toHaveBeenCalledWith('entry_stage',key.key,expect.any(AbortSignal));expect(sessionStorage.getItem(homeSavingsStorage)).toBeNull()
})
it('cold new-entry unknown enables only same action, preserves key through 409 and discovers late original commit',async()=>{
 saveHomeSavingsIdentity(identity('entry_stage'));render(view());await screen.findByText('Not yet approved');expect(screen.getByLabelText('Amount in US dollars') .matches(':disabled')).toBe(true);await fresh();await waitFor(()=>expect(screen.getByLabelText('Amount in US dollars') .matches(':disabled')).toBe(false));expect(screen.getByRole('button',{name:'Review target plan'}) .matches(':disabled')).toBe(true);vi.mocked(api.stageSavingsEntry).mockRejectedValue(new ApiRequestError('Original payload already won',{status:409}));fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'10.00'}});fireEvent.click(screen.getByRole('button',{name:'Review savings record'}));await screen.findByText('Original payload already won');expect(api.stageSavingsEntry).toHaveBeenCalledWith(expect.objectContaining({signed_cents:1000}),'original-safe-key',expect.any(AbortSignal));expect(sessionStorage.getItem(homeSavingsStorage)).toContain('original-safe-key');expect(screen.queryByRole('button',{name:'Retry exact savings request'})).toBeNull();vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'committed',record:savingsEntryDraft(),replayed:true,challenge:fixture(),actor_scope:actor,cohort_id:42});fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText(/earlier request was confirmed once/);expect(api.stageSavingsEntry).toHaveBeenCalledTimes(1)
})
it('pre-enrollment recovery verifies program identity and a newly committed enrollment without reenrolling',async()=>{
 saveHomeSavingsIdentity(identity('enrollment'));vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(fixture(false));vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'committed',record:fixture().enrollment,replayed:true,challenge:fixture(),actor_scope:actor,cohort_id:42});render(view());await screen.findByText('Review before joining');expect(screen.getByLabelText(/read this notice/) .matches(':disabled')).toBe(true);vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(fixture());fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText('Your approved progress');await waitFor(()=>expect(document.activeElement?.textContent).toBe('Your approved progress'));expect(api.enrollSavingsChallenge).not.toHaveBeenCalled()
})
it('cold enrollment unknown requires current terms consent and uses retained key',async()=>{
 saveHomeSavingsIdentity(identity('enrollment'));vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(fixture(false));vi.mocked(api.enrollSavingsChallenge).mockResolvedValue({record:fixture().enrollment!,replayed:false,challenge:fixture()});render(view());await screen.findByText('Review before joining');await fresh();await waitFor(()=>expect(screen.getByLabelText(/read this notice/) .matches(':disabled')).toBe(false));fireEvent.click(screen.getByLabelText(/read this notice/));fireEvent.click(screen.getByLabelText(/later personal start/));fireEvent.click(screen.getByRole('button',{name:'Accept and join'}));await waitFor(()=>expect(api.enrollSavingsChallenge).toHaveBeenCalledWith(expect.objectContaining({expected_acceptance_digest:'a'.repeat(64)}),'original-safe-key',expect.any(AbortSignal)))
})
it('cold approval only unlocks original paged draft and does not allow another draft or new report',async()=>{
 saveHomeSavingsIdentity(identity('entry_approve',{draftId:31}));vi.mocked(api.fetchSavingsPage).mockImplementation(async collection=>({records:collection==='entry_drafts'?[savingsEntryDraft(),{...savingsEntryDraft(),id:32}]:[],next_cursor:null,actor_scope:actor,enrollment_id:1,cohort_id:42}));vi.mocked(api.approveSavingsEntry).mockResolvedValue({record:savingsEntryVersion(),replayed:false,challenge:fixture()});render(view());await screen.findByText('Not yet approved');await fresh();await waitFor(()=>expect(screen.getByRole('button',{name:'Approve savings record #31'}) .matches(':disabled')).toBe(false));expect(screen.getByRole('button',{name:'Approve savings record #32'}) .matches(':disabled')).toBe(true);expect(screen.getByLabelText('Amount in US dollars') .matches(':disabled')).toBe(true);expect(api.fetchSavingsPage).toHaveBeenCalledWith('entry_drafts',30,expect.any(AbortSignal));fireEvent.click(screen.getByRole('button',{name:'Approve savings record #31'}));await waitFor(()=>expect(api.approveSavingsEntry).toHaveBeenCalledWith(31,expect.objectContaining({accepted:true}),'original-safe-key',expect.any(AbortSignal)))
})
it('cold correction only opens original record, paginates directly and preserves approved total until approval',async()=>{
 saveHomeSavingsIdentity(identity('entry_stage',{entryId:41}));vi.mocked(api.fetchSavingsPage).mockImplementation(async collection=>({records:collection==='entries'?[{id:41,current_approved_version_id:51,lock_version:2,current_approved_version:savingsEntryVersion()},{id:42,current_approved_version_id:52,lock_version:0,current_approved_version:savingsEntryVersion()}]:[],next_cursor:null,actor_scope:actor,enrollment_id:1,cohort_id:42}));vi.mocked(api.stageSavingsEntry).mockResolvedValue({record:savingsEntryDraft(1000),replayed:false,challenge:fixture()});render(view());await screen.findByText('Not yet approved');await fresh();await waitFor(()=>expect(screen.getByRole('button',{name:'Correct record #41'}) .matches(':disabled')).toBe(false));expect(screen.getByRole('button',{name:'Correct record #42'}) .matches(':disabled')).toBe(true);expect(screen.getByLabelText('Amount in US dollars') .matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Correct record #41'}));fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'10.00'}});fireEvent.change(screen.getByLabelText('Reason for correction'),{target:{value:'Re-reviewed amount'}});fireEvent.click(screen.getByRole('button',{name:'Review savings record'}));await waitFor(()=>expect(api.stageSavingsEntry).toHaveBeenCalledWith(expect.objectContaining({entry_id:41,expected_entry_lock_version:2}),'original-safe-key',expect.any(AbortSignal)))
})
it('zero recovery requires fresh attestation and retains key while in flight',async()=>{
 saveHomeSavingsIdentity(identity('zero_attest'));vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValueOnce({state:'in_flight',actor_scope:actor,cohort_id:42}).mockResolvedValueOnce({state:'unknown',can_retry:true,actor_scope:actor,cohort_id:42});vi.mocked(api.attestSavingsZero).mockResolvedValue({record:{id:2,cutoff_on:'2026-10-04',approval_sequence:1,previous_attestation_id:null,approved_at:''},challenge:fixture(),replayed:false});render(view());await screen.findByText('Not yet approved');fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText(/still processing/);expect(screen.queryByRole('button',{name:'Prepare fresh savings review'})).toBeNull();await fresh();await waitFor(()=>expect(screen.getByLabelText(/I know I have no eligible/) .matches(':disabled')).toBe(false));expect(screen.getByRole('button',{name:'Confirm known zero'}) .matches(':disabled')).toBe(true);fireEvent.click(screen.getByLabelText(/I know I have no eligible/));fireEvent.click(screen.getByRole('button',{name:'Confirm known zero'}));await waitFor(()=>expect(api.attestSavingsZero).toHaveBeenCalledWith(expect.objectContaining({known_zero:true}),'original-safe-key',expect.any(AbortSignal)))
})
it('wrong-cohort status clears private contents without clearing original identity or submitting',async()=>{
 saveHomeSavingsIdentity(identity('entry_stage'));vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'unknown',can_retry:true,actor_scope:actor,cohort_id:99});render(view());await screen.findByText('Not yet approved');fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText('Private plan access is no longer available.');expect(screen.queryByLabelText('Amount in US dollars')).toBeNull();expect(sessionStorage.getItem(homeSavingsStorage)).toContain('original-safe-key');expect(api.stageSavingsEntry).not.toHaveBeenCalled()
})
it('actor/program switch aborts late status and retains isolated identities',async()=>{
 saveHomeSavingsIdentity(identity('entry_stage'));let resolve!:(value:apiReturn)=>void;type apiReturn=Awaited<ReturnType<typeof api.fetchHomeSavingsRequestStatus>>;vi.mocked(api.fetchHomeSavingsRequestStatus).mockImplementation(()=>new Promise(done=>{resolve=done}));const ui=render(view());await screen.findByText('Not yet approved');fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));const signal=vi.mocked(api.fetchHomeSavingsRequestStatus).mock.calls[0][2];vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(Object.assign(fixture(false),{cohort_id:99}));ui.rerender(view(99));await screen.findByText('Review before joining');await act(async()=>resolve({state:'committed',record:savingsEntryDraft(),replayed:true,challenge:fixture(),actor_scope:actor,cohort_id:42}));expect(signal?.aborted).toBe(true);expect(screen.queryByText('Not yet approved')).toBeNull();expect(sessionStorage.getItem(homeSavingsStorage)).toContain('original-safe-key')
})
it('evidence refresh updates approved projection/history while keeping unsaved target and entry inputs',async()=>{
 const ui=render(view());await screen.findByText('Not yet approved');fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'17.25'}});fireEvent.change(screen.getByLabelText('Target in US dollars'),{target:{value:'333.00'}});const next=fixture();next.projection={...next.projection!,reporting_known:true,reported_cents:2550,evidence_supported_cents:1000};vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(next);ui.rerender(view(42,1));await screen.findByText(/Evidence-supported subset: \$10.00/);expect((screen.getByLabelText('Amount in US dollars')as HTMLInputElement).value).toBe('17.25');expect((screen.getByLabelText('Target in US dollars')as HTMLInputElement).value).toBe('333.00')
})
it('storage unavailable blocks mutation before the server receives it',async()=>{await open();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('Storage blocked')});fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'1.00'}});fireEvent.click(screen.getByRole('button',{name:'Review savings record'}));await screen.findByText(/No change was submitted/);expect(api.stageSavingsEntry).not.toHaveBeenCalled()})
it('existing pending plan identity blocks Home writes even in plan fresh-review mode',async()=>{
 const planScope={...actor,enrollment_id:1};const plan=await import('../lib/comfortablePlanRecovery');plan.bindPlanScope(planScope);plan.savePlanRequest({scope:planScope,action:'plan_stage',key:'pending-plan-key',working:false,awaitingFreshReview:true});render(view());await screen.findByText('Not yet approved');expect(screen.getByLabelText('Amount in US dollars').matches(':disabled')).toBe(true);fireEvent.change(screen.getByLabelText('Amount in US dollars'),{target:{value:'10.00'}});fireEvent.submit(screen.getByLabelText('Amount in US dollars').closest('form')!);expect(api.stageSavingsEntry).not.toHaveBeenCalled();plan.clearPlanRequest('pending-plan-key');plan.bindPlanScope(null)
})
it('denied recovery aborts an overlapping Home read and ignores its late private response',async()=>{
 saveHomeSavingsIdentity(identity('entry_stage'));let resolve!:(value:ReturnType<typeof fixture>)=>void;vi.mocked(api.fetchSavingsChallenge).mockImplementation(()=>new Promise(done=>{resolve=done}));vi.mocked(api.fetchHomeSavingsRequestStatus).mockResolvedValue({state:'unknown',can_retry:true,actor_scope:actor,cohort_id:99});render(view());await screen.findByRole('button',{name:'Check earlier savings result'});await waitFor(()=>expect(api.fetchSavingsChallenge).toHaveBeenCalledTimes(1));const signal=vi.mocked(api.fetchSavingsChallenge).mock.calls[0][0];fireEvent.click(screen.getByRole('button',{name:'Check earlier savings result'}));await screen.findByText('Private plan access is no longer available.');await act(async()=>resolve(fixture()));expect(signal?.aborted).toBe(true);expect(screen.queryByRole('article',{name:'Approved savings progress'})).toBeNull();expect(sessionStorage.getItem(homeSavingsStorage)).toContain('original-safe-key')
})

it.each(['actor', 'enrollment', 'cohort', 'missing'] as const)('rejects %s mismatched savings history before showing records or allowing another change', async (kind) => {
 const bad = {records:[{id:41,lock_version:2,current_approved_version_id:99,current_approved_version:savingsEntryVersion(43210)}],next_cursor:null,actor_scope:actor,enrollment_id:1,cohort_id:42};
 if(kind==='actor')bad.actor_scope={user_id:99,household_id:8};
 if(kind==='enrollment')bad.enrollment_id=9;
 if(kind==='cohort')bad.cohort_id=99;
 if(kind==='missing')delete (bad as {actor_scope?:typeof actor}).actor_scope;
 vi.mocked(api.fetchSavingsPage).mockResolvedValue(bad);render(view());
 await screen.findByText('Private plan access is no longer available.');
 expect(screen.queryByRole('article',{name:'Approved savings progress'})).toBeNull();
 expect(screen.queryByLabelText('Amount in US dollars')).toBeNull();
 expect(api.stageSavingsEntry).not.toHaveBeenCalled();
})

it('blocks stale enrollment acceptance until a scoped refresh and new explicit consent', async () => {
 vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(fixture(false))
 vi.mocked(api.enrollSavingsChallenge).mockRejectedValueOnce(new ApiRequestError('Participation offer changed; refresh to review it.', {status:409})).mockResolvedValueOnce({record:fixture().enrollment!,challenge:fixture(),replayed:false})
 render(view());await screen.findByText('Review before joining')
 const join=screen.getByRole('button',{name:'Accept and join'})
 fireEvent.click(screen.getByLabelText(/read this notice/));fireEvent.click(screen.getByLabelText(/later personal start/));fireEvent.click(join)
 await screen.findByText('Participation offer changed; refresh to review it.')
 expect(join.matches(':disabled')).toBe(true)
 expect((screen.getByLabelText(/read this notice/) as HTMLInputElement).checked).toBe(false)
 expect((screen.getByLabelText(/later personal start/) as HTMLInputElement).checked).toBe(false)
 const refreshed=fixture(false);refreshed.offer!.acceptance_digest='b'.repeat(64)
 vi.mocked(api.fetchSavingsChallenge).mockResolvedValue(refreshed)
 fireEvent.click(screen.getByRole('button',{name:'Refresh challenge'}))
 await waitFor(()=>expect(api.fetchSavingsChallenge).toHaveBeenCalledTimes(2))
 expect(join.matches(':disabled')).toBe(true)
 fireEvent.click(screen.getByLabelText(/read this notice/));fireEvent.click(screen.getByLabelText(/later personal start/));fireEvent.click(join)
 await screen.findByText('Your approved progress')
 expect(vi.mocked(api.enrollSavingsChallenge).mock.calls[1][0].expected_acceptance_digest).toBe('b'.repeat(64))
 expect(sessionStorage.getItem(homeSavingsStorage)).toBeNull()
})
