import { useState, type FormEvent } from 'react'
import { checkedDebtTerms, debtDate, debtDecimal, debtNullableDecimal, type DebtCandidate, type DebtCard, type DebtInput, type DebtMapping, type HouseholdDebtCandidate, type HouseholdDebtMapping, type DebtTerms } from '../lib/optionalDebt'
type RateForm = { label: string; balance: string; apr: string; expires: string; after: string }
const blankRate = (): RateForm => ({ label: '', balance: '', apr: '', expires: '', after: '' })
type Props = { localToday: string; card?: DebtCard; candidates: DebtCandidate[]; householdCandidates: HouseholdDebtCandidate[]; useHousehold?: boolean; busy: boolean; onReview: (input: DebtInput) => void; mapping?: DebtMapping | null }
export function OptionalDebtTerms({ localToday, card, candidates, householdCandidates, useHousehold = false, busy, onReview, mapping = null }: Props) {
  const householdInitial = useHousehold ? householdCandidates.find(row => row.household_debt_id === card?.household_debt_id) : undefined
  const previous = card?.current_version?.terms
  const initial = householdInitial ? { ...previous, label: householdInitial.label, as_of_on: localToday, ...householdInitial.proposed_terms, due_on: null, promotional_apr_bps: null, promotional_expires_on: null, post_promo_apr_bps: null, rate_segments: [] } : previous
  const [label, setLabel] = useState(initial?.label ?? ''), [asOf, setAsOf] = useState(initial?.as_of_on ?? localToday), [balance, setBalance] = useState(debtDecimal(initial?.balance_cents ?? null)), [minimum, setMinimum] = useState(debtDecimal(initial?.minimum_payment_cents ?? null)), [apr, setApr] = useState(debtDecimal(initial?.apr_bps ?? null))
  const [due, setDue] = useState(initial?.due_on ?? ''), [promo, setPromo] = useState(debtDecimal(initial?.promotional_apr_bps ?? null)), [expires, setExpires] = useState(initial?.promotional_expires_on ?? ''), [after, setAfter] = useState(debtDecimal(initial?.post_promo_apr_bps ?? null)), [status, setStatus] = useState<DebtTerms['status']>(initial?.status ?? 'active'), [reason, setReason] = useState('')
  const [rates, setRates] = useState<RateForm[]>(initial?.rate_segments.map(row => ({ label: row.label, balance: debtDecimal(row.balance_cents), apr: debtDecimal(row.apr_bps), expires: row.promotional_expires_on ?? '', after: debtDecimal(row.post_promo_apr_bps) })) ?? [])
  const [route, setRoute] = useState<'manual' | 'source' | 'household' | ''>(householdInitial ? 'household' : ''), [selected, setSelected] = useState<DebtMapping | null>(mapping), [error, setError] = useState<string | null>(null)
  const [householdSelected, setHouseholdSelected] = useState<HouseholdDebtMapping | null>(householdInitial ? { household_debt_id: householdInitial.household_debt_id, fingerprint: householdInitial.fingerprint } : card?.current_version?.household_debt_id && card.current_version.household_debt_fingerprint ? { household_debt_id: card.current_version.household_debt_id, fingerprint: card.current_version.household_debt_fingerprint } : null)
  function householdChoice(id: string) {
    const candidate = householdCandidates.find(row => String(row.household_debt_id) === id)
    if (!candidate) { setHouseholdSelected(null); return }
    setHouseholdSelected({ household_debt_id: candidate.household_debt_id, fingerprint: candidate.fingerprint }); setLabel(candidate.label); setBalance(debtDecimal(candidate.proposed_terms.balance_cents)); setMinimum(debtDecimal(candidate.proposed_terms.minimum_payment_cents)); setApr(debtDecimal(candidate.proposed_terms.apr_bps)); setAsOf(localToday); setDue(''); setPromo(''); setExpires(''); setAfter(''); setRates([]); setStatus('active')
  }
  function sourceChoice(id: string) {
    const candidate = candidates.find(row => String(row.source_account_identity_version_id) === id)
    if (!candidate) { setSelected(null); return }
    setSelected({ source_tracked_account_id: candidate.source_tracked_account_id, source_account_identity_version_id: candidate.source_account_identity_version_id, source_revision_approval_id: candidate.source_revision_approval_id, fingerprint: candidate.fingerprint })
    setAsOf(candidate.statement_as_of_on); setBalance(debtDecimal(candidate.proposed_terms.balance_cents)); setMinimum(''); setApr(''); setPromo(''); setExpires(''); setAfter(''); setRates([])
    if (!label) setLabel(candidate.label)
  }
  function review(event: FormEvent) {
    event.preventDefault(); setError(null)
    try {
      if (!route) throw new Error('Choose manual terms or an explicitly reviewed statement account.')
      if (route === 'household' && !householdSelected) throw new Error('Select the saved household card you intend to link.')
      if (householdSelected && householdCandidates.find(row => row.household_debt_id === householdSelected?.household_debt_id)?.linked_card_id && householdCandidates.find(row => row.household_debt_id === householdSelected?.household_debt_id)?.linked_card_id !== card?.id) throw new Error('This saved household card is already linked. Review its existing optional card.')
      if (route === 'source' && !selected) throw new Error('Select an exact approved liability account.')
      const date = debtDate(asOf)
      if (date > localToday || previous && date < previous.as_of_on) throw new Error('Use today or an earlier date, no earlier than the current approved terms.')
      if (route === 'source' && !candidates.some(row => row.source_account_identity_version_id === selected?.source_account_identity_version_id && row.fingerprint === selected.fingerprint && row.statement_as_of_on === date)) throw new Error('Select the current statement mapping and its exact end date.')
      if (card?.current_version_id && !reason.trim()) throw new Error('Explain this correction before reviewing it.')
      const terms = checkedDebtTerms({ label, as_of_on: date, balance_cents: debtNullableDecimal(balance), minimum_payment_cents: debtNullableDecimal(minimum), apr_bps: debtNullableDecimal(apr, true), due_on: due ? debtDate(due) : null, promotional_apr_bps: debtNullableDecimal(promo, true), promotional_expires_on: expires ? debtDate(expires) : null, post_promo_apr_bps: debtNullableDecimal(after, true), rate_segments: rates.map(row => ({ label: row.label, balance_cents: debtNullableDecimal(row.balance), apr_bps: debtNullableDecimal(row.apr, true), promotional_expires_on: row.expires ? debtDate(row.expires) : null, post_promo_apr_bps: debtNullableDecimal(row.after, true) })), status })
      onReview({ terms, ...(card ? { card_id: card.id } : {}), expected_version_id: card?.current_version_id ?? null, expected_head_lock_version: card?.lock_version ?? 0, source_mapping: route === 'source' ? selected : null, household_debt_mapping: householdSelected, reason })
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Review the terms before continuing.') }
  }
  const amountField = (name: string, value: string, set: (value: string) => void) => <label>{name}<input inputMode="decimal" value={value} onChange={event => set(event.target.value)} autoComplete="off"/></label>
  return <form onSubmit={review} aria-label="Optional card terms"><fieldset disabled={busy}><legend>{card?.current_version ? 'Correct approved card terms' : 'Review an optional card'}</legend><p>Blank money or APR means unknown. Enter 0 only when you reviewed a true zero. This does not change your savings.</p>
    <label>How will you review these terms?<select value={route} onChange={event => { setRoute(event.target.value as typeof route); if (event.target.value !== 'source') setSelected(null) }}><option value="">Choose a route</option><option value="manual">Enter manual terms — no statement required</option><option value="household">Review a saved household card — link without synchronization</option><option value="source">Explicitly map an approved statement account</option></select></label>
    {!householdSelected && route && card?.household_debt_id && <p className="debt-warning">This route removes the current household card link after approval. Earlier links remain in history.</p>}
    {route && route !== 'household' && <><label>Link to a saved household card (optional)<select value={householdSelected?.household_debt_id ?? ''} onChange={event => { const candidate = householdCandidates.find(row => String(row.household_debt_id) === event.target.value); setHouseholdSelected(candidate ? { household_debt_id: candidate.household_debt_id, fingerprint: candidate.fingerprint } : null) }}><option value="">No household card link</option>{householdCandidates.map(row => <option key={row.household_debt_id} value={row.household_debt_id} disabled={row.linked_card_id !== null && row.linked_card_id !== card?.id}>{row.label}{row.linked_card_id !== null && row.linked_card_id !== card?.id ? ' — already linked' : ''}</option>)}</select></label><p>A link identifies the same card. It does not copy values or synchronize either view.</p>{householdSelected && householdCandidates.some(row => row.household_debt_id === householdSelected.household_debt_id && row.fingerprint !== householdSelected.fingerprint) && <><p className="debt-warning">Saved household values changed. Review the current link snapshot before preparing this correction.</p>{householdCandidates.filter(row => row.household_debt_id === householdSelected.household_debt_id).map(row => <p key={row.household_debt_id}>Current saved values: balance {debtDecimal(row.proposed_terms.balance_cents) || 'Unknown'} · minimum {debtDecimal(row.proposed_terms.minimum_payment_cents) || 'Unknown'} · APR {debtDecimal(row.proposed_terms.apr_bps) || 'Unknown'}. Your optional terms stay as entered.</p>)}<button type="button" className="debt-secondary" onClick={() => { const candidate = householdCandidates.find(row => row.household_debt_id === householdSelected.household_debt_id); if (candidate) setHouseholdSelected({ household_debt_id: candidate.household_debt_id, fingerprint: candidate.fingerprint }) }}>Use current household link snapshot without copying terms</button></>}</>}
    {route === 'household' && <><label>Saved household credit card<select value={householdSelected?.household_debt_id ?? ''} onChange={event => householdChoice(event.target.value)}><option value="">Choose a saved card</option>{householdCandidates.map(row => <option key={row.household_debt_id} value={row.household_debt_id} disabled={row.linked_card_id !== null && row.linked_card_id !== card?.id}>{row.label}{row.linked_card_id !== null && row.linked_card_id !== card?.id ? ' — already linked' : ''}</option>)}</select></label><p>Review every proposed value and the terms date below. Blank means unknown; 0 means a known zero. Approval links this identity and retains a snapshot, without changing household debt.</p></>}
    {route !== 'source' && route && card?.source_tracked_account_id && <p className="debt-warning">Approving this route removes the current statement mapping. Earlier source-linked versions remain in history.</p>}
    {route === 'source' && <><label>Exact approved liability account<select value={selected?.source_account_identity_version_id ?? ''} onChange={event => sourceChoice(event.target.value)}><option value="">Choose a reviewed account</option>{candidates.map(row => <option key={row.source_account_identity_version_id} value={row.source_account_identity_version_id}>{row.label} · {row.statement_as_of_on}</option>)}</select></label><p>Only the reviewed closing balance and date are proposed. APR, minimums and promotional terms remain unknown until you verify them. Selecting another account resets those terms.</p>{selected && candidates.find(row => row.source_account_identity_version_id === selected.source_account_identity_version_id)?.qualifications.map(text => <p key={text}>{text}</p>)}</>}
    <div className="debt-fields"><label>Card label<input value={label} maxLength={120} required onChange={event => setLabel(event.target.value)} autoComplete="off"/></label><label>Terms as of<input type="date" value={asOf} max={localToday} min={previous?.as_of_on} required readOnly={route === 'source'} onChange={event => setAsOf(event.target.value)}/></label>{amountField('Balance in US dollars', balance, setBalance)}{amountField('Required minimum in US dollars', minimum, setMinimum)}{amountField('APR in percent', apr, setApr)}<label>Due date (optional)<input type="date" value={due} onChange={event => setDue(event.target.value)}/></label></div>
    <details><summary>Promotional and separate-rate terms</summary><div className="debt-fields">{amountField('Promotional APR in percent', promo, setPromo)}<label>Promotional expiry<input type="date" value={expires} onChange={event => setExpires(event.target.value)}/></label>{amountField('APR after promotion in percent', after, setAfter)}</div><p>Partial promotions and separate rates are kept visible and excluded from a precise single-rate APR order.</p>{rates.map((row, index) => <fieldset key={index} className="debt-rate"><legend>Rate segment {index + 1}</legend><label>Segment label {index + 1}<input value={row.label} maxLength={120} onChange={event => setRates(items => items.map((item, i) => i === index ? { ...item, label: event.target.value } : item))}/></label>{(['balance', 'apr', 'after', 'expires'] as const).map(key => <label key={key}>{({ balance: 'Segment balance in US dollars', apr: 'Segment APR in percent', after: 'Segment APR after promotion', expires: 'Segment promotional expiry' })[key]} {index + 1}<input type={key === 'expires' ? 'date' : 'text'} inputMode={key === 'expires' ? undefined : 'decimal'} value={row[key]} onChange={event => setRates(items => items.map((item, i) => i === index ? { ...item, [key]: event.target.value } : item))}/></label>)}<button type="button" className="debt-secondary" onClick={() => setRates(items => items.filter((_, i) => i !== index))}>Remove rate segment {index + 1}</button></fieldset>)}<button type="button" className="debt-secondary" disabled={rates.length >= 8} onClick={() => setRates(items => [...items, blankRate()])}>Add separate rate segment</button></details>
    <label>Card status<select value={status} onChange={event => setStatus(event.target.value as DebtTerms['status'])}><option value="active">Active</option><option value="paid_off">Paid off — reviewed balance must be zero</option><option value="archived">Archived — exclude from comparisons</option></select></label><label>Reason for this review{card?.current_version_id ? ' (required for correction)' : ' (optional)'}<textarea value={reason} maxLength={500} onChange={event => setReason(event.target.value)}/></label>{error && <p role="alert">{error}</p>}<button type="submit">Review pending proposal</button>
  </fieldset></form>
}
