// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {ParticipantProgramPicker} from './ParticipantProgramPicker'
import {fetchParticipantPrograms,type ParticipantPrograms,type ParticipantProgram} from '../participantProgramsApi'
vi.mock('../participantProgramsApi',()=>({fetchParticipantPrograms:vi.fn()}))
const program=(id:number,name=`Fictional program ${id}`):ParticipantProgram=>({id,name,status:'active'})
const page=(programs=[program(1),program(2)]):ParticipantPrograms=>({actor_id:7,current_cohort_id:2,current_program:program(2),selection_unavailable:false,programs,next_cursor:null})
const choose=vi.fn()
function view(actorId=7,currentCohortId?:number){return <ParticipantProgramPicker actorId={actorId} currentCohortId={currentCohortId} onChoose={choose}/>}
beforeEach(()=>{vi.clearAllMocks();vi.mocked(fetchParticipantPrograms).mockResolvedValue(page())})
afterEach(()=>{cleanup();vi.restoreAllMocks()})
it('shows server-current instead of first option and calls selection only on deliberate native change',async()=>{render(view());const select=await screen.findByLabelText('Switch participant program');expect((select as HTMLSelectElement).value).toBe('2');expect(choose).not.toHaveBeenCalled();fireEvent.change(select,{target:{value:'1'}});expect(choose).toHaveBeenCalledWith(1);expect(screen.getByText(/does not join a program/)).toBeTruthy()})
it('one available alternative stays explicit when current is unavailable',async()=>{vi.mocked(fetchParticipantPrograms).mockResolvedValue({...page([program(1)]),current_cohort_id:null,current_program:null,selection_unavailable:true});render(view(7,999));await screen.findByText(/selected program is unavailable/);expect(screen.queryByRole('combobox')).toBeNull();expect(choose).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Use Fictional program 1'}));expect(choose).toHaveBeenCalledWith(1)})
it('empty metadata names no finances and a single current program does not show an unnecessary selector',async()=>{vi.mocked(fetchParticipantPrograms).mockResolvedValueOnce({...page([]),current_cohort_id:null,current_program:null});const ui=render(view());await screen.findByText('No participant programs are available in this workspace.');expect(choose).not.toHaveBeenCalled();vi.mocked(fetchParticipantPrograms).mockResolvedValue({...page([program(2)]),current_program:program(2)});ui.rerender(view(7,2));await screen.findByText('Fictional program 2');expect(screen.queryByRole('combobox')).toBeNull();expect(screen.queryByRole('button',{name:/^Use /})).toBeNull()})
it('paged choices remain accessible and current outside page1 is separately displayed',async()=>{const first={...page(Array.from({length:50},(_,index)=>program(index+1))),current_cohort_id:103,current_program:program(103),next_cursor:50};vi.mocked(fetchParticipantPrograms).mockResolvedValueOnce(first).mockResolvedValueOnce({...first,programs:Array.from({length:50},(_,index)=>program(index+51)),next_cursor:100}).mockResolvedValueOnce({...first,programs:[program(101),program(102),program(103)],next_cursor:null});render(view());const select=await screen.findByLabelText('Switch participant program');expect((select as HTMLSelectElement).value).toBe('103');fireEvent.click(screen.getByRole('button',{name:'Load more programs'}));await waitFor(()=>expect(screen.getAllByRole('option')).toHaveLength(102));fireEvent.click(screen.getByRole('button',{name:'Load more programs'}));await waitFor(()=>expect(screen.getAllByRole('option')).toHaveLength(104));expect(fetchParticipantPrograms).toHaveBeenLastCalledWith(100,expect.any(AbortSignal));expect(screen.queryByRole('button',{name:'Load more programs'})).toBeNull();expect(choose).not.toHaveBeenCalled()})
it('actor change aborts old read and ignores late old names',async()=>{let resolve!:(value:ParticipantPrograms)=>void;vi.mocked(fetchParticipantPrograms).mockImplementationOnce(()=>new Promise(done=>{resolve=done})).mockResolvedValueOnce({...page([program(3,'New actor program')]),actor_id:8,current_cohort_id:3,current_program:program(3,'New actor program')});const ui=render(view());await waitFor(()=>expect(fetchParticipantPrograms).toHaveBeenCalledTimes(1));const signal=vi.mocked(fetchParticipantPrograms).mock.calls[0][1];ui.rerender(view(8));await screen.findByText('New actor program');await act(async()=>resolve(page([program(1,'Old actor private program')])));expect(signal?.aborted).toBe(true);expect(screen.queryByText('Old actor private program')).toBeNull();expect(choose).not.toHaveBeenCalled()})
it('wrong actor metadata and failed reads clear choices, allow retry, and never choose automatically',async()=>{vi.mocked(fetchParticipantPrograms).mockResolvedValueOnce({...page(),actor_id:99}).mockRejectedValueOnce(new Error('Program link unavailable')).mockResolvedValueOnce(page());render(view());await screen.findByRole('alert');expect(screen.queryByRole('combobox')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry program choices'}));await screen.findByText(/Program link unavailable/);fireEvent.click(screen.getByRole('button',{name:'Retry program choices'}));await screen.findByLabelText('Switch participant program');expect(choose).not.toHaveBeenCalled()})
it('archived own current program is qualified rather than silently granting access',async()=>{const old={...program(1),status:'archived' as const};vi.mocked(fetchParticipantPrograms).mockResolvedValue({...page([old]),current_cohort_id:1,current_program:old});render(view());await screen.findByText(/tools may be unavailable/);expect(choose).not.toHaveBeenCalled()})
it('program changes during page continuation require refresh instead of switching current implicitly',async()=>{vi.mocked(fetchParticipantPrograms).mockResolvedValueOnce({...page(),next_cursor:2}).mockResolvedValueOnce({...page([program(3)]),current_cohort_id:3,current_program:program(3)});render(view());fireEvent.click(await screen.findByRole('button',{name:'Load more programs'}));await screen.findByText(/current program changed/);expect(screen.queryByRole('combobox')).toBeNull();expect(choose).not.toHaveBeenCalled()})
