import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react'
import {ApiRequestError} from '../api'
import {fetchSavingsEvidence,fetchSavingsEvidenceCandidates} from '../evidenceApi'
import type {BaselineScope} from '../lib/financialBaseline'
import {sameBaselineScope} from '../lib/financialBaseline'
import {savingsDollars,savingsFundingOptions,savingsInputCents} from '../lib/savingsChallenge'
import {evidenceProof,evidenceScopeMatches,validateEvidenceSelections,type EvidenceAction,type EvidenceCandidate,type EvidenceMovementLeg,type EvidenceCandidates,type EvidenceInput,type EvidencePage} from '../lib/savingsEvidence'
import {useEvidenceMutation} from '../lib/useEvidenceMutation'
import {usePilotDialog} from '../lib/usePilotDialog'
import './SavingsEvidenceDialog.css'
type Selection={candidate:EvidenceCandidate;amount:string}
function MovementLegs({legs}:{legs:EvidenceMovementLeg[]|undefined}){return legs?.length?<div className="evidence-legs" aria-label="Reviewed movement legs">{legs.map((leg,index)=><p key={index}>{leg.account_label} · {leg.posted_on} · {savingsDollars(leg.signed_amount_cents)} · {leg.merchant} · {leg.filename ?? 'Original statement removed'}{!leg.source_available?' (source removed; approved facts retained)':''}</p>)}</div>:null}
type Proposal={action:EvidenceAction;input:EvidenceInput;selections:Selection[];total:number}
const message=(failure:unknown)=>failure instanceof Error?failure.message:'Evidence review is unavailable. Try again.'
type DialogProps={actorScope:BaselineScope;entryVersionId:number;onClose:()=>void;onChanged:()=>void}
export function SavingsEvidenceDialog(props:DialogProps){return <EvidenceDialogBody key={`${props.actorScope.user_id}:${props.actorScope.household_id}:${props.entryVersionId}`} {...props}/>}
function EvidenceDialogBody({actorScope,entryVersionId,onClose,onChanged}:DialogProps){
 const dialog=usePilotDialog(onClose);const heading=useRef<HTMLHeadingElement>(null);const contribution=useRef<HTMLElement>(null)
 const expected=useMemo(()=>({user_id:actorScope.user_id,household_id:actorScope.household_id}),[actorScope.user_id,actorScope.household_id])
 const[page,setPage]=useState<EvidencePage|null>(null);const[candidates,setCandidates]=useState<EvidenceCandidates|null>(null);const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const[denied,setDenied]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null)
 const[historyOpen,setHistoryOpen]=useState(false)
 const[historyCursor,setHistoryCursor]=useState<number|null>(null);const[historyPages,setHistoryPages]=useState<Array<number|null>>([]);const[cursor,setCursor]=useState<number|null>(null);const[pages,setPages]=useState<Array<number|null>>([]);const[attempt,setAttempt]=useState(0)
 const[selected,setSelected]=useState<Selection[]>([]);const[reason,setReason]=useState('');const[mode,setMode]=useState<EvidenceAction>('attach');const[proposal,setProposal]=useState<Proposal|null>(null);const[accepted,setAccepted]=useState(false);const[ownership,setOwnership]=useState(false);const[newMoney,setNewMoney]=useState(false);const[freshConsent,setFreshConsent]=useState(false)
 const privateReady=Boolean(page&&page.entry.id===entryVersionId&&sameBaselineScope(page.actor_scope,expected)&&!denied)
 const enrollmentId=page?.enrollment_id
 const scope=useMemo(()=>privateReady&&enrollmentId?{...expected,enrollment_id:enrollmentId,entry_version_id:entryVersionId}:undefined,[privateReady,enrollmentId,expected,entryVersionId])
 const clearReview=useCallback(()=>{setProposal(null);setAccepted(false);setOwnership(false);setNewMoney(false);setFreshConsent(false)},[])
 const refresh=useCallback(()=>{clearReview();setLoading(true);setAttempt(value=>value+1)},[clearReview])
 const revokeAccess=useCallback(()=>{setDenied(true);setPage(null);setCandidates(null);setSelected([]);setReason('');clearReview()},[clearReview])
 const done=useCallback(()=>{setSelected([]);setReason('');setMode('attach');setNotice('Evidence review saved. Your reported savings amount is unchanged.');refresh();onChanged();requestAnimationFrame(()=>{contribution.current?.focus();contribution.current?.scrollIntoView?.({block:'start'})})},[refresh,onChanged])
 const invalidate=useCallback(()=>{clearReview();setSelected([]);setFailed(true)},[clearReview])
 const mutation=useEvidenceMutation(scope,done,revokeAccess,invalidate)
 const busy=Boolean(mutation.pending&&!mutation.pending.fresh);const canAttach=privateReady&&page?.entry_is_current&&page.entry.signed_cents>0&&savingsFundingOptions.some(option=>option.value===page.entry.funding_source&&option.eligible)
 const canRevoke=privateReady&&page?.current_version?.state==='attached'
 const editable=canAttach||canRevoke
 const actionMode:EvidenceAction=canAttach?mode:'revoke'
 useEffect(()=>{let live=true;const controller=new AbortController();fetchSavingsEvidence(entryVersionId,historyCursor,controller.signal).then(async result=>{
  if(!live)return;if(!sameBaselineScope(result.actor_scope,expected)||result.entry.id!==entryVersionId)throw new ApiRequestError('The private workspace changed. Close and reopen evidence review.',{status:403})
  let choices:EvidenceCandidates|null=null
  if(result.entry_is_current&&result.entry.signed_cents>0&&savingsFundingOptions.some(option=>option.value===result.entry.funding_source&&option.eligible))choices=await fetchSavingsEvidenceCandidates(entryVersionId,cursor,controller.signal)
  if(!live)return;if(choices&&!evidenceScopeMatches(choices,{...expected,enrollment_id:result.enrollment_id,entry_version_id:entryVersionId}))throw new ApiRequestError('The private enrollment changed. Reopen evidence review.',{status:403})
  setPage(result);setCandidates(choices);setLoading(false);setFailed(false);setError(null)
 }).catch(failure=>{if(!live)return;setLoading(false);setFailed(true);setError(message(failure));if(failure instanceof ApiRequestError&&[401,403,404].includes(failure.status))revokeAccess()});return()=>{live=false;controller.abort()}},[entryVersionId,expected,historyCursor,cursor,attempt,revokeAccess])
 useEffect(()=>{const check=()=>{if(!document.hidden&&!mutation.pending)refresh()};window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);const timer=window.setInterval(check,30000);return()=>{window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);window.clearInterval(timer)}},[refresh,mutation.pending])
  function choose(candidate:EvidenceCandidate,checked:boolean){clearReview();setError(null);setSelected(rows=>checked?[...rows,{candidate,amount:''}]:rows.filter(row=>row.candidate.source_review_version_id!==candidate.source_review_version_id))}
 function prepare(event:FormEvent){event.preventDefault();clearReview();setError(null);if(!editable||!page||loading||failed||busy)return
  try{if(!reason.trim())throw new Error('Explain why this proof supports your contribution, or why you are revoking it.');const input:EvidenceInput={entry_version_id:entryVersionId,expected_evidence_version_id:page.head?.current_version_id??null,expected_head_lock_version:page.head?.lock_version??0,accepted:true,reason:reason.trim()}
   let total=0;if(actionMode==='attach'){const amounts=selected.map(row=>({candidate:row.candidate,amount_cents:savingsInputCents(row.amount)}));total=validateEvidenceSelections(amounts,page.entry.signed_cents);input.proofs=amounts.map(row=>evidenceProof(row.candidate,row.amount_cents));input.participant_ownership_accepted=true;input.new_money_reservation_accepted=true}else if(page.current_version?.state!=='attached')throw new Error('There is no current attached proof to revoke.')
   setProposal({action:actionMode,input,selections:structuredClone(selected),total});requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView?.({block:'start'})})
  }catch(failure){setError(message(failure))}
 }
 function changePage(kind:'history'|'candidate',next:number|null,previous=false){clearReview();setLoading(true);if(kind==='history'){setHistoryPages(rows=>previous?rows.slice(0,-1):[...rows,historyCursor]);setHistoryCursor(next)}else{setPages(rows=>previous?rows.slice(0,-1):[...rows,cursor]);setCursor(next)}}
 const canApprove=proposal&&accepted&&(proposal.action==='revoke'||ownership&&newMoney)&&!loading&&!failed&&!busy&&(proposal.action==='attach'?canAttach:canRevoke)&&(!mutation.pending||mutation.pending.action===proposal.action)
 return <div className="evidence-overlay"><section ref={dialog} className="evidence-dialog" role="dialog" aria-modal="true" aria-labelledby="evidence-title" tabIndex={-1}><header><div><p className="eyebrow">Optional private proof</p><h2 id="evidence-title">Review savings evidence</h2></div><button type="button" onClick={onClose} aria-label="Close evidence">Close</button></header>
 <p>Connect already reviewed statement movements to money you reported setting aside. Support is part of that contribution, never extra savings. No money moves here.</p>
 {notice&&<p role="status">{notice}</p>}{(error||mutation.error||mutation.pending?.error)&&<p role="alert">{error??mutation.error??mutation.pending?.error}</p>}
 {denied?<p>Private access is unavailable. Close this view and reopen it in your current workspace.</p>:<><button type="button" onClick={refresh} disabled={loading||Boolean(mutation.pending)}>Refresh evidence</button>{loading&&<p role="status">Checking current private evidence…</p>}{failed&&<p>Evidence could not be refreshed. Earlier information is unavailable for approval.</p>}
 {privateReady&&page&&<><section ref={contribution} tabIndex={-1} aria-label="Reported contribution" className="evidence-contribution"><strong>{savingsDollars(page.entry.signed_cents)} reported · {page.entry.effective_on}</strong><p>{page.entry.reason}</p><p>{savingsDollars(page.entry.evidence_supported_cents)} currently supported · {page.entry.evidence_status.replace('_',' ')}</p>{!canAttach&&<p>This is a historical or ineligible savings record. New proof links are unavailable here. {canRevoke?'You may explicitly revoke its existing proof to free the reserved movement capacity.':'No attached proof is available to revoke.'}</p>}</section>
 {mutation.pending&&<section aria-label="Evidence request recovery" className="evidence-recovery"><h3>Check your earlier evidence request</h3><p>Other changes stay blocked until this {mutation.pending.action==='attach'?'link':'revocation'} is resolved. Closing this view clears financial inputs and keeps only its request identity.</p>{mutation.check&&<button type="button" onClick={()=>void mutation.check!()}>Check earlier evidence result</button>}{mutation.retry&&<button type="button" onClick={()=>void mutation.retry!()}>Retry exact evidence request</button>}{mutation.reviewFresh&&<><label><input type="checkbox" checked={freshConsent} onChange={event=>setFreshConsent(event.target.checked)}/> Re-review this same action with its retained request key</label><button type="button" disabled={!freshConsent} onClick={()=>{setMode(mutation.pending!.action);clearReview();mutation.reviewFresh!();refresh()}}>Prepare fresh evidence review</button></>}</section>}
 {editable&&<form onSubmit={prepare}><fieldset disabled={loading||failed||busy}><legend>Choose the proof you want to review</legend><div className="evidence-actions"><button type="button" disabled={!canAttach||mutation.pending?.fresh&&mutation.pending.action!=='attach'} aria-pressed={actionMode==='attach'} onClick={()=>{setMode('attach');clearReview()}}>Link or replace proof</button><button type="button" disabled={!canRevoke||mutation.pending?.fresh&&mutation.pending.action!=='revoke'} aria-pressed={actionMode==='revoke'} onClick={()=>{setMode('revoke');clearReview()}}>Revoke current proof</button></div>
 {actionMode==='attach'&&<><p>Select reviewed income or a reviewed transfer between your asset accounts. A transfer alone does not prove new money; you must confirm its origin. Up to 20 movements per review.</p><section aria-label="Available statement movements"><h3>Reviewed movements · page {pages.length+1}</h3>{!candidates?.records.length&&<p>No eligible movements on this page. {candidates?.next_cursor!==null&&candidates?.next_cursor!==undefined?'Continue to the next page.':'You can review more statements separately, or leave this contribution self-reported.'}</p>}<ul className="evidence-movements">{candidates?.records.map(candidate=><li key={candidate.source_review_version_id}><label><input type="checkbox" checked={selected.some(row=>row.candidate.source_review_version_id===candidate.source_review_version_id)} disabled={candidate.available_cents<1||selected.length>=20&&!selected.some(row=>row.candidate.source_review_version_id===candidate.source_review_version_id)} onChange={event=>choose(candidate,event.target.checked)}/><strong>{candidate.merchant||'Reviewed statement movement'}</strong></label><p>{candidate.posted_on} · {candidate.account_label} · {candidate.movement_kind==='reviewed_income'?'Reviewed income':'Reviewed asset transfer'}</p><p>{candidate.filename ?? 'Original statement removed'} · {candidate.source_available?'Source file available':'Source file removed; approved facts retained'}</p><p>Signed movement {savingsDollars(candidate.signed_amount_cents)} · Available support {savingsDollars(candidate.available_cents)}</p><MovementLegs legs={candidate.movement_legs}/></li>)}</ul><nav aria-label="Statement movement pages"><button type="button" disabled={!pages.length} onClick={()=>changePage('candidate',pages.at(-1)??null,true)}>Previous movements</button><button type="button" disabled={candidates?.next_cursor==null} onClick={()=>changePage('candidate',candidates!.next_cursor)}>Next movements</button></nav></section>
 {!!selected.length&&<section aria-label="Selected evidence"><h3>{selected.length} selected movement{selected.length===1?'':'s'}</h3>{selected.map((row,index)=><article key={row.candidate.source_review_version_id}><strong>{row.candidate.merchant} · {row.candidate.account_label}</strong><p>{row.candidate.posted_on} · {row.candidate.filename ?? 'Original statement removed'}</p><label>Support amount {index+1} in US dollars<input inputMode="decimal" value={row.amount} onChange={event=>{const value=event.target.value;clearReview();setSelected(rows=>rows.map(item=>item.candidate.source_review_version_id===row.candidate.source_review_version_id?{...item,amount:value}:item))}}/></label><button type="button" onClick={()=>choose(row.candidate,false)}>Remove {row.candidate.merchant}</button></article>)}</section>}</>}
 <label>Reason for evidence review<textarea value={reason} maxLength={2000} onChange={event=>{setReason(event.target.value);clearReview()}}/></label><button type="submit">Review {actionMode==='attach'?'proof link':'proof revocation'}</button></fieldset></form>}
 {proposal&&<section className="evidence-proposal" aria-label="Evidence approval review"><h3 ref={heading} tabIndex={-1}>Review before {proposal.action==='attach'?'linking':'revoking'}</h3>{proposal.action==='attach'?<><p>Link {savingsDollars(proposal.total)} of support within this {savingsDollars(page.entry.signed_cents)} reported contribution. {page.current_version?.state==='attached'?'This replaces the current proof selection.':''}</p><ul>{proposal.selections.map((row,index)=><li key={row.candidate.source_review_version_id}>{row.candidate.merchant} · {row.candidate.posted_on} · {row.candidate.account_label} · {row.candidate.filename ?? 'Original statement removed'} · {savingsDollars(proposal.input.proofs![index].amount_cents)}<MovementLegs legs={row.candidate.movement_legs}/></li>)}</ul></>:<p>Revoke the current {savingsDollars(page.current_version?.supported_cents??0)} proof linkage. Reported savings stay unchanged; approved proof history is retained.</p>}<p>{proposal.input.reason}</p><label><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)} disabled={loading||failed||busy}/> I reviewed this exact evidence change</label>{proposal.action==='attach'&&<><label><input type="checkbox" checked={ownership} onChange={event=>setOwnership(event.target.checked)} disabled={loading||failed||busy}/> These are my movements and support this contribution</label><label><input type="checkbox" checked={newMoney} onChange={event=>setNewMoney(event.target.checked)} disabled={loading||failed||busy}/> This was new money set aside, not borrowing, a refund, or savings I already had</label></>}<button type="button" disabled={!canApprove} onClick={()=>void mutation.submit(proposal.action,proposal.input)}>Approve {proposal.action==='attach'?'proof link':'proof revocation'}</button></section>}
 <button type="button" aria-expanded={historyOpen} aria-controls="evidence-history" onClick={()=>setHistoryOpen(value=>!value)}>Approved proof history</button>{historyOpen&&<section id="evidence-history" aria-label="Approved proof history"><p>History shows approved linkages at that time. Current support above accounts for stale or revoked proof; historical amounts are not added together.</p><ul className="evidence-history">{page.records.map(record=><li key={record.id}><strong>Review {record.version_number} · {record.state==='attached'?'Linked':'Revoked'} · {savingsDollars(record.supported_cents)}</strong><p>{record.approved_at.slice(0,10)} · {record.reason}</p>{record.proof_display?.map((proof,index)=><p key={index}>{proof.merchant} · {proof.posted_on} · {proof.account_label} · {proof.filename ?? 'Original statement removed'} · {proof.source_available?'Source available':'Source removed'}</p>)}</li>)}</ul>{!page.records.length&&<p>No approved proof history yet.</p>}<nav aria-label="Proof history pages"><button type="button" disabled={loading||Boolean(mutation.pending)||!historyPages.length} onClick={()=>changePage('history',historyPages.at(-1)??null,true)}>Previous proof history</button><button type="button" disabled={loading||Boolean(mutation.pending)||page.next_cursor===null} onClick={()=>changePage('history',page.next_cursor)}>Next proof history</button></nav></section>}</> }</>}
 </section></div>
}
