// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import * as api from '../evidenceApi'
import {ApiRequestError} from '../api'
import {baselineScope} from '../test/baselineFixtures'
import {evidenceActor,evidenceCandidate,evidencePage,evidenceVersion} from '../test/evidenceFixtures'
import {SavingsEvidenceDialog} from './SavingsEvidenceDialog'
vi.mock('../evidenceApi',()=>({fetchSavingsEvidence:vi.fn(),fetchSavingsEvidenceCandidates:vi.fn(),mutateSavingsEvidence:vi.fn(),fetchSavingsEvidenceStatus:vi.fn()}))
const view=(changed=vi.fn())=><SavingsEvidenceDialog actorScope={baselineScope} entryVersionId={11} onClose={vi.fn()} onChanged={changed}/>
afterEach(cleanup)
beforeEach(()=>{sessionStorage.clear();vi.resetAllMocks();vi.mocked(api.fetchSavingsEvidence).mockResolvedValue(evidencePage());vi.mocked(api.fetchSavingsEvidenceCandidates).mockResolvedValue({...evidenceActor,records:[evidenceCandidate()],next_cursor:null});vi.mocked(api.mutateSavingsEvidence).mockResolvedValue({...evidenceActor,record:evidenceVersion(),replayed:false});vi.mocked(api.fetchSavingsEvidenceStatus).mockResolvedValue({...evidenceActor,state:'committed',record:evidenceVersion(),replayed:true})})
async function proposal(){fireEvent.click(await screen.findByRole('checkbox',{name:'Fictional paycheck 101'}));fireEvent.change(screen.getByLabelText('Support amount 1 in US dollars'),{target:{value:'25.50'}});fireEvent.change(screen.getByLabelText('Reason for evidence review'),{target:{value:'This supports new wages I reserved.'}});fireEvent.click(screen.getByRole('button',{name:'Review proof link'}));return screen.findByRole('region',{name:'Evidence approval review'})}
function consent(){for(const name of [/I reviewed this exact/,/These are my movements/,/This was new money/])fireEvent.click(screen.getByRole('checkbox',{name}))}
it('requires separate ownership and new-money review; submits exact digests and cents without inflating reported savings',async()=>{render(view());const review=await proposal();expect(within(review).getByText(/Link \$25.50 of support within this \$50.00/)).toBeTruthy();expect(screen.getByRole('button',{name:'Approve proof link'}).matches(':disabled')).toBe(true);expect(api.mutateSavingsEvidence).not.toHaveBeenCalled();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await waitFor(()=>expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1));expect(vi.mocked(api.mutateSavingsEvidence).mock.calls[0][1]).toMatchObject({entry_version_id:11,expected_head_lock_version:0,expected_evidence_version_id:null,accepted:true,participant_ownership_accepted:true,new_money_reservation_accepted:true,proofs:[{amount_cents:2550,expected_source_digest:'a'.repeat(64),expected_account_identity_digest:'b'.repeat(64)}]});await screen.findByText(/reported savings amount is unchanged/);expect(screen.getByRole('region',{name:'Reported contribution'}).textContent).toContain('$50.00')})
it('retains a next cursor on an empty filtered page and preserves explicitly selected amounts across pages',async()=>{vi.mocked(api.fetchSavingsEvidenceCandidates).mockResolvedValueOnce({...evidenceActor,records:[],next_cursor:50}).mockResolvedValueOnce({...evidenceActor,records:[evidenceCandidate()],next_cursor:100}).mockResolvedValue({...evidenceActor,records:[evidenceCandidate(102)],next_cursor:null});render(view());fireEvent.click(await screen.findByRole('button',{name:'Next movements'}));await screen.findByRole('checkbox',{name:'Fictional paycheck 101'});fireEvent.click(screen.getByRole('checkbox',{name:'Fictional paycheck 101'}));fireEvent.change(screen.getByLabelText('Support amount 1 in US dollars'),{target:{value:'10.25'}});fireEvent.click(screen.getByRole('button',{name:'Next movements'}));await screen.findByRole('checkbox',{name:'Fictional paycheck 102'});expect((screen.getByLabelText('Support amount 1 in US dollars') as HTMLInputElement).value).toBe('10.25');expect(api.fetchSavingsEvidenceCandidates).toHaveBeenCalledWith(11,100,expect.any(AbortSignal))})
it('keeps original key after close, discards body, and reconciles committed result without another mutation',async()=>{vi.mocked(api.mutateSavingsEvidence).mockRejectedValueOnce(new Error('Lost response'));const changed=vi.fn();const ui=render(view(changed));await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await screen.findByRole('button',{name:'Retry exact evidence request'});const key=vi.mocked(api.mutateSavingsEvidence).mock.calls[0][2];const stored=sessionStorage.getItem('savings-evidence-request-identities-v1')!;expect(stored).not.toContain('wages');expect(stored).not.toContain('proofs');ui.unmount();render(view(changed));fireEvent.click(await screen.findByRole('button',{name:'Check earlier evidence result'}));await waitFor(()=>expect(changed).toHaveBeenCalledTimes(1));expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1);expect(api.fetchSavingsEvidenceStatus).toHaveBeenCalledWith('attach',11,key,expect.any(AbortSignal))})
it('cold unknown permits only fresh same-action review with the original key; conflict preserves its identity',async()=>{vi.mocked(api.mutateSavingsEvidence).mockRejectedValueOnce(new Error('Lost response')).mockRejectedValueOnce(new ApiRequestError('Original request won',{status:409}));vi.mocked(api.fetchSavingsEvidenceStatus).mockResolvedValue({...evidenceActor,state:'unknown',can_retry:true});const ui=render(view());await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await screen.findByRole('button',{name:'Retry exact evidence request'});const key=vi.mocked(api.mutateSavingsEvidence).mock.calls[0][2];ui.unmount();render(view());fireEvent.click(await screen.findByRole('button',{name:'Check earlier evidence result'}));const fresh=await screen.findByRole('button',{name:'Prepare fresh evidence review'});expect(fresh.matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/Re-review this same action/}));fireEvent.click(fresh);await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await screen.findByText('Original request won');expect(vi.mocked(api.mutateSavingsEvidence).mock.calls[1][2]).toBe(key);expect(sessionStorage.getItem('savings-evidence-request-identities-v1')).toContain(key);expect(screen.queryByRole('button',{name:'Retry exact evidence request'})).toBeNull()})
it('revokes exact current linkage after separate review and renders optional human history without summing transfer legs',async()=>{const page=evidencePage();page.current_version=evidenceVersion();page.head={id:30,current_version_id:31,lock_version:2};page.records=[page.current_version];vi.mocked(api.fetchSavingsEvidence).mockResolvedValue(page);render(view());fireEvent.click(await screen.findByRole('button',{name:'Revoke current proof'}));fireEvent.change(screen.getByLabelText('Reason for evidence review'),{target:{value:'Proof was allocated to the wrong contribution.'}});fireEvent.click(screen.getByRole('button',{name:'Review proof revocation'}));fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this exact/}));fireEvent.click(screen.getByRole('button',{name:'Approve proof revocation'}));await waitFor(()=>expect(api.mutateSavingsEvidence).toHaveBeenCalledWith('revoke',expect.objectContaining({expected_evidence_version_id:31,expected_head_lock_version:2}),expect.any(String),expect.any(AbortSignal)))})
it('clears private selections and hides late responses on actor switch and access denial',async()=>{const ui=render(view());await proposal();vi.mocked(api.fetchSavingsEvidence).mockRejectedValue(new ApiRequestError('Private access revoked',{status:403}));fireEvent.click(screen.getByRole('button',{name:'Refresh evidence'}));await screen.findByText(/Private access is unavailable/);expect(screen.queryByText(/Set aside new wages/)).toBeNull();expect(screen.queryByLabelText('Reason for evidence review')).toBeNull();ui.rerender(<SavingsEvidenceDialog actorScope={{user_id:902,household_id:78}} entryVersionId={11} onClose={vi.fn()} onChanged={vi.fn()}/>);expect(screen.queryByRole('region',{name:'Evidence approval review'})).toBeNull()})
it('does not offer proof editing for historical, withdrawal, or excluded-funding savings',async()=>{for(const entry of [{entry_is_current:false},{entry:{...evidencePage().entry,signed_cents:-100}},{entry:{...evidencePage().entry,funding_source:'borrowed' as const}}]){vi.mocked(api.fetchSavingsEvidence).mockResolvedValue({...evidencePage(),...entry});const ui=render(view());await screen.findByText(/historical or ineligible/);expect(screen.queryByRole('button',{name:'Review proof link'})).toBeNull();ui.unmount()}expect(api.fetchSavingsEvidenceCandidates).not.toHaveBeenCalled()})
it('retains original payload/key for warm retry through metadata-only lock contention and unknown status',async()=>{vi.mocked(api.mutateSavingsEvidence).mockRejectedValueOnce(new Error('Timeout')).mockResolvedValueOnce({...evidenceActor,record:evidenceVersion(),replayed:true});vi.mocked(api.fetchSavingsEvidenceStatus).mockResolvedValueOnce({...evidenceActor,enrollment_id:null,state:'in_flight'}).mockResolvedValueOnce({...evidenceActor,state:'unknown',can_retry:true});render(view());await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));fireEvent.click(await screen.findByRole('button',{name:'Check earlier evidence result'}));await screen.findByText(/still processing/);expect(screen.getByLabelText('Reason for evidence review').matches(':disabled')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Check earlier evidence result'}));await screen.findByText(/retry the exact request/);fireEvent.click(screen.getByRole('button',{name:'Retry exact evidence request'}));await waitFor(()=>expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(2));const calls=vi.mocked(api.mutateSavingsEvidence).mock.calls;expect(calls[1].slice(0,3)).toEqual(calls[0].slice(0,3));expect(screen.queryByRole('region',{name:'Evidence request recovery'})).toBeNull()})
it('aborts reads on close and suppresses late completed financial callbacks on unmount',async()=>{let resolveMutation!:(value:Awaited<ReturnType<typeof api.mutateSavingsEvidence>>)=>void;vi.mocked(api.mutateSavingsEvidence).mockImplementation(()=>new Promise(resolve=>{resolveMutation=resolve}));const changed=vi.fn();const ui=render(view(changed));await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await waitFor(()=>expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1));const signal=vi.mocked(api.mutateSavingsEvidence).mock.calls[0][3]!;ui.unmount();expect(signal.aborted).toBe(true);resolveMutation({...evidenceActor,record:evidenceVersion(),replayed:false});await new Promise(resolve=>setTimeout(resolve,0));expect(changed).not.toHaveBeenCalled();expect(sessionStorage.getItem('savings-evidence-request-identities-v1')).not.toBeNull()})
it('rejects a mutation/status with different actor or enrollment and never marks private proof as saved',async()=>{vi.mocked(api.mutateSavingsEvidence).mockResolvedValue({...evidenceActor,enrollment_id:8,record:evidenceVersion(),replayed:false});const changed=vi.fn();render(view(changed));await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await screen.findByText(/Private access is unavailable/);expect(changed).not.toHaveBeenCalled();expect(screen.queryByRole('region',{name:'Reported contribution'})).toBeNull()})
it('rejects fractions of a cent and over-allocation and invalidates stale approval on refresh',async()=>{render(view());await proposal();consent();fireEvent.change(screen.getByLabelText('Support amount 1 in US dollars'),{target:{value:'0.001'}});expect(screen.queryByRole('region',{name:'Evidence approval review'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Review proof link'}));await screen.findByText(/at most two decimal/);fireEvent.change(screen.getByLabelText('Support amount 1 in US dollars'),{target:{value:'50.01'}});fireEvent.click(screen.getByRole('button',{name:'Review proof link'}));await screen.findByText(/available reviewed movement/);fireEvent.change(screen.getByLabelText('Support amount 1 in US dollars'),{target:{value:'25.50'}});fireEvent.click(screen.getByRole('button',{name:'Review proof link'}));consent();fireEvent.click(screen.getByRole('button',{name:'Refresh evidence'}));await waitFor(()=>expect(api.fetchSavingsEvidence).toHaveBeenCalledTimes(2));expect(screen.queryByRole('region',{name:'Evidence approval review'})).toBeNull();expect(api.mutateSavingsEvidence).not.toHaveBeenCalled()})
it('allows an explicit historical proof revocation to free capacity but never links new proof to that old revision',async()=>{const page=evidencePage();page.entry_is_current=false;page.entry.evidence_status='stale';page.current_version=evidenceVersion();page.head={id:30,current_version_id:31,lock_version:2};vi.mocked(api.fetchSavingsEvidence).mockResolvedValue(page);render(view());await screen.findByText(/free the reserved movement capacity/);expect(screen.getByRole('button',{name:'Link or replace proof'}).matches(':disabled')).toBe(true);expect(api.fetchSavingsEvidenceCandidates).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Reason for evidence review'),{target:{value:'Release stale proof on the superseded contribution.'}});fireEvent.click(screen.getByRole('button',{name:'Review proof revocation'}));fireEvent.click(screen.getByRole('checkbox',{name:/I reviewed this exact/}));fireEvent.click(screen.getByRole('button',{name:'Approve proof revocation'}));await waitFor(()=>expect(api.mutateSavingsEvidence).toHaveBeenCalledWith('revoke',expect.objectContaining({entry_version_id:11,expected_evidence_version_id:31,expected_head_lock_version:2}),expect.any(String),expect.any(AbortSignal)))})
it('refuses a financial mutation when its nonfinancial recovery identity cannot be retained',async()=>{render(view());await proposal();consent();const store=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('Storage blocked')});fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}));await screen.findByText(/No proof change was submitted/);expect(api.mutateSavingsEvidence).not.toHaveBeenCalled();store.mockRestore()})

it('keeps approved provenance readable after full import deletion with nullable source metadata',async()=>{
 const page=evidencePage(),version=evidenceVersion();version.proof_display![0]={...version.proof_display![0],filename:null,source_available:false};page.records=[version]
 vi.mocked(api.fetchSavingsEvidence).mockResolvedValue(page)
 vi.mocked(api.fetchSavingsEvidenceCandidates).mockResolvedValue({...evidenceActor,records:[{...evidenceCandidate(),document_import_id:null,filename:null,source_available:false}],next_cursor:null})
 render(view());await screen.findByText(/Source file removed; approved facts retained/)
 expect(screen.getByRole('checkbox',{name:'Fictional paycheck 101'})).toBeTruthy()
 fireEvent.click(screen.getByRole('button',{name:'Approved proof history'}))
 const history=screen.getByRole('region',{name:'Approved proof history'})
 expect(history.textContent).toContain('Original statement removed')
 expect(history.textContent).toContain('$25.00')
 expect(history.textContent).toContain('Source removed')
 expect(api.mutateSavingsEvidence).not.toHaveBeenCalled()
})


it('keeps cold metadata-only in-flight status unresolved with its original request identity',async()=>{
 vi.mocked(api.mutateSavingsEvidence).mockRejectedValueOnce(new Error('Lost response'))
 const changed=vi.fn(),ui=render(view(changed));await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}))
 await screen.findByRole('button',{name:'Retry exact evidence request'})
 const key=vi.mocked(api.mutateSavingsEvidence).mock.calls[0][2]
 ui.unmount()
 vi.mocked(api.fetchSavingsEvidenceStatus).mockResolvedValueOnce({...evidenceActor,enrollment_id:null,state:'in_flight'})
 render(view(changed));fireEvent.click(await screen.findByRole('button',{name:'Check earlier evidence result'}))
 await screen.findByText(/still processing/)
 expect(screen.getByRole('button',{name:'Check earlier evidence result'})).toBeTruthy()
 expect(screen.queryByRole('button',{name:'Retry exact evidence request'})).toBeNull()
 expect(screen.queryByRole('button',{name:'Prepare fresh evidence review'})).toBeNull()
 expect(screen.queryByText(/Private access is unavailable/)).toBeNull()
 expect(sessionStorage.getItem('savings-evidence-request-identities-v1')).toContain(key)
 expect(changed).not.toHaveBeenCalled();expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1)
 fireEvent.click(screen.getByRole('button',{name:'Check earlier evidence result'}))
 await waitFor(()=>expect(changed).toHaveBeenCalledTimes(1))
 expect(api.fetchSavingsEvidenceStatus).toHaveBeenNthCalledWith(2,'attach',11,key,expect.any(AbortSignal))
 expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1)
})

it.each([
 ['other actor', {actor_scope:{...baselineScope,user_id:902},enrollment_id:null,state:'in_flight'}],
 ['other household', {actor_scope:{...baselineScope,household_id:78},enrollment_id:null,state:'in_flight'}],
 ['other enrollment', {...evidenceActor,enrollment_id:8,state:'in_flight'}],
 ['unknown without enrollment', {...evidenceActor,enrollment_id:null,state:'unknown',can_retry:true}],
 ['committed without enrollment', {...evidenceActor,enrollment_id:null,state:'committed',record:evidenceVersion(),replayed:true}],
 ['committed in another enrollment', {...evidenceActor,enrollment_id:8,state:'committed',record:evidenceVersion(),replayed:true}],
 ['financial payload masquerading as metadata', {...evidenceActor,enrollment_id:null,state:'in_flight',record:evidenceVersion(),replayed:true}],
])('rejects recovery status for %s without acknowledging a private proof',async(_name,status)=>{
 vi.mocked(api.mutateSavingsEvidence).mockRejectedValueOnce(new Error('Lost response'))
 // Exercise invalid wire envelopes as well as valid but mismatched actor contexts.
 vi.mocked(api.fetchSavingsEvidenceStatus).mockResolvedValue(status as Awaited<ReturnType<typeof api.fetchSavingsEvidenceStatus>>)
 const changed=vi.fn();render(view(changed));await proposal();consent();fireEvent.click(screen.getByRole('button',{name:'Approve proof link'}))
 fireEvent.click(await screen.findByRole('button',{name:'Check earlier evidence result'}))
 await screen.findByText(/Private access is unavailable/)
 expect(changed).not.toHaveBeenCalled();expect(api.mutateSavingsEvidence).toHaveBeenCalledTimes(1)
 expect(screen.queryByRole('region',{name:'Reported contribution'})).toBeNull()
 expect(sessionStorage.getItem('savings-evidence-request-identities-v1')).not.toBeNull()
})
