// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import type { SetupHelpState, SetupSupportRequest } from '../lib/setupHelp'
import { SetupHelpDialog } from './SetupHelpDialog'
const mocks = vi.hoisted(() => ({ fetchSetupHelp: vi.fn(), createSetupSupportRequest: vi.fn(), changeOwnSetupSupportRequest: vi.fn() }))
vi.mock('../setupHelpApi', () => mocks)
const request: SetupSupportRequest = { id: 9, status: 'requested', reason: 'practice_numbers', reason_label: 'I entered practice numbers', participant_name: 'Fictional participant', user_id: 901, household_id: 1, cohort_id: 2, program_name: 'Fictional BOG pilot', lock_version: 1, review_id: null, review_expires_at: null, review_state: 'none', created_at: '2026-10-07T10:00:00Z', updated_at: '2026-10-07T10:00:00Z' }
const saved: SetupHelpState = { household_id: 1, cohort_id: 2, financial_generation: 0, available: true, owner_required: false, setup_complete: false, self_restart_available: false, blockers: [{ code: 'saved_financial_records', label: 'You have saved financial information' }], latest_request: null }
const props = { scopeKey: 'actor901:hh1:cohort2', userId: 901, householdId: 1, onClose: vi.fn(), onTopic: vi.fn(() => true), onAskMia: vi.fn(() => true), onRestart: vi.fn() }
beforeEach(() => { vi.resetAllMocks(); window.sessionStorage.clear(); mocks.fetchSetupHelp.mockResolvedValue(saved); props.onTopic.mockReturnValue(true); props.onAskMia.mockReturnValue(true) })
afterEach(() => { cleanup(); vi.restoreAllMocks() })
function sharing() { fireEvent.click(screen.getByRole('checkbox', { name: /Share this request/ })) }
it('routes a correction without requesting or restarting anything', async () => {
  render(<SetupHelpDialog {...props} />)
  await screen.findByText('You have saved financial information')
  fireEvent.click(screen.getByRole('button', { name: 'Income' }))
  expect(props.onTopic).toHaveBeenCalledWith('income'); expect(props.onClose).toHaveBeenCalledOnce()
  expect(mocks.createSetupSupportRequest).not.toHaveBeenCalled(); expect(props.onRestart).not.toHaveBeenCalled()
})
it('keeps the help open and explains when a correction navigation is blocked', async () => {
  props.onTopic.mockReturnValue(false)
  render(<SetupHelpDialog {...props} />); await screen.findByText('You have saved financial information')
  fireEvent.click(screen.getByRole('button', { name: 'Debt' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'That correction tool is not available right now. Finish any open edits, or ask Mia to help.')
  expect(props.onClose).not.toHaveBeenCalled()
})
it('offers self-service only from a verified eligible server response and respects unfinished edits', async () => {
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, self_restart_available: true, blockers: [] })
  const view = render(<SetupHelpDialog {...props} blockedReason="Finish your draft first." />)
  const start = await screen.findByRole('button', { name: 'Review starting setup again' })
  expect(start).toHaveProperty('disabled', true)
  view.rerender(<SetupHelpDialog {...props} />)
  fireEvent.click(start); expect(props.onRestart).toHaveBeenCalledWith()
  expect(screen.queryByRole('button', { name: 'Request support review' })).toBeNull()
})
it('shows corrections while a household partner cannot request a whole-household restart', async () => {
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, available: false, owner_required: true })
  render(<SetupHelpDialog {...props} />)
  await screen.findByText(/household owner needs to review/)
  expect(screen.queryByRole('button', { name: 'Request support review' })).toBeNull()
  expect(screen.getByRole('button', { name: 'Income' })).toBeTruthy()
})
it('requires explicit metadata sharing and does not submit any private financial text', async () => {
  mocks.createSetupSupportRequest.mockResolvedValue({ request, setup_help: { ...saved, latest_request: request } })
  render(<SetupHelpDialog {...props} />)
  const send = await screen.findByRole('button', { name: 'Request support review' })
  expect(send).toHaveProperty('disabled', true)
  fireEvent.change(screen.getByRole('combobox', { name: 'What needs help?' }), { target: { value: 'wrong_setup' } })
  sharing(); fireEvent.click(send)
  await screen.findByText('Waiting for support')
  expect(mocks.createSetupSupportRequest).toHaveBeenCalledWith('wrong_setup', expect.any(String))
  expect(props.onRestart).not.toHaveBeenCalled()
  expect(window.sessionStorage.getItem('household-cfo:setup-support:actor901:hh1:cohort2')).toBeNull()
})
it('preserves the same creation reference and reason after a lost reply', async () => {
  mocks.createSetupSupportRequest.mockRejectedValueOnce(new Error('Reply unavailable')).mockResolvedValueOnce({ request, setup_help: { ...saved, latest_request: request } })
  render(<SetupHelpDialog {...props} />)
  await screen.findByRole('button', { name: 'Request support review' }); sharing()
  fireEvent.click(screen.getByRole('button', { name: 'Request support review' }))
  await screen.findByRole('alert')
  expect(screen.getByRole('combobox', { name: 'What needs help?' })).toHaveProperty('disabled', true)
  fireEvent.click(screen.getByRole('button', { name: 'Retry the same request' }))
  await screen.findByText('Waiting for support')
  expect(mocks.createSetupSupportRequest.mock.calls[1]).toEqual(mocks.createSetupSupportRequest.mock.calls[0])
})
it('keeps a lost cancellation uncertain when status checking fails, then recovers its terminal status', async () => {
  mocks.fetchSetupHelp.mockResolvedValueOnce({ ...saved, latest_request: request }).mockRejectedValueOnce(new Error('Status unavailable')).mockResolvedValueOnce({ ...saved, latest_request: { ...request, status: 'canceled', lock_version: 2 } })
  mocks.changeOwnSetupSupportRequest.mockRejectedValue(new Error('Cancellation reply lost'))
  render(<SetupHelpDialog {...props} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Cancel request' }))
  await screen.findByRole('alert')
  fireEvent.click(screen.getByRole('button', { name: 'Check request status' }))
  await screen.findByText('Status unavailable')
  expect(screen.getByRole('button', { name: 'Cancel request' })).toHaveProperty('disabled', true)
  fireEvent.click(screen.getByRole('button', { name: 'Check request status' }))
  await screen.findByText('Request canceled')
  expect(mocks.changeOwnSetupSupportRequest).toHaveBeenCalledOnce()
})
it('returns an expired prepared request to support without preparing or applying it locally', async () => {
  const ready = { ...request, status: 'ready' as const, review_id: 13, review_state: 'expired' as const }
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, latest_request: ready })
  mocks.changeOwnSetupSupportRequest.mockResolvedValue({ request: { ...request, status: 'in_review' }, setup_help: { ...saved, latest_request: { ...request, status: 'in_review' } } })
  render(<SetupHelpDialog {...props} />)
  await screen.findByRole('heading', { name: 'Review needs refreshing' })
  expect(screen.queryByRole('heading', { name: 'Your review is ready' })).toBeNull()
  fireEvent.click(await screen.findByRole('button', { name: 'Request a fresh review' }))
  await screen.findByText('Support is reviewing')
  expect(mocks.changeOwnSetupSupportRequest).toHaveBeenCalledWith(9, 'reopen', 1)
  expect(props.onRestart).not.toHaveBeenCalled()
})
it('rejects another actor’s request before displaying its identity or enabling a restart', async () => {
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, latest_request: { ...request, user_id: 888, participant_name: 'Private other person' } })
  render(<SetupHelpDialog {...props} />)
  await screen.findByRole('alert')
  expect(screen.queryByText(/Private other person/)).toBeNull()
  expect(screen.queryByRole('button', { name: 'Request support review' })).toBeNull()
})
it('aborts an outstanding read at unmount and ignores a late response', async () => {
  let resolve!: (value: SetupHelpState) => void
  mocks.fetchSetupHelp.mockImplementation(() => new Promise(done => { resolve = done }))
  const view = render(<SetupHelpDialog {...props} />)
  await waitFor(() => expect(mocks.fetchSetupHelp).toHaveBeenCalledOnce())
  const signal = mocks.fetchSetupHelp.mock.calls[0][0] as AbortSignal
  view.unmount(); expect(signal.aborted).toBe(true)
  await act(async () => resolve(saved))
  expect(screen.queryByText('You have saved financial information')).toBeNull()
})
it('does not keep a newly prepared review stale because an earlier review of the same request failed', async () => {
  const ready = { ...request, status: 'ready' as const, review_id: 14, review_state: 'pending' as const }
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, latest_request: ready })
  render(<SetupHelpDialog {...props} staleReview={{ requestId: 9, reviewId: 13 }} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Review prepared restart' }))
  expect(props.onRestart).toHaveBeenCalledWith(9)
  expect(screen.queryByRole('button', { name: 'Request a fresh review' })).toBeNull()
})
it('requires verified current status and fresh sharing before replacing an unusable request reference', async () => {
  const { ApiRequestError } = await import('../api')
  mocks.createSetupSupportRequest.mockRejectedValue(new ApiRequestError('Request not found for this program access', { status: 404 }))
  render(<SetupHelpDialog {...props} />)
  await screen.findByRole('button', { name: 'Request support review' }); sharing()
  fireEvent.click(screen.getByRole('button', { name: 'Request support review' }))
  await screen.findByRole('alert')
  expect(screen.queryByRole('button', { name: 'Start a new support request' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Check request status' }))
  fireEvent.click(await screen.findByRole('button', { name: 'Start a new support request' }))
  expect(screen.getByRole('button', { name: 'Request support review' })).toHaveProperty('disabled', true)
  expect(mocks.createSetupSupportRequest).toHaveBeenCalledOnce()
})

it('does not treat an unidentified earlier review as a permanent stale marker', async () => {
  mocks.fetchSetupHelp.mockResolvedValue({ ...saved, latest_request: { ...request, status: 'ready', review_id: 14, review_state: 'pending' } })
  render(<SetupHelpDialog {...props} staleReview={{ requestId: 9 }} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Review prepared restart' }))
  expect(props.onRestart).toHaveBeenCalledWith(9)
  expect(screen.queryByRole('button', { name: 'Request a fresh review' })).toBeNull()
})
it('reports blocked recovery storage before sending a support request and allows a safe later attempt', async () => {
  const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Quota exceeded', 'QuotaExceededError') })
  render(<SetupHelpDialog {...props} />)
  await screen.findByRole('button', { name: 'Request support review' }); sharing()
  fireEvent.click(screen.getByRole('button', { name: 'Request support review' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'Your browser cannot keep the recovery reference. No support request was sent this time. Enable session storage or try another browser, then retry.')
  expect(mocks.createSetupSupportRequest).not.toHaveBeenCalled()
  expect(screen.queryByRole('button', { name: 'Check request status' })).toBeNull()
  write.mockRestore()
  mocks.createSetupSupportRequest.mockResolvedValue({ request, setup_help: { ...saved, latest_request: request } })
  fireEvent.click(screen.getByRole('button', { name: 'Request support review' }))
  await screen.findByText('Your request is saved. Your financial information and chat have not changed.')
  expect(mocks.createSetupSupportRequest).toHaveBeenCalledOnce()
})
