// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { SetupSupportRequest } from '../lib/setupHelp'
import { SetupSupportInbox } from './SetupSupportInbox'
const mocks = vi.hoisted(() => ({ fetchSetupSupportRequests: vi.fn(), updateSetupSupportRequest: vi.fn() }))
vi.mock('../setupHelpApi', () => mocks)
const request: SetupSupportRequest = { id: 9, permissions: { triage: true, prepare: true, decline: true }, participant_name: 'Fictional Participant', user_id: 3, household_id: 4, cohort_id: 5, program_name: 'BOG pilot', reason: 'practice_numbers', reason_label: 'I entered practice numbers', status: 'requested', lock_version: 2, review_id: null, review_expires_at: null, review_state: 'none', created_at: '2026-10-07T10:00:00Z', updated_at: '2026-10-07T10:00:00Z' }
const base = { actorId: 1, workspaceId: 2, cohortId: 5, isAdmin: false }
function deferred<T>() { let resolve!: (value: T) => void; let reject!: (reason: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no }); return { promise, resolve, reject } }
beforeEach(() => { vi.resetAllMocks(); mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [request], next_cursor: null }); mocks.updateSetupSupportRequest.mockResolvedValue({ request: { ...request, status: 'in_review', lock_version: 3 } }) })
afterEach(cleanup)
describe('staff setup request safety', () => {
  it('fails closed when server permissions are absent or deny writes, even for a platform admin', async () => {
    mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [{ ...request, permissions: undefined }, { ...request, id: 11, permissions: { triage: false, prepare: false, decline: false } }], next_cursor: null })
    render(<SetupSupportInbox {...base} workspaceId={null} cohortId={null} isAdmin />)
    await screen.findByText('#11')
    expect(screen.queryByRole('button', { name: 'Prepare participant review' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'Mark in review' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'Recommend corrections' })).toBeNull()
  })
  it('shares only metadata and gives coaches triage, without preparing or applying a restart', async () => {
    mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [{ ...request, private_chat: 'Hidden chat', account_balance: 'Hidden balance', documents: ['Hidden document'], snapshot_digest: 'Hidden hash' }], next_cursor: null })
    render(<SetupSupportInbox {...base} />)
    await screen.findByText('Fictional Participant')
    expect(screen.getByText('#9')).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'Prepare participant review' })).toBeNull()
    expect(screen.queryByText(/Hidden/)).toBeNull()
    expect(screen.queryByRole('button', { name: /apply|reset/i })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Mark in review' }))
    await waitFor(() => expect(mocks.updateSetupSupportRequest).toHaveBeenCalledWith(9, 'triage', 2))
    expect(await screen.findByRole('status')).toHaveProperty('textContent', 'Request #9: In review.')
  })
  it('requires admin confirmation, blocks double submissions, and reports pending synchronously', async () => {
    const pending = deferred<{ request: SetupSupportRequest }>()
    mocks.updateSetupSupportRequest.mockReturnValue(pending.promise)
    const onPendingChange = vi.fn()
    render(<SetupSupportInbox {...base} isAdmin onPendingChange={onPendingChange} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Prepare participant review' }))
    expect(mocks.updateSetupSupportRequest).not.toHaveBeenCalled()
    expect(screen.getByRole('group', { name: /Confirm review preparation/ }).textContent).toContain('does not change financial records')
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(screen.queryByRole('button', { name: 'Confirm preparation' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Prepare participant review' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm preparation' }))
    expect(onPendingChange).toHaveBeenLastCalledWith(true)
    fireEvent.click(screen.getByRole('button', { name: 'Prepare participant review' }))
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    await act(async () => pending.resolve({ request: { ...request, status: 'ready', lock_version: 3, review_state: 'pending' } }))
    expect(screen.getByRole('status').textContent).toContain('No financial records changed')
    expect(onPendingChange).toHaveBeenLastCalledWith(false)
  })
  it('reloads a conflict without retrying a write or retaining its confirmation', async () => {
    mocks.updateSetupSupportRequest.mockRejectedValue(Object.assign(new Error('Stale'), { status: 409 }))
    mocks.fetchSetupSupportRequests.mockResolvedValueOnce({ records: [request], next_cursor: null }).mockResolvedValue({ records: [{ ...request, lock_version: 7, status: 'ready', review_state: 'stale' }], next_cursor: null })
    render(<SetupSupportInbox {...base} isAdmin />)
    fireEvent.click(await screen.findByRole('button', { name: 'Prepare participant review' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm preparation' }))
    const status = await screen.findByRole('status')
    expect(status.textContent).toContain('previous confirmation has been discarded')
    expect(status.textContent).toContain('Request #9 has been reloaded')
    expect(screen.queryByRole('alert')).toBeNull()
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    expect(screen.queryByRole('button', { name: 'Confirm preparation' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Prepare participant review' }))
    expect(screen.getByRole('button', { name: 'Confirm preparation' })).toBeTruthy()
  })
  it('checks the exact request on a different cursor after a lost reply', async () => {
    mocks.updateSetupSupportRequest.mockRejectedValue(new Error('Reply lost'))
    mocks.fetchSetupSupportRequests.mockResolvedValueOnce({ records: [request], next_cursor: 9 })
      .mockResolvedValueOnce({ records: [{ ...request, id: 10 }], next_cursor: 10 })
      .mockResolvedValueOnce({ records: [{ ...request, id: 10 }], next_cursor: 10 })
      .mockResolvedValueOnce({ records: [{ ...request, status: 'ready', lock_version: 3, review_state: 'pending' }], next_cursor: null })
    render(<SetupSupportInbox {...base} isAdmin />)
    fireEvent.click(await screen.findByRole('button', { name: 'Prepare participant review' }))
    fireEvent.click(screen.getByRole('button', { name: 'Confirm preparation' }))
    await screen.findByText('Waiting for the participant to review and confirm.')
    const status = screen.getByRole('status')
    expect(status.textContent).toContain('Reply lost')
    expect(status.textContent).toContain('Request #9 has been reloaded')
    expect(screen.queryByRole('alert')).toBeNull()
    expect(mocks.fetchSetupSupportRequests).toHaveBeenLastCalledWith(5, 10, expect.any(AbortSignal))
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    expect(within(screen.getByRole('region', { name: 'Request #9' })).queryByRole('button', { name: 'Prepare participant review' })).toBeNull()
  })
  it('paginates a bounded page and refreshes to the first requests', async () => {
    mocks.fetchSetupSupportRequests.mockResolvedValueOnce({ records: [request], next_cursor: 9 }).mockResolvedValueOnce({ records: [{ ...request, id: 8, participant_name: 'Older Participant' }], next_cursor: null }).mockResolvedValue({ records: [request], next_cursor: 9 })
    render(<SetupSupportInbox {...base} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Load more requests' }))
    await screen.findByText('Older Participant')
    expect(screen.queryByText('Fictional Participant')).toBeNull()
    expect(mocks.fetchSetupSupportRequests).toHaveBeenLastCalledWith(5, 9, expect.any(AbortSignal))
    fireEvent.click(screen.getByRole('button', { name: 'Fresh requests' }))
    await screen.findByText('Fictional Participant')
    expect(mocks.fetchSetupSupportRequests).toHaveBeenLastCalledWith(5, null, expect.any(AbortSignal))
  })
  it('clears old scope immediately, aborts pending loads and discards late acknowledgments', async () => {
    const pending = deferred<{ request: SetupSupportRequest }>()
    mocks.updateSetupSupportRequest.mockReturnValue(pending.promise)
    const busy = vi.fn()
    const { rerender } = render(<SetupSupportInbox {...base} isAdmin onPendingChange={busy} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [{ ...request, id: 20, participant_name: 'Different scope' }], next_cursor: null })
    rerender(<SetupSupportInbox {...base} cohortId={6} isAdmin onPendingChange={busy} />)
    expect(screen.queryByText('Fictional Participant')).toBeNull()
    expect(busy).toHaveBeenLastCalledWith(false)
    await screen.findByText('Different scope')
    await act(async () => pending.resolve({ request: { ...request, status: 'in_review' } }))
    expect(screen.queryByText(/Request #9: In review/)).toBeNull()
  })
  it('ignores a late old scope fetch and aborts its signal', async () => {
    const pending = deferred<{ records: SetupSupportRequest[]; next_cursor: number | null }>()
    mocks.fetchSetupSupportRequests.mockReturnValueOnce(pending.promise).mockResolvedValue({ records: [], next_cursor: null })
    const { rerender } = render(<SetupSupportInbox {...base} />)
    await waitFor(() => expect(mocks.fetchSetupSupportRequests).toHaveBeenCalledTimes(1))
    const signal = mocks.fetchSetupSupportRequests.mock.calls[0][2] as AbortSignal
    rerender(<SetupSupportInbox {...base} actorId={2} />)
    expect(signal.aborted).toBe(true)
    await screen.findByText('No setup requests in this scope.')
    await act(async () => pending.resolve({ records: [request], next_cursor: null }))
    expect(screen.queryByText('Fictional Participant')).toBeNull()
  })
  it('provides explicit permission errors and retries a failed load', async () => {
    mocks.fetchSetupSupportRequests.mockRejectedValueOnce(Object.assign(new Error('Denied'), { status: 403 }))
    render(<SetupSupportInbox {...base} />)
    expect((await screen.findByRole('alert')).textContent).toContain('workspace or program permissions')
    fireEvent.click(screen.getByRole('button', { name: 'Retry loading requests' }))
    await screen.findByText('Fictional Participant')
    expect(screen.queryByRole('alert')).toBeNull()
  })
  it('requires explicit workspace context for coaches and does not fetch in platform mode', () => {
    render(<SetupSupportInbox {...base} workspaceId={null} cohortId={null} />)
    expect(screen.getByText('Choose a workspace to view its setup requests.')).toBeTruthy()
    expect(mocks.fetchSetupSupportRequests).not.toHaveBeenCalled()
  })
  it('loads ordinary platform requests for admins and allows only the server-granted actions', async () => {
    const ordinary = { ...request, cohort_id: null, program_name: null }
    mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [ordinary], next_cursor: null })
    mocks.updateSetupSupportRequest.mockResolvedValueOnce({ request: { ...ordinary, status: 'in_review', lock_version: 3 } }).mockResolvedValueOnce({ request: { ...ordinary, status: 'ready', lock_version: 4, review_state: 'pending' } })
    render(<SetupSupportInbox {...base} workspaceId={null} cohortId={null} isAdmin />)
    expect(screen.getByText('Platform support requests; select a program workspace for its requests.')).toBeTruthy()
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    await screen.findByText('Request #9: In review.')
    expect(mocks.fetchSetupSupportRequests).toHaveBeenCalledWith(null, null, expect.any(AbortSignal))
    expect(mocks.updateSetupSupportRequest).toHaveBeenNthCalledWith(1, 9, 'triage', 2)
    fireEvent.click(screen.getByRole('button', { name: 'Prepare participant review' }))
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    fireEvent.click(screen.getByRole('button', { name: 'Confirm preparation' }))
    await screen.findByText('Waiting for the participant to review and confirm.')
    expect(mocks.updateSetupSupportRequest).toHaveBeenNthCalledWith(2, 9, 'prepare', 3)
    expect(screen.getByRole('button', { name: 'Fresh requests' })).toHaveProperty('disabled', false)
  })
  it('hides preparation for an admin own request when the server denies it', async () => {
    mocks.fetchSetupSupportRequests.mockResolvedValue({ records: [{ ...request, user_id: base.actorId, cohort_id: null, program_name: null, permissions: { triage: true, decline: true, prepare: false } }], next_cursor: null })
    render(<SetupSupportInbox {...base} workspaceId={null} cohortId={null} isAdmin />)
    await screen.findByText('Fictional Participant')
    expect(screen.queryByRole('button', { name: 'Prepare participant review' })).toBeNull()
    expect(screen.getByRole('button', { name: 'Mark in review' })).toBeTruthy()
    expect(mocks.updateSetupSupportRequest).not.toHaveBeenCalled()
  })
  it('uses the shared workspace mutation lifecycle and releases its ticket', async () => {
    const ticket = { id: 3, workspaceId: 2 }
    const lifecycle = { pending: false, begin: vi.fn(() => ticket), isCurrent: vi.fn(() => true), finish: vi.fn() }
    render(<SetupSupportInbox {...base} mutationLifecycle={lifecycle} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    await screen.findByRole('status')
    expect(lifecycle.begin).toHaveBeenCalledTimes(1)
    expect(lifecycle.isCurrent).toHaveBeenCalledWith(ticket)
    expect(lifecycle.finish).toHaveBeenCalledWith(ticket)
  })
  it('discards acknowledgments invalidated by the workspace mutation lifecycle', async () => {
    const pending = deferred<{ request: SetupSupportRequest }>()
    mocks.updateSetupSupportRequest.mockReturnValue(pending.promise)
    const ticket = { id: 3, workspaceId: 2 }
    const lifecycle = { pending: false, begin: vi.fn(() => ticket), isCurrent: vi.fn(() => false), finish: vi.fn() }
    render(<SetupSupportInbox {...base} mutationLifecycle={lifecycle} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    await act(async () => pending.resolve({ request: { ...request, status: 'in_review', lock_version: 3 } }))
    expect(screen.queryByText('Request #9: In review.')).toBeNull()
    expect(screen.getByRole('button', { name: 'Mark in review' })).toHaveProperty('disabled', false)
    expect(lifecycle.finish).toHaveBeenCalledWith(ticket)
  })
  it('prevents further writes when a lost reply cannot be verified until a successful refresh', async () => {
    mocks.updateSetupSupportRequest.mockRejectedValue(new Error('Reply lost'))
    mocks.fetchSetupSupportRequests.mockResolvedValueOnce({ records: [request], next_cursor: null }).mockRejectedValueOnce(new Error('Refresh unavailable'))
    render(<SetupSupportInbox {...base} />)
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    const alert = await screen.findByRole('alert')
    expect(alert.textContent).toContain('Reply lost')
    expect(alert.textContent).toContain('Refresh unavailable')
    expect(alert.textContent).toContain('Request #9 could not be verified')
    expect(screen.queryByRole('status')).toBeNull()
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    expect(screen.queryByRole('button', { name: 'Mark in review' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Fresh requests' }))
    await screen.findByText('Request #9 has been reloaded. Check its current status before acting again.')
    expect(screen.queryByRole('alert')).toBeNull()
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
    expect(screen.getByRole('button', { name: 'Mark in review' })).toHaveProperty('disabled', false)
  })
  it('keeps writes blocked and both messages when the exact request cannot be verified in the bounded search', async () => {
    mocks.updateSetupSupportRequest.mockRejectedValue(new Error('Action reply lost'))
    mocks.fetchSetupSupportRequests.mockResolvedValueOnce({ records: [request], next_cursor: null }).mockResolvedValue({ records: [{ ...request, id: 20 }], next_cursor: 20 })
    render(<SetupSupportInbox {...base} isAdmin />)
    fireEvent.click(await screen.findByRole('button', { name: 'Mark in review' }))
    const alert = await screen.findByRole('alert')
    expect(alert.textContent).toContain('Action reply lost')
    expect(alert.textContent).toContain('Request #9 could not be verified')
    expect(screen.queryByRole('status')).toBeNull()
    expect(screen.getByRole('button', { name: 'Mark in review' })).toHaveProperty('disabled', true)
    expect(screen.getByRole('button', { name: 'Prepare participant review' })).toHaveProperty('disabled', true)
    fireEvent.click(screen.getByRole('button', { name: 'Mark in review' }))
    expect(mocks.updateSetupSupportRequest).toHaveBeenCalledTimes(1)
  })
})
