// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { ApiRequestError } from '../api'
import { WorkosSignInDialog, type DialogEmailAuthStep } from './WorkosSignInDialog'

const client = { authOptions: vi.fn(), startEmail: vi.fn(), verifyEmail: vi.fn(), resendEmail: vi.fn(), cancelEmail: vi.fn() }
const props = { client, screen: 'sign-in' as const, onClose: vi.fn(), onAuthenticated: vi.fn(), onExternalSignIn: vi.fn() }
const challenge: DialogEmailAuthStep = { step: 'code', challenge_id: 'challenge_test', email: 'invited@example.test', expires_at: new Date(Date.now() + 600_000).toISOString(), resend_after: 60 }
beforeEach(() => { vi.resetAllMocks(); client.authOptions.mockResolvedValue({ google_enabled: false }); client.startEmail.mockResolvedValue(challenge); client.cancelEmail.mockResolvedValue(undefined); props.onExternalSignIn.mockResolvedValue(undefined) })
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks() })
async function startEmail() {
  fireEvent.change(screen.getByRole('textbox', { name: 'Email address' }), { target: { value: ' Invited@Example.test ' } })
  fireEvent.submit(screen.getByRole('textbox', { name: 'Email address' }).closest('form')!)
  await screen.findByRole('textbox', { name: 'Sign-in code' })
}

it('uses a named modal and offers Google only after a verified enabled option', async () => {
  const view = render(<WorkosSignInDialog {...props} />)
  expect(screen.getByRole('dialog', { name: 'Welcome back' })).toHaveProperty('getAttribute')
  expect(screen.queryByRole('button', { name: 'Continue with Google' })).toBeNull()
  client.authOptions.mockResolvedValue({ google_enabled: true })
  view.unmount(); render(<WorkosSignInDialog {...props} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Continue with Google' }))
  await waitFor(() => expect(props.onExternalSignIn).toHaveBeenCalledWith('google'))
})
it('normalizes the email, keeps the invitation and destination, and verifies the pasted code', async () => {
  client.verifyEmail.mockResolvedValue({ step: 'complete', return_to: '/#MyMoney' })
  render(<WorkosSignInDialog {...props} options={{ invitationToken: 'inv_test', returnTo: '/#MyMoney' }} />)
  await startEmail()
  expect(client.startEmail).toHaveBeenCalledWith({ email: 'invited@example.test', invitationToken: 'inv_test', returnTo: '/#MyMoney' })
  const code = screen.getByRole('textbox', { name: 'Sign-in code' })
  expect(code.getAttribute('autocomplete')).toBe('one-time-code')
  expect(code.getAttribute('inputmode')).toBe('numeric')
  expect(document.activeElement).toBe(code)
  fireEvent.change(code, { target: { value: '123 456' } })
  fireEvent.click(screen.getByRole('button', { name: 'Verify and sign in' }))
  await waitFor(() => expect(props.onAuthenticated).toHaveBeenCalledWith('/#MyMoney'))
  expect(client.verifyEmail).toHaveBeenCalledWith('challenge_test', '123456')
  expect(client.cancelEmail).not.toHaveBeenCalled()
})
it('ignores incomplete codes and prevents duplicated email submissions', async () => {
  let resolve!: (result: DialogEmailAuthStep) => void
  client.startEmail.mockImplementation(() => new Promise<DialogEmailAuthStep>(done => { resolve = done }))
  render(<WorkosSignInDialog {...props} />)
  const email = screen.getByRole('textbox', { name: 'Email address' })
  fireEvent.change(email, { target: { value: 'invited@example.test' } })
  fireEvent.submit(email.closest('form')!); fireEvent.submit(email.closest('form')!)
  expect(client.startEmail).toHaveBeenCalledOnce()
  await act(async () => resolve(challenge))
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123' } })
  expect(screen.getByRole('button', { name: 'Verify and sign in' })).toHaveProperty('disabled', true)
  fireEvent.submit(screen.getByRole('textbox', { name: 'Sign-in code' }).closest('form')!)
  expect(client.verifyEmail).not.toHaveBeenCalled()
})
it('uses safe error copy and never displays raw provider output', async () => {
  client.verifyEmail.mockRejectedValue(new ApiRequestError('SECRET provider detail', { status: 401, code: 'email_code_invalid' }))
  render(<WorkosSignInDialog {...props} />); await startEmail()
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123456' } })
  fireEvent.click(screen.getByRole('button', { name: 'Verify and sign in' }))
  expect((await screen.findByRole('alert')).textContent).toBe('That code did not match. Check the latest email and try again.')
  expect(screen.queryByText(/SECRET/)).toBeNull()
  client.verifyEmail.mockRejectedValue(new ApiRequestError('SECRET unrecognized code', { status: 400, code: '__proto__' }))
  fireEvent.click(screen.getByRole('button', { name: 'Verify and sign in' }))
  await waitFor(() => expect(screen.getByRole('alert').textContent).toBe('Sign-in is temporarily unavailable. Please try again.'))
})
it.each([[60, '1 minute'], [3500, '59 minutes']])('shows the actual rate-limit delay of %s seconds without provider details', async (seconds, copy) => {
  client.startEmail.mockRejectedValue(new ApiRequestError('SECRET provider detail', { status: 429, code: 'auth_rate_limited', payload: { retry_after_sec: seconds } }))
  render(<WorkosSignInDialog {...props} />)
  fireEvent.change(screen.getByLabelText('Email address'), { target: { value: 'invited@example.test' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue with email' }))
  expect((await screen.findByRole('alert')).textContent).toBe(`Too many sign-in attempts. Try again in about ${copy}.`)
  expect(screen.queryByText(/SECRET/)).toBeNull()
  expect(screen.getByRole('button', { name: 'Close' })).toHaveProperty('disabled', false)
})
it('counts down resend cooldown and replaces the challenge and code after resend', async () => {
  vi.useFakeTimers({ toFake: ['Date', 'setInterval', 'clearInterval'] })
  client.resendEmail.mockResolvedValue({ ...challenge, challenge_id: 'challenge_new', resend_after: 60 })
  render(<WorkosSignInDialog {...props} />); await startEmail()
  expect(screen.getByRole('button', { name: 'Resend code in 60s' })).toHaveProperty('disabled', true)
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123456' } })
  await act(async () => { vi.advanceTimersByTime(60_001) })
  fireEvent.click(screen.getByRole('button', { name: 'Resend code' }))
  await waitFor(() => expect(screen.getByRole('textbox', { name: 'Sign-in code' })).toHaveProperty('value', ''))
  expect(client.resendEmail).toHaveBeenCalledWith('challenge_test')
  expect(screen.getByRole('button', { name: 'Resend code in 60s' })).toHaveProperty('disabled', true)
})
it('offers the secure organization flow alone for an explicit organization and does not send an email challenge', async () => {
  render(<WorkosSignInDialog {...props} options={{ organizationId: 'org_test' }} />)
  fireEvent.click(screen.getByRole('button', { name: 'Continue with your organization' }))
  await waitFor(() => expect(props.onExternalSignIn).toHaveBeenCalledWith('sso'))
  expect(client.authOptions).not.toHaveBeenCalled()
  expect(screen.queryByRole('textbox')).toBeNull()
  expect(client.startEmail).not.toHaveBeenCalled()
})
it('blocks verification of an expired challenge while leaving recovery actions available', async () => {
  client.startEmail.mockResolvedValue({ ...challenge, expires_at: new Date(Date.now() - 1000).toISOString(), resend_after: 0 })
  render(<WorkosSignInDialog {...props} />); await startEmail()
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123456' } })
  expect(screen.getByRole('button', { name: 'Verify and sign in' })).toHaveProperty('disabled', true)
  expect(screen.getByRole('button', { name: 'Start again' })).toHaveProperty('disabled', false)
  expect(screen.getByText('Your code has expired. Start again with your email.')).toBeTruthy()
  fireEvent.click(screen.getByRole('button', { name: 'Start again' }))
  expect(screen.getByRole('textbox', { name: 'Email address' })).toBeTruthy()
  expect(client.verifyEmail).not.toHaveBeenCalled()
})
it('routes a policy redirect to work SSO rather than showing an email-code form', async () => {
  client.startEmail.mockResolvedValue({ step: 'redirect', authorization_url: 'https://api.workos.com/user_management/authorize' })
  render(<WorkosSignInDialog {...props} />)
  fireEvent.change(screen.getByRole('textbox', { name: 'Email address' }), { target: { value: 'bank@example.test' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue with email' }))
  await waitFor(() => expect(props.onExternalSignIn).toHaveBeenCalledWith('sso', 'https://api.workos.com/user_management/authorize'))
  expect(screen.queryByRole('textbox', { name: 'Sign-in code' })).toBeNull()
})
it('cancels a stale challenge returned after close and does not move to the code step', async () => {
  let resolve!: (result: DialogEmailAuthStep) => void
  client.startEmail.mockImplementation(() => new Promise<DialogEmailAuthStep>(done => { resolve = done }))
  render(<WorkosSignInDialog {...props} />)
  fireEvent.change(screen.getByRole('textbox', { name: 'Email address' }), { target: { value: 'invited@example.test' } })
  fireEvent.click(screen.getByRole('button', { name: 'Continue with email' }))
  fireEvent.click(screen.getByRole('button', { name: 'Close' }))
  await act(async () => resolve(challenge))
  expect(client.cancelEmail).toHaveBeenCalledWith('challenge_test')
  expect(props.onClose).toHaveBeenCalledOnce()
  expect(props.onAuthenticated).not.toHaveBeenCalled()
  expect(screen.queryByRole('textbox', { name: 'Sign-in code' })).toBeNull()
})
it('does not report a late authentication result after Escape and cancels the active challenge', async () => {
  let resolve!: (result: DialogEmailAuthStep) => void
  client.verifyEmail.mockImplementation(() => new Promise<DialogEmailAuthStep>(done => { resolve = done }))
  render(<WorkosSignInDialog {...props} />); await startEmail()
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123456' } })
  fireEvent.click(screen.getByRole('button', { name: 'Verify and sign in' }))
  fireEvent.keyDown(document, { key: 'Escape' })
  await act(async () => resolve({ step: 'complete', return_to: '/#Home' }))
  expect(props.onAuthenticated).not.toHaveBeenCalled()
  expect(client.cancelEmail).toHaveBeenCalledWith('challenge_test')
})
it('returns to email entry and cancels the old challenge', async () => {
  render(<WorkosSignInDialog {...props} />); await startEmail()
  fireEvent.click(screen.getByRole('button', { name: 'Use a different email' }))
  expect(screen.getByRole('textbox', { name: 'Email address' })).toHaveProperty('value', 'Invited@Example.test')
  expect(client.cancelEmail).toHaveBeenCalledWith('challenge_test')
  expect(screen.queryByRole('textbox', { name: 'Sign-in code' })).toBeNull()
})
it('keeps email usable when optional provider loading fails and can retry it', async () => {
  client.authOptions.mockRejectedValueOnce(new Error('SECRET')).mockResolvedValue({ google_enabled: true })
  render(<WorkosSignInDialog {...props} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Retry sign-in options' }))
  expect(await screen.findByRole('button', { name: 'Continue with Google' })).toBeTruthy()
  expect(screen.queryByText(/SECRET/)).toBeNull()
})
it('restores focus on unmount and displays a canceled external sign-in inside the dialog', async () => {
  const trigger = document.createElement('button'); document.body.append(trigger); trigger.focus()
  const view = render(<WorkosSignInDialog {...props} screen="sign-up" externalError="Sign-in was canceled. You can try again." />)
  expect(screen.getByRole('dialog', { name: 'Join your invited workspace' })).toBeTruthy()
  expect(screen.getByRole('alert').textContent).toMatch(/canceled/)
  view.unmount()
  expect(document.activeElement).toBe(trigger)
  trigger.remove()
})

it('returns to the entered email when the server expires the attempt instead of repeating stale-code requests', async () => {
  client.verifyEmail.mockRejectedValue(new ApiRequestError('private detail', { status: 410, code: 'email_challenge_expired' }))
  render(<WorkosSignInDialog {...props} />); await startEmail()
  fireEvent.change(screen.getByRole('textbox', { name: 'Sign-in code' }), { target: { value: '123456' } })
  fireEvent.click(screen.getByRole('button', { name: 'Verify and sign in' }))
  await screen.findByRole('textbox', { name: 'Email address' })
  expect(screen.queryByRole('textbox', { name: 'Sign-in code' })).toBeNull()
  expect(screen.getByRole('button', { name: 'Continue with email' })).toHaveProperty('disabled', false)
  expect(screen.getByRole('alert').textContent).toContain('Start again')
})

it('allows explicit external cancellation and leaves email usable while the old provider settles', async () => {
  client.authOptions.mockResolvedValue({ google_enabled: true })
  let finish!: () => void
  props.onExternalSignIn.mockImplementation(() => new Promise<void>(resolve => { finish = resolve }))
  const cancel = vi.fn()
  render(<WorkosSignInDialog {...props} onCancelExternal={cancel} />)
  fireEvent.click(await screen.findByRole('button', { name: 'Continue with Google' }))
  await screen.findByRole('button', { name: 'Cancel sign-in' })
  fireEvent.click(screen.getByRole('button', { name: 'Cancel sign-in' }))
  expect(cancel).toHaveBeenCalledOnce()
  expect(screen.getByRole('textbox', { name: 'Email address' })).toHaveProperty('disabled', false)
  await act(async () => { finish() })
  expect(screen.getByRole('status').textContent).toContain('Stopped waiting')
})

it.each([false, true])('does not advertise unconfigured work SSO alongside email when Google is %s', async googleEnabled => {
  client.authOptions.mockResolvedValue({ google_enabled: googleEnabled })
  render(<WorkosSignInDialog {...props} />)
  await waitFor(() => expect(client.authOptions).toHaveBeenCalledOnce())
  if (googleEnabled) expect(await screen.findByRole('button', { name: 'Continue with Google' })).toBeTruthy()
  expect(screen.queryByRole('button', { name: /SSO|Continue with your organization/ })).toBeNull()
  expect(screen.getByRole('button', { name: 'Continue with email' })).toBeTruthy()
})
